-- Generated by qedgen lean-gen from counter.qedspec
-- Source of truth: the .qedspec file. Regenerate with:
--   qedgen lean-gen --spec <spec>.qedspec --output <this-file>

import QEDGen
import CounterProg

open QEDGen.Solana.SBPF
open QEDGen.Solana.SBPF.Memory

namespace Initialize

-- Global constants (from prog module, not re-declared):
--   DATA_LEN_ZERO = 0
--   NON_DUP_MARKER = 255
--   N_ACCOUNTS_INCREMENT = 2
--   N_ACCOUNTS_INIT = 3

-- Error constants
abbrev E_INVALID_ACCOUNT_COUNT : Nat := 1
abbrev E_USER_DATA_LEN_NONZERO : Nat := 2
abbrev E_PDA_DATA_LEN_INVALID : Nat := 3
abbrev E_SYSTEM_PROGRAM_DATA_LEN : Nat := 4
abbrev E_PDA_DUPLICATE : Nat := 5
abbrev E_SYSTEM_PROGRAM_DUPLICATE : Nat := 6
abbrev E_UNABLE_TO_DERIVE_PDA : Nat := 7
abbrev E_PDA_MISMATCH : Nat := 8
abbrev E_INVALID_INSTRUCTION_DATA_LEN : Nat := 9

-- Offset constants
abbrev N_ACCOUNTS : Int := 0
abbrev USER_DATA_LEN : Int := 88
abbrev PDA_DUP_MARKER : Int := 10344

-- Effective address lemmas
@[simp] theorem ea_N_ACCOUNTS (b : Nat) : effectiveAddr b N_ACCOUNTS = b := by
  unfold effectiveAddr N_ACCOUNTS; omega

@[simp] theorem ea_USER_DATA_LEN (b : Nat) : effectiveAddr b USER_DATA_LEN = b + 88 := by
  unfold effectiveAddr USER_DATA_LEN; omega

@[simp] theorem ea_PDA_DUP_MARKER (b : Nat) : effectiveAddr b PDA_DUP_MARKER = b + 10344 := by
  unfold effectiveAddr PDA_DUP_MARKER; omega

-- Guard theorem stubs
-- Hypotheses derived from checks + layout. Fill proofs with wp_exec.

/-- Account count must be 2 (increment) or 3 (initialize) -/
theorem rejects_wrong_account_count
    (inputAddr : Nat) (mem : Mem)
    -- TODO: add guard-specific hypotheses
    :
    (executeFn CounterProg.progAt (initState inputAddr mem) 8).exitCode
      = some E_INVALID_ACCOUNT_COUNT := sorry

/-- User data length must be zero (initialize path) -/
theorem init_rejects_user_data_len
    (inputAddr : Nat) (mem : Mem)
    (userDataLen : Nat)
    (h_userDataLen_val : readU64 mem (inputAddr + 88) = userDataLen)
    (h_userDataLen_ne : userDataLen ≠ DATA_LEN_ZERO)
    :
    (executeFn CounterProg.progAt (initState inputAddr mem) 10).exitCode
      = some E_USER_DATA_LEN_NONZERO := sorry

/-- PDA must not be a duplicate account (initialize path) -/
theorem init_rejects_pda_duplicate
    (inputAddr : Nat) (mem : Mem)
    (h_userDataLen : readU64 mem (inputAddr + 88) = DATA_LEN_ZERO)
    (pdaDupMarker : Nat)
    (h_pdaDupMarker_val : readU8 mem (inputAddr + 10344) = pdaDupMarker)
    (h_pdaDupMarker_ne : pdaDupMarker ≠ NON_DUP_MARKER)
    :
    (executeFn CounterProg.progAt (initState inputAddr mem) 12).exitCode
      = some E_PDA_DUPLICATE := sorry

-- Completeness structure: fill all fields to prove every guard is covered
structure Spec (progAt : Nat → Option Insn) where
  rejects_wrong_account_count :
    ∀ (inputAddr : Nat) (mem : Mem),
    (executeFn progAt (initState inputAddr mem) 8).exitCode = some E_INVALID_ACCOUNT_COUNT
  init_rejects_user_data_len :
    ∀ (inputAddr : Nat) (mem : Mem) (userDataLen : Nat) (_h_userDataLen_val : readU64 mem (inputAddr + 88) = userDataLen) (_h_userDataLen_ne : userDataLen ≠ DATA_LEN_ZERO),
    (executeFn progAt (initState inputAddr mem) 10).exitCode = some E_USER_DATA_LEN_NONZERO
  init_rejects_pda_duplicate :
    ∀ (inputAddr : Nat) (mem : Mem) (_h_userDataLen : readU64 mem (inputAddr + 88) = DATA_LEN_ZERO) (pdaDupMarker : Nat) (_h_pdaDupMarker_val : readU8 mem (inputAddr + 10344) = pdaDupMarker) (_h_pdaDupMarker_ne : pdaDupMarker ≠ NON_DUP_MARKER),
    (executeFn progAt (initState inputAddr mem) 12).exitCode = some E_PDA_DUPLICATE

end Initialize
