-- Auto-generated by qedgen asm2lean from dropset.s
-- DO NOT EDIT — regenerate with: qedgen asm2lean --input dropset.s

import QEDGen.Solana.SBPF

namespace DropsetProg

open QEDGen.Solana.SBPF

/-! ## .equ constants -/

abbrev DISC_REGISTER_MARKET : Nat := 0
abbrev E_INVALID_DISCRIMINANT : Nat := 1
abbrev E_INVALID_INSTRUCTION_LENGTH : Nat := 2
abbrev E_INVALID_NUMBER_OF_ACCOUNTS : Nat := 3
abbrev E_USER_HAS_DATA : Nat := 4
abbrev E_MARKET_ACCOUNT_IS_DUPLICATE : Nat := 5
abbrev E_MARKET_HAS_DATA : Nat := 6
abbrev E_BASE_MINT_IS_DUPLICATE : Nat := 7
abbrev E_QUOTE_MINT_IS_DUPLICATE : Nat := 8
abbrev E_INVALID_MARKET_PUBKEY : Nat := 9
abbrev E_SYSTEM_PROGRAM_IS_DUPLICATE : Nat := 10
abbrev E_INVALID_SYSTEM_PROGRAM_PUBKEY : Nat := 11
abbrev E_RENT_SYSVAR_IS_DUPLICATE : Nat := 12
abbrev E_INVALID_RENT_SYSVAR_PUBKEY : Nat := 13
abbrev ACCT_DUPLICATE_OFF : Int := 0
abbrev ACCT_IS_SIGNER_OFF : Nat := 1
abbrev ACCT_IS_WRITABLE_OFF : Nat := 2
abbrev ACCT_EXECUTABLE_OFF : Nat := 3
abbrev ACCT_RESIZE_DELTA_OFF : Nat := 4
abbrev ACCT_ADDRESS_OFF : Nat := 8
abbrev ACCT_ADDRESS_CHUNK_0_OFF : Int := 8
abbrev ACCT_ADDRESS_CHUNK_1_OFF : Int := 16
abbrev ACCT_ADDRESS_CHUNK_2_OFF : Int := 24
abbrev ACCT_ADDRESS_CHUNK_3_OFF : Int := 32
abbrev ACCT_OWNER_OFF : Nat := 40
abbrev ACCT_OWNER_CHUNK_0_OFF : Nat := 40
abbrev ACCT_OWNER_CHUNK_1_OFF : Nat := 48
abbrev ACCT_OWNER_CHUNK_2_OFF : Nat := 56
abbrev ACCT_OWNER_CHUNK_3_OFF : Nat := 64
abbrev ACCT_DATA_LEN_OFF : Int := 80
abbrev ACCT_DATA_OFF : Int := 88
abbrev ACCT_NON_DUP_MARKER : Nat := 255
abbrev ACCT_STORAGE_OVERHEAD : Nat := 128
abbrev CPI_WRITABLE_SIGNER : Nat := 257
abbrev DATA_LEN_ZERO : Nat := 0
abbrev DATA_BPF_ALIGN_OF_U128 : Nat := 8
abbrev DATA_LEN_MAX_PAD : Nat := 7
abbrev DATA_LEN_AND_MASK : Int := -8
abbrev IB_USER_DATA_LEN_OFF : Int := 88
abbrev IB_USER_PUBKEY_OFF : Nat := 16
abbrev IB_USER_PUBKEY_CHUNK_0_OFF : Nat := 16
abbrev IB_USER_PUBKEY_CHUNK_1_OFF : Nat := 24
abbrev IB_USER_PUBKEY_CHUNK_2_OFF : Nat := 32
abbrev IB_USER_PUBKEY_CHUNK_3_OFF : Nat := 40
abbrev IB_MARKET_DUPLICATE_OFF : Int := 10344
abbrev IB_MARKET_DATA_LEN_OFF : Int := 10424
abbrev IB_MARKET_PUBKEY_OFF : Nat := 10352
abbrev IB_MARKET_PUBKEY_CHUNK_0_OFF : Int := 10352
abbrev IB_MARKET_PUBKEY_CHUNK_1_OFF : Int := 10360
abbrev IB_MARKET_PUBKEY_CHUNK_2_OFF : Int := 10368
abbrev IB_MARKET_PUBKEY_CHUNK_3_OFF : Int := 10376
abbrev IB_ADDRESS_TO_OWNER_REL_OFF_IMM : Nat := 32
abbrev IB_OWNER_TO_LAMPORTS_REL_OFF_IMM : Nat := 32
abbrev IB_LAMPORTS_TO_DATA_REL_OFF_IMM : Nat := 16
abbrev IB_USER_DATA_TO_MARKET_ADDRESS_REL_OFF_IMM : Nat := 10256
abbrev SIZE_OF_U8 : Nat := 1
abbrev SIZE_OF_ADDRESS : Nat := 32
abbrev SIZE_OF_EMPTY_ACCOUNT : Nat := 10336
abbrev SIZE_OF_MARKET_HEADER : Nat := 40
abbrev SIZE_OF_CREATE_ACCOUNT_DATA : Nat := 56
abbrev PUBKEY_CHUNK_0_OFF : Int := 0
abbrev PUBKEY_CHUNK_1_OFF : Int := 8
abbrev PUBKEY_CHUNK_2_OFF : Int := 16
abbrev PUBKEY_CHUNK_3_OFF : Int := 24
abbrev PUBKEY_RENT_CHUNK_0 : Nat := 5862609301215225606
abbrev PUBKEY_RENT_CHUNK_0_LO : Nat := 399877894
abbrev PUBKEY_RENT_CHUNK_0_HI : Nat := 1364995097
abbrev PUBKEY_RENT_CHUNK_1 : Nat := 9219231539345853473
abbrev PUBKEY_RENT_CHUNK_1_LO : Nat := 1288277025
abbrev PUBKEY_RENT_CHUNK_1_HI : Nat := 2146519613
abbrev PUBKEY_RENT_CHUNK_2 : Nat := 4971307250928769624
abbrev PUBKEY_RENT_CHUNK_2_LO : Nat := 149871192
abbrev PUBKEY_RENT_CHUNK_2_HI : Nat := 1157472667
abbrev PUBKEY_RENT_CHUNK_3 : Nat := 2329533411
abbrev PUBKEY_RENT_CHUNK_3_LO : Int := -1965433885
abbrev PUBKEY_RENT_CHUNK_3_HI : Nat := 0
abbrev IB_N_ACCTS_OFF : Int := 0
abbrev INSN_LEN_OFF : Int := -8
abbrev INSN_DISC_OFF : Int := 0
abbrev REGISTER_MARKET_DATA_LEN : Nat := 1
abbrev REGISTER_MARKET_ACCOUNTS_LEN : Nat := 10
abbrev RM_FM_PDA_SEEDS_OFF : Int := -664
abbrev RM_FM_PDA_SEEDS_N_SEEDS : Nat := 3
abbrev RM_FM_PDA_SEEDS_BASE_ADDR_OFF : Int := -664
abbrev RM_FM_PDA_SEEDS_BASE_LEN_OFF : Int := -656
abbrev RM_FM_PDA_SEEDS_QUOTE_ADDR_OFF : Int := -648
abbrev RM_FM_PDA_SEEDS_QUOTE_LEN_OFF : Int := -640
abbrev RM_FM_PDA_SEEDS_BUMP_ADDR_OFF : Int := -632
abbrev RM_FM_PDA_SEEDS_BUMP_LEN_OFF : Int := -624
abbrev RM_FM_PDA_OFF : Int := -616
abbrev RM_FM_PDA_CHUNK_0_OFF : Int := -616
abbrev RM_FM_PDA_CHUNK_1_OFF : Int := -608
abbrev RM_FM_PDA_CHUNK_2_OFF : Int := -600
abbrev RM_FM_PDA_CHUNK_3_OFF : Int := -592
abbrev RM_FM_SYSTEM_PROGRAM_PUBKEY_OFF : Int := -584
abbrev RM_FM_SYSTEM_PROGRAM_PUBKEY_CHUNK_0_OFF : Int := -584
abbrev RM_FM_SYSTEM_PROGRAM_PUBKEY_CHUNK_1_OFF : Int := -576
abbrev RM_FM_SYSTEM_PROGRAM_PUBKEY_CHUNK_2_OFF : Int := -568
abbrev RM_FM_SYSTEM_PROGRAM_PUBKEY_CHUNK_3_OFF : Int := -560
abbrev RM_FM_CREATE_ACCT_DATA_OFF : Int := -552
abbrev RM_FM_CREATE_ACCT_LAMPORTS_UOFF : Int := -548
abbrev RM_FM_CREATE_ACCT_SPACE_UOFF : Int := -540
abbrev RM_FM_CREATE_ACCT_OWNER_UOFF : Int := -532
abbrev RM_FM_CREATE_ACCT_OWNER_CHUNK_0_UOFF : Int := -532
abbrev RM_FM_CREATE_ACCT_OWNER_CHUNK_1_UOFF : Int := -524
abbrev RM_FM_CREATE_ACCT_OWNER_CHUNK_2_UOFF : Int := -516
abbrev RM_FM_CREATE_ACCT_OWNER_CHUNK_3_UOFF : Int := -508
abbrev RM_FM_CPI_N_ACCOUNTS : Nat := 6
abbrev RM_FM_CPI_SOL_ACCT_INFO_OFF : Int := -496
abbrev RM_FM_CPI_SOL_ACCT_META_OFF : Int := -160
abbrev RM_FM_CPI_USER_ACCT_INFO_KEY_UOFF : Int := -496
abbrev RM_FM_CPI_USER_ACCT_INFO_LAMPORTS_UOFF : Int := -488
abbrev RM_FM_CPI_USER_ACCT_INFO_DATA_LEN_UOFF : Int := -480
abbrev RM_FM_CPI_USER_ACCT_INFO_DATA_UOFF : Int := -472
abbrev RM_FM_CPI_USER_ACCT_INFO_OWNER_UOFF : Int := -464
abbrev RM_FM_CPI_USER_ACCT_INFO_RENT_EPOCH_UOFF : Int := -456
abbrev RM_FM_CPI_USER_ACCT_INFO_IS_SIGNER_UOFF : Int := -448
abbrev RM_FM_CPI_USER_ACCT_INFO_IS_WRITABLE_UOFF : Int := -447
abbrev RM_FM_CPI_USER_ACCT_INFO_EXECUTABLE_UOFF : Int := -446
abbrev RM_FM_CPI_USER_ACCT_META_PUBKEY_UOFF : Int := -160
abbrev RM_FM_CPI_USER_ACCT_META_IS_WRITABLE_UOFF : Int := -152
abbrev RM_FM_CPI_USER_ACCT_META_IS_SIGNER_UOFF : Int := -151
abbrev RM_FM_CPI_TARGET_ACCT_INFO_KEY_UOFF : Int := -440
abbrev RM_FM_CPI_TARGET_ACCT_INFO_LAMPORTS_UOFF : Int := -432
abbrev RM_FM_CPI_TARGET_ACCT_INFO_DATA_LEN_UOFF : Int := -424
abbrev RM_FM_CPI_TARGET_ACCT_INFO_DATA_UOFF : Int := -416
abbrev RM_FM_CPI_TARGET_ACCT_INFO_OWNER_UOFF : Int := -408
abbrev RM_FM_CPI_TARGET_ACCT_INFO_RENT_EPOCH_UOFF : Int := -400
abbrev RM_FM_CPI_TARGET_ACCT_INFO_IS_SIGNER_UOFF : Int := -392
abbrev RM_FM_CPI_TARGET_ACCT_INFO_IS_WRITABLE_UOFF : Int := -391
abbrev RM_FM_CPI_TARGET_ACCT_INFO_EXECUTABLE_UOFF : Int := -390
abbrev RM_FM_CPI_TARGET_ACCT_META_PUBKEY_UOFF : Int := -144
abbrev RM_FM_CPI_TARGET_ACCT_META_IS_WRITABLE_UOFF : Int := -136
abbrev RM_FM_CPI_TARGET_ACCT_META_IS_SIGNER_UOFF : Int := -135
abbrev RM_FM_CPI_PROPRIETOR_ACCT_INFO_KEY_UOFF : Int := -384
abbrev RM_FM_CPI_PROPRIETOR_ACCT_INFO_LAMPORTS_UOFF : Int := -376
abbrev RM_FM_CPI_PROPRIETOR_ACCT_INFO_DATA_LEN_UOFF : Int := -368
abbrev RM_FM_CPI_PROPRIETOR_ACCT_INFO_DATA_UOFF : Int := -360
abbrev RM_FM_CPI_PROPRIETOR_ACCT_INFO_OWNER_UOFF : Int := -352
abbrev RM_FM_CPI_PROPRIETOR_ACCT_INFO_RENT_EPOCH_UOFF : Int := -344
abbrev RM_FM_CPI_PROPRIETOR_ACCT_INFO_IS_SIGNER_UOFF : Int := -336
abbrev RM_FM_CPI_PROPRIETOR_ACCT_INFO_IS_WRITABLE_UOFF : Int := -335
abbrev RM_FM_CPI_PROPRIETOR_ACCT_INFO_EXECUTABLE_UOFF : Int := -334
abbrev RM_FM_CPI_PROPRIETOR_ACCT_META_PUBKEY_UOFF : Int := -128
abbrev RM_FM_CPI_PROPRIETOR_ACCT_META_IS_WRITABLE_UOFF : Int := -120
abbrev RM_FM_CPI_PROPRIETOR_ACCT_META_IS_SIGNER_UOFF : Int := -119
abbrev RM_FM_CPI_MINT_ACCT_INFO_KEY_UOFF : Int := -328
abbrev RM_FM_CPI_MINT_ACCT_INFO_LAMPORTS_UOFF : Int := -320
abbrev RM_FM_CPI_MINT_ACCT_INFO_DATA_LEN_UOFF : Int := -312
abbrev RM_FM_CPI_MINT_ACCT_INFO_DATA_UOFF : Int := -304
abbrev RM_FM_CPI_MINT_ACCT_INFO_OWNER_UOFF : Int := -296
abbrev RM_FM_CPI_MINT_ACCT_INFO_RENT_EPOCH_UOFF : Int := -288
abbrev RM_FM_CPI_MINT_ACCT_INFO_IS_SIGNER_UOFF : Int := -280
abbrev RM_FM_CPI_MINT_ACCT_INFO_IS_WRITABLE_UOFF : Int := -279
abbrev RM_FM_CPI_MINT_ACCT_INFO_EXECUTABLE_UOFF : Int := -278
abbrev RM_FM_CPI_MINT_ACCT_META_PUBKEY_UOFF : Int := -112
abbrev RM_FM_CPI_MINT_ACCT_META_IS_WRITABLE_UOFF : Int := -104
abbrev RM_FM_CPI_MINT_ACCT_META_IS_SIGNER_UOFF : Int := -103
abbrev RM_FM_CPI_SYSTEM_PROGRAM_ACCT_INFO_KEY_UOFF : Int := -272
abbrev RM_FM_CPI_SYSTEM_PROGRAM_ACCT_INFO_LAMPORTS_UOFF : Int := -264
abbrev RM_FM_CPI_SYSTEM_PROGRAM_ACCT_INFO_DATA_LEN_UOFF : Int := -256
abbrev RM_FM_CPI_SYSTEM_PROGRAM_ACCT_INFO_DATA_UOFF : Int := -248
abbrev RM_FM_CPI_SYSTEM_PROGRAM_ACCT_INFO_OWNER_UOFF : Int := -240
abbrev RM_FM_CPI_SYSTEM_PROGRAM_ACCT_INFO_RENT_EPOCH_UOFF : Int := -232
abbrev RM_FM_CPI_SYSTEM_PROGRAM_ACCT_INFO_IS_SIGNER_UOFF : Int := -224
abbrev RM_FM_CPI_SYSTEM_PROGRAM_ACCT_INFO_IS_WRITABLE_UOFF : Int := -223
abbrev RM_FM_CPI_SYSTEM_PROGRAM_ACCT_INFO_EXECUTABLE_UOFF : Int := -222
abbrev RM_FM_CPI_SYSTEM_PROGRAM_ACCT_META_PUBKEY_UOFF : Int := -96
abbrev RM_FM_CPI_SYSTEM_PROGRAM_ACCT_META_IS_WRITABLE_UOFF : Int := -88
abbrev RM_FM_CPI_SYSTEM_PROGRAM_ACCT_META_IS_SIGNER_UOFF : Int := -87
abbrev RM_FM_CPI_TOKEN_PROGRAM_ACCT_INFO_KEY_UOFF : Int := -216
abbrev RM_FM_CPI_TOKEN_PROGRAM_ACCT_INFO_LAMPORTS_UOFF : Int := -208
abbrev RM_FM_CPI_TOKEN_PROGRAM_ACCT_INFO_DATA_LEN_UOFF : Int := -200
abbrev RM_FM_CPI_TOKEN_PROGRAM_ACCT_INFO_DATA_UOFF : Int := -192
abbrev RM_FM_CPI_TOKEN_PROGRAM_ACCT_INFO_OWNER_UOFF : Int := -184
abbrev RM_FM_CPI_TOKEN_PROGRAM_ACCT_INFO_RENT_EPOCH_UOFF : Int := -176
abbrev RM_FM_CPI_TOKEN_PROGRAM_ACCT_INFO_IS_SIGNER_UOFF : Int := -168
abbrev RM_FM_CPI_TOKEN_PROGRAM_ACCT_INFO_IS_WRITABLE_UOFF : Int := -167
abbrev RM_FM_CPI_TOKEN_PROGRAM_ACCT_INFO_EXECUTABLE_UOFF : Int := -166
abbrev RM_FM_CPI_TOKEN_PROGRAM_ACCT_META_PUBKEY_UOFF : Int := -80
abbrev RM_FM_CPI_TOKEN_PROGRAM_ACCT_META_IS_WRITABLE_UOFF : Int := -72
abbrev RM_FM_CPI_TOKEN_PROGRAM_ACCT_META_IS_SIGNER_UOFF : Int := -71
abbrev RM_FM_SIGNERS_SEEDS_ADDR_UOFF : Int := -64
abbrev RM_FM_SIGNERS_SEEDS_LEN_UOFF : Int := -56
abbrev RM_FM_SOL_INSN_OFF : Int := -48
abbrev RM_FM_SOL_INSN_PROGRAM_ID_UOFF : Int := -48
abbrev RM_FM_SOL_INSN_ACCOUNTS_UOFF : Int := -40
abbrev RM_FM_SOL_INSN_ACCOUNT_LEN_UOFF : Int := -32
abbrev RM_FM_SOL_INSN_DATA_UOFF : Int := -24
abbrev RM_FM_SOL_INSN_DATA_LEN_UOFF : Int := -16
abbrev RM_FM_BUMP_OFF : Int := -8
abbrev RM_FM_PDA_SEEDS_TO_SOL_INSN_REL_OFF_IMM : Nat := 616
abbrev RM_FM_PDA_TO_SIGNERS_SEEDS_REL_OFF_IMM : Nat := 552
abbrev RM_FM_CREATE_ACCT_DATA_TO_CPI_ACCT_METAS_REL_OFF_IMM : Nat := 392
abbrev RM_MISC_BASE_DUPLICATE_OFF : Int := 20680
abbrev RM_MISC_BASE_DATA_LEN_OFF : Int := 20760
abbrev RM_MISC_BASE_ADDR_OFF : Nat := 20688
abbrev RM_MISC_QUOTE_OFF : Nat := 31016
abbrev RM_MISC_QUOTE_DUPLICATE_OFF : Int := 31016
abbrev RM_MISC_QUOTE_ADDR_OFF : Nat := 31024
abbrev RM_MISC_QUOTE_DATA_LEN_OFF : Int := 31096
abbrev RM_MISC_TRY_FIND_PDA_SEEDS_LEN : Nat := 2
abbrev RM_MISC_CREATE_ACCOUNT_N_ACCOUNTS : Nat := 2
abbrev RM_MISC_N_PDA_SIGNERS : Nat := 1

/-! ## Program (chunked lookup for O(1) simp) -/

def progAt_0 : Nat → Option QEDGen.Solana.SBPF.Insn
  | 0 => some (.mov32 .r0 (.imm E_INVALID_INSTRUCTION_LENGTH))  -- 0: e_invalid_instruction_length
  | 1 => some (.exit)  -- 1
  | 2 => some (.mov32 .r0 (.imm E_INVALID_NUMBER_OF_ACCOUNTS))  -- 2: e_invalid_number_of_accounts
  | 3 => some (.exit)  -- 3
  | 4 => some (.mov32 .r0 (.imm E_USER_HAS_DATA))  -- 4: e_user_has_data
  | 5 => some (.exit)  -- 5
  | 6 => some (.mov32 .r0 (.imm E_MARKET_ACCOUNT_IS_DUPLICATE))  -- 6: e_market_account_is_duplicate
  | 7 => some (.exit)  -- 7
  | 8 => some (.mov32 .r0 (.imm E_MARKET_HAS_DATA))  -- 8: e_market_has_data
  | 9 => some (.exit)  -- 9
  | 10 => some (.mov32 .r0 (.imm E_BASE_MINT_IS_DUPLICATE))  -- 10: e_base_mint_is_duplicate
  | 11 => some (.exit)  -- 11
  | 12 => some (.mov32 .r0 (.imm E_QUOTE_MINT_IS_DUPLICATE))  -- 12: e_quote_mint_is_duplicate
  | 13 => some (.exit)  -- 13
  | 14 => some (.mov32 .r0 (.imm E_INVALID_MARKET_PUBKEY))  -- 14: e_invalid_market_pubkey
  | 15 => some (.exit)  -- 15
  | 16 => some (.mov32 .r0 (.imm E_SYSTEM_PROGRAM_IS_DUPLICATE))  -- 16: e_system_program_is_duplicate
  | 17 => some (.exit)  -- 17
  | 18 => some (.mov32 .r0 (.imm E_INVALID_SYSTEM_PROGRAM_PUBKEY))  -- 18: e_invalid_system_program_pubkey
  | 19 => some (.exit)  -- 19
  | 20 => some (.mov32 .r0 (.imm E_RENT_SYSVAR_IS_DUPLICATE))  -- 20: e_rent_sysvar_is_duplicate
  | 21 => some (.exit)  -- 21
  | 22 => some (.mov32 .r0 (.imm E_INVALID_RENT_SYSVAR_PUBKEY))  -- 22: e_invalid_rent_sysvar_pubkey
  | 23 => some (.exit)  -- 23
  | 24 => some (.ldx .dword .r3 .r1 IB_N_ACCTS_OFF)  -- 24: entrypoint
  | 25 => some (.ldx .dword .r4 .r2 INSN_LEN_OFF)  -- 25
  | 26 => some (.ldx .byte .r5 .r2 INSN_DISC_OFF)  -- 26
  | 27 => some (.jeq .r5 (.imm DISC_REGISTER_MARKET) 30)  -- 27
  | 28 => some (.mov32 .r0 (.imm E_INVALID_DISCRIMINANT))  -- 28
  | 29 => some (.exit)  -- 29
  | 30 => some (.jlt .r3 (.imm REGISTER_MARKET_ACCOUNTS_LEN) 2)  -- 30: register_market
  | 31 => some (.jne .r4 (.imm REGISTER_MARKET_DATA_LEN) 0)  -- 31
  | 32 => some (.ldx .dword .r9 .r1 IB_USER_DATA_LEN_OFF)  -- 32
  | 33 => some (.jne .r9 (.imm DATA_LEN_ZERO) 4)  -- 33
  | 34 => some (.ldx .byte .r9 .r1 IB_MARKET_DUPLICATE_OFF)  -- 34
  | 35 => some (.jne .r9 (.imm ACCT_NON_DUP_MARKER) 6)  -- 35
  | 36 => some (.ldx .dword .r9 .r1 IB_MARKET_DATA_LEN_OFF)  -- 36
  | 37 => some (.jne .r9 (.imm DATA_LEN_ZERO) 8)  -- 37
  | 38 => some (.ldx .byte .r9 .r1 RM_MISC_BASE_DUPLICATE_OFF)  -- 38
  | 39 => some (.jne .r9 (.imm ACCT_NON_DUP_MARKER) 10)  -- 39
  | 40 => some (.mov64 .r9 (.reg .r1))  -- 40
  | 41 => some (.add64 .r9 (.imm RM_MISC_BASE_ADDR_OFF))  -- 41
  | 42 => some (.stx .dword .r10 RM_FM_PDA_SEEDS_BASE_ADDR_OFF .r9)  -- 42
  | 43 => some (.mov64 .r9 (.imm SIZE_OF_ADDRESS))  -- 43
  | 44 => some (.stx .dword .r10 RM_FM_PDA_SEEDS_BASE_LEN_OFF .r9)  -- 44
  | 45 => some (.ldx .dword .r9 .r1 RM_MISC_BASE_DATA_LEN_OFF)  -- 45
  | 46 => some (.add64 .r9 (.imm DATA_LEN_MAX_PAD))  -- 46
  | 47 => some (.and64 .r9 (.imm DATA_LEN_AND_MASK))  -- 47
  | 48 => some (.add64 .r9 (.reg .r1))  -- 48
  | 49 => some (.ldx .byte .r8 .r9 RM_MISC_QUOTE_DUPLICATE_OFF)  -- 49
  | 50 => some (.jne .r8 (.imm ACCT_NON_DUP_MARKER) 12)  -- 50
  | 51 => some (.mov64 .r8 (.reg .r9))  -- 51
  | 52 => some (.add64 .r8 (.imm RM_MISC_QUOTE_ADDR_OFF))  -- 52
  | 53 => some (.stx .dword .r10 RM_FM_PDA_SEEDS_QUOTE_ADDR_OFF .r8)  -- 53
  | 54 => some (.ldx .dword .r8 .r9 RM_MISC_QUOTE_DATA_LEN_OFF)  -- 54
  | 55 => some (.add64 .r8 (.imm DATA_LEN_MAX_PAD))  -- 55
  | 56 => some (.and64 .r8 (.imm DATA_LEN_AND_MASK))  -- 56
  | 57 => some (.add64 .r9 (.imm RM_MISC_QUOTE_OFF))  -- 57
  | 58 => some (.add64 .r9 (.reg .r8))  -- 58
  | 59 => some (.add64 .r9 (.imm SIZE_OF_EMPTY_ACCOUNT))  -- 59
  | 60 => some (.mov64 .r8 (.imm SIZE_OF_ADDRESS))  -- 60
  | 61 => some (.stx .dword .r10 RM_FM_PDA_SEEDS_QUOTE_LEN_OFF .r8)  -- 61
  | 62 => some (.mov64 .r6 (.reg .r1))  -- 62
  | 63 => some (.mov64 .r1 (.reg .r10))  -- 63
  | 64 => some (.add64 .r1 (.imm RM_FM_PDA_SEEDS_OFF))  -- 64
  | 65 => some (.mov64 .r3 (.reg .r2))  -- 65
  | 66 => some (.add64 .r3 (.imm REGISTER_MARKET_DATA_LEN))  -- 66
  | 67 => some (.mov64 .r2 (.imm RM_MISC_TRY_FIND_PDA_SEEDS_LEN))  -- 67
  | 68 => some (.mov64 .r4 (.reg .r10))  -- 68
  | 69 => some (.add64 .r4 (.imm RM_FM_PDA_OFF))  -- 69
  | 70 => some (.mov64 .r5 (.reg .r10))  -- 70
  | 71 => some (.add64 .r5 (.imm RM_FM_BUMP_OFF))  -- 71
  | 72 => some (.call .sol_try_find_program_address)  -- 72
  | 73 => some (.ldx .dword .r7 .r6 IB_MARKET_PUBKEY_CHUNK_0_OFF)  -- 73
  | 74 => some (.ldx .dword .r8 .r10 RM_FM_PDA_CHUNK_0_OFF)  -- 74
  | 75 => some (.jne .r7 (.reg .r8) 14)  -- 75
  | 76 => some (.ldx .dword .r7 .r6 IB_MARKET_PUBKEY_CHUNK_1_OFF)  -- 76
  | 77 => some (.ldx .dword .r8 .r10 RM_FM_PDA_CHUNK_1_OFF)  -- 77
  | 78 => some (.jne .r7 (.reg .r8) 14)  -- 78
  | 79 => some (.ldx .dword .r7 .r6 IB_MARKET_PUBKEY_CHUNK_2_OFF)  -- 79
  | 80 => some (.ldx .dword .r8 .r10 RM_FM_PDA_CHUNK_2_OFF)  -- 80
  | 81 => some (.jne .r7 (.reg .r8) 14)  -- 81
  | 82 => some (.ldx .dword .r7 .r6 IB_MARKET_PUBKEY_CHUNK_3_OFF)  -- 82
  | 83 => some (.ldx .dword .r8 .r10 RM_FM_PDA_CHUNK_3_OFF)  -- 83
  | 84 => some (.jne .r7 (.reg .r8) 14)  -- 84
  | 85 => some (.stx .dword .r10 RM_FM_PDA_SEEDS_BUMP_ADDR_OFF .r5)  -- 85
  | 86 => some (.mov64 .r7 (.imm SIZE_OF_U8))  -- 86
  | 87 => some (.stx .dword .r10 RM_FM_PDA_SEEDS_BUMP_LEN_OFF .r7)  -- 87
  | 88 => some (.ldx .dword .r7 .r3 PUBKEY_CHUNK_0_OFF)  -- 88
  | 89 => some (.stx .dword .r10 RM_FM_CREATE_ACCT_OWNER_CHUNK_0_UOFF .r7)  -- 89
  | 90 => some (.ldx .dword .r7 .r3 PUBKEY_CHUNK_1_OFF)  -- 90
  | 91 => some (.stx .dword .r10 RM_FM_CREATE_ACCT_OWNER_CHUNK_1_UOFF .r7)  -- 91
  | 92 => some (.ldx .dword .r7 .r3 PUBKEY_CHUNK_2_OFF)  -- 92
  | 93 => some (.stx .dword .r10 RM_FM_CREATE_ACCT_OWNER_CHUNK_2_UOFF .r7)  -- 93
  | 94 => some (.ldx .dword .r7 .r3 PUBKEY_CHUNK_3_OFF)  -- 94
  | 95 => some (.stx .dword .r10 RM_FM_CREATE_ACCT_OWNER_CHUNK_3_UOFF .r7)  -- 95
  | 96 => some (.ldx .byte .r7 .r9 ACCT_DUPLICATE_OFF)  -- 96
  | 97 => some (.jne .r7 (.imm ACCT_NON_DUP_MARKER) 16)  -- 97
  | 98 => some (.ldx .dword .r7 .r9 ACCT_ADDRESS_CHUNK_0_OFF)  -- 98
  | 99 => some (.ldx .dword .r8 .r10 RM_FM_SYSTEM_PROGRAM_PUBKEY_CHUNK_0_OFF)  -- 99
  | _ => none

def progAt_1 : Nat → Option QEDGen.Solana.SBPF.Insn
  | 100 => some (.jne .r7 (.reg .r8) 18)  -- 100
  | 101 => some (.ldx .dword .r7 .r9 ACCT_ADDRESS_CHUNK_1_OFF)  -- 101
  | 102 => some (.ldx .dword .r8 .r10 RM_FM_SYSTEM_PROGRAM_PUBKEY_CHUNK_1_OFF)  -- 102
  | 103 => some (.jne .r7 (.reg .r8) 18)  -- 103
  | 104 => some (.ldx .dword .r7 .r9 ACCT_ADDRESS_CHUNK_2_OFF)  -- 104
  | 105 => some (.ldx .dword .r8 .r10 RM_FM_SYSTEM_PROGRAM_PUBKEY_CHUNK_2_OFF)  -- 105
  | 106 => some (.jne .r7 (.reg .r8) 18)  -- 106
  | 107 => some (.ldx .dword .r7 .r9 ACCT_ADDRESS_CHUNK_3_OFF)  -- 107
  | 108 => some (.ldx .dword .r8 .r10 RM_FM_SYSTEM_PROGRAM_PUBKEY_CHUNK_3_OFF)  -- 108
  | 109 => some (.jne .r7 (.reg .r8) 18)  -- 109
  | 110 => some (.mov64 .r7 (.reg .r9))  -- 110
  | 111 => some (.add64 .r7 (.imm ACCT_ADDRESS_OFF))  -- 111
  | 112 => some (.stx .dword .r10 RM_FM_SOL_INSN_PROGRAM_ID_UOFF .r7)  -- 112
  | 113 => some (.ldx .dword .r7 .r9 ACCT_DATA_LEN_OFF)  -- 113
  | 114 => some (.add64 .r7 (.imm DATA_LEN_MAX_PAD))  -- 114
  | 115 => some (.and64 .r7 (.imm DATA_LEN_AND_MASK))  -- 115
  | 116 => some (.add64 .r9 (.reg .r7))  -- 116
  | 117 => some (.add64 .r9 (.imm SIZE_OF_EMPTY_ACCOUNT))  -- 117
  | 118 => some (.ldx .byte .r7 .r9 ACCT_DUPLICATE_OFF)  -- 118
  | 119 => some (.jne .r7 (.imm ACCT_NON_DUP_MARKER) 20)  -- 119
  | 120 => some (.ldx .dword .r7 .r9 ACCT_ADDRESS_CHUNK_0_OFF)  -- 120
  | 121 => some (.lddw .r8 PUBKEY_RENT_CHUNK_0)  -- 121
  | 122 => some (.jne .r7 (.reg .r8) 22)  -- 122
  | 123 => some (.ldx .dword .r7 .r9 ACCT_ADDRESS_CHUNK_1_OFF)  -- 123
  | 124 => some (.lddw .r8 PUBKEY_RENT_CHUNK_1)  -- 124
  | 125 => some (.jne .r7 (.reg .r8) 22)  -- 125
  | 126 => some (.ldx .dword .r7 .r9 ACCT_ADDRESS_CHUNK_2_OFF)  -- 126
  | 127 => some (.lddw .r8 PUBKEY_RENT_CHUNK_2)  -- 127
  | 128 => some (.jne .r7 (.reg .r8) 22)  -- 128
  | 129 => some (.ldx .dword .r7 .r9 ACCT_ADDRESS_CHUNK_3_OFF)  -- 129
  | 130 => some (.mov32 .r8 (.imm PUBKEY_RENT_CHUNK_3_LO))  -- 130
  | 131 => some (.jne .r7 (.reg .r8) 22)  -- 131
  | 132 => some (.mov64 .r7 (.imm SIZE_OF_MARKET_HEADER))  -- 132
  | 133 => some (.stx .dword .r10 RM_FM_CREATE_ACCT_SPACE_UOFF .r7)  -- 133
  | 134 => some (.add64 .r7 (.imm ACCT_STORAGE_OVERHEAD))  -- 134
  | 135 => some (.ldx .dword .r8 .r9 ACCT_DATA_OFF)  -- 135
  | 136 => some (.mul64 .r7 (.reg .r8))  -- 136
  | 137 => some (.stx .dword .r10 RM_FM_CREATE_ACCT_LAMPORTS_UOFF .r7)  -- 137
  | 138 => some (.st .half .r10 RM_FM_CPI_USER_ACCT_INFO_IS_SIGNER_UOFF CPI_WRITABLE_SIGNER)  -- 138
  | 139 => some (.st .half .r10 RM_FM_CPI_USER_ACCT_META_IS_WRITABLE_UOFF CPI_WRITABLE_SIGNER)  -- 139
  | 140 => some (.st .half .r10 RM_FM_CPI_TARGET_ACCT_INFO_IS_SIGNER_UOFF CPI_WRITABLE_SIGNER)  -- 140
  | 141 => some (.st .half .r10 RM_FM_CPI_TARGET_ACCT_META_IS_WRITABLE_UOFF CPI_WRITABLE_SIGNER)  -- 141
  | 142 => some (.add64 .r6 (.imm IB_USER_PUBKEY_OFF))  -- 142
  | 143 => some (.stx .dword .r10 RM_FM_CPI_USER_ACCT_META_PUBKEY_UOFF .r6)  -- 143
  | 144 => some (.stx .dword .r10 RM_FM_CPI_USER_ACCT_INFO_KEY_UOFF .r6)  -- 144
  | 145 => some (.add64 .r6 (.imm IB_ADDRESS_TO_OWNER_REL_OFF_IMM))  -- 145
  | 146 => some (.stx .dword .r10 RM_FM_CPI_USER_ACCT_INFO_OWNER_UOFF .r6)  -- 146
  | 147 => some (.add64 .r6 (.imm IB_OWNER_TO_LAMPORTS_REL_OFF_IMM))  -- 147
  | 148 => some (.stx .dword .r10 RM_FM_CPI_USER_ACCT_INFO_LAMPORTS_UOFF .r6)  -- 148
  | 149 => some (.add64 .r6 (.imm IB_LAMPORTS_TO_DATA_REL_OFF_IMM))  -- 149
  | 150 => some (.stx .dword .r10 RM_FM_CPI_USER_ACCT_INFO_DATA_UOFF .r6)  -- 150
  | 151 => some (.add64 .r6 (.imm IB_USER_DATA_TO_MARKET_ADDRESS_REL_OFF_IMM))  -- 151
  | 152 => some (.stx .dword .r10 RM_FM_CPI_TARGET_ACCT_META_PUBKEY_UOFF .r6)  -- 152
  | 153 => some (.stx .dword .r10 RM_FM_CPI_TARGET_ACCT_INFO_KEY_UOFF .r6)  -- 153
  | 154 => some (.add64 .r6 (.imm IB_ADDRESS_TO_OWNER_REL_OFF_IMM))  -- 154
  | 155 => some (.stx .dword .r10 RM_FM_CPI_TARGET_ACCT_INFO_OWNER_UOFF .r6)  -- 155
  | 156 => some (.add64 .r6 (.imm IB_OWNER_TO_LAMPORTS_REL_OFF_IMM))  -- 156
  | 157 => some (.stx .dword .r10 RM_FM_CPI_TARGET_ACCT_INFO_LAMPORTS_UOFF .r6)  -- 157
  | 158 => some (.add64 .r6 (.imm IB_LAMPORTS_TO_DATA_REL_OFF_IMM))  -- 158
  | 159 => some (.stx .dword .r10 RM_FM_CPI_TARGET_ACCT_INFO_DATA_UOFF .r6)  -- 159
  | 160 => some (.stx .dword .r10 RM_FM_SIGNERS_SEEDS_ADDR_UOFF .r1)  -- 160
  | 161 => some (.mov64 .r7 (.imm RM_FM_PDA_SEEDS_N_SEEDS))  -- 161
  | 162 => some (.stx .dword .r10 RM_FM_SIGNERS_SEEDS_LEN_UOFF .r7)  -- 162
  | 163 => some (.mov64 .r7 (.reg .r10))  -- 163
  | 164 => some (.add64 .r7 (.imm RM_FM_CREATE_ACCT_DATA_OFF))  -- 164
  | 165 => some (.stx .dword .r10 RM_FM_SOL_INSN_DATA_UOFF .r7)  -- 165
  | 166 => some (.add64 .r7 (.imm RM_FM_CREATE_ACCT_DATA_TO_CPI_ACCT_METAS_REL_OFF_IMM))  -- 166
  | 167 => some (.stx .dword .r10 RM_FM_SOL_INSN_ACCOUNTS_UOFF .r7)  -- 167
  | 168 => some (.mov64 .r7 (.imm RM_MISC_CREATE_ACCOUNT_N_ACCOUNTS))  -- 168
  | 169 => some (.stx .dword .r10 RM_FM_SOL_INSN_ACCOUNT_LEN_UOFF .r7)  -- 169
  | 170 => some (.mov64 .r7 (.imm SIZE_OF_CREATE_ACCOUNT_DATA))  -- 170
  | 171 => some (.stx .dword .r10 RM_FM_SOL_INSN_DATA_LEN_UOFF .r7)  -- 171
  | 172 => some (.add64 .r1 (.imm RM_FM_PDA_SEEDS_TO_SOL_INSN_REL_OFF_IMM))  -- 172
  | 173 => some (.mov64 .r2 (.reg .r10))  -- 173
  | 174 => some (.add64 .r2 (.imm RM_FM_CPI_SOL_ACCT_INFO_OFF))  -- 174
  | 175 => some (.mov64 .r3 (.imm RM_MISC_CREATE_ACCOUNT_N_ACCOUNTS))  -- 175
  | 176 => some (.add64 .r4 (.imm RM_FM_PDA_TO_SIGNERS_SEEDS_REL_OFF_IMM))  -- 176
  | 177 => some (.mov64 .r5 (.imm RM_MISC_N_PDA_SIGNERS))  -- 177
  | 178 => some (.call .sol_invoke_signed_c)  -- 178
  | 179 => some (.exit)  -- 179
  | _ => none

def progAt (n : Nat) : Option QEDGen.Solana.SBPF.Insn :=
  if n < 100 then progAt_0 n
  else
  progAt_1 n

def prog : Program := #[
  .mov32 .r0 (.imm E_INVALID_INSTRUCTION_LENGTH),
  .exit,
  .mov32 .r0 (.imm E_INVALID_NUMBER_OF_ACCOUNTS),
  .exit,
  .mov32 .r0 (.imm E_USER_HAS_DATA),
  .exit,
  .mov32 .r0 (.imm E_MARKET_ACCOUNT_IS_DUPLICATE),
  .exit,
  .mov32 .r0 (.imm E_MARKET_HAS_DATA),
  .exit,
  .mov32 .r0 (.imm E_BASE_MINT_IS_DUPLICATE),
  .exit,
  .mov32 .r0 (.imm E_QUOTE_MINT_IS_DUPLICATE),
  .exit,
  .mov32 .r0 (.imm E_INVALID_MARKET_PUBKEY),
  .exit,
  .mov32 .r0 (.imm E_SYSTEM_PROGRAM_IS_DUPLICATE),
  .exit,
  .mov32 .r0 (.imm E_INVALID_SYSTEM_PROGRAM_PUBKEY),
  .exit,
  .mov32 .r0 (.imm E_RENT_SYSVAR_IS_DUPLICATE),
  .exit,
  .mov32 .r0 (.imm E_INVALID_RENT_SYSVAR_PUBKEY),
  .exit,
  .ldx .dword .r3 .r1 IB_N_ACCTS_OFF,
  .ldx .dword .r4 .r2 INSN_LEN_OFF,
  .ldx .byte .r5 .r2 INSN_DISC_OFF,
  .jeq .r5 (.imm DISC_REGISTER_MARKET) 30,
  .mov32 .r0 (.imm E_INVALID_DISCRIMINANT),
  .exit,
  .jlt .r3 (.imm REGISTER_MARKET_ACCOUNTS_LEN) 2,
  .jne .r4 (.imm REGISTER_MARKET_DATA_LEN) 0,
  .ldx .dword .r9 .r1 IB_USER_DATA_LEN_OFF,
  .jne .r9 (.imm DATA_LEN_ZERO) 4,
  .ldx .byte .r9 .r1 IB_MARKET_DUPLICATE_OFF,
  .jne .r9 (.imm ACCT_NON_DUP_MARKER) 6,
  .ldx .dword .r9 .r1 IB_MARKET_DATA_LEN_OFF,
  .jne .r9 (.imm DATA_LEN_ZERO) 8,
  .ldx .byte .r9 .r1 RM_MISC_BASE_DUPLICATE_OFF,
  .jne .r9 (.imm ACCT_NON_DUP_MARKER) 10,
  .mov64 .r9 (.reg .r1),
  .add64 .r9 (.imm RM_MISC_BASE_ADDR_OFF),
  .stx .dword .r10 RM_FM_PDA_SEEDS_BASE_ADDR_OFF .r9,
  .mov64 .r9 (.imm SIZE_OF_ADDRESS),
  .stx .dword .r10 RM_FM_PDA_SEEDS_BASE_LEN_OFF .r9,
  .ldx .dword .r9 .r1 RM_MISC_BASE_DATA_LEN_OFF,
  .add64 .r9 (.imm DATA_LEN_MAX_PAD),
  .and64 .r9 (.imm DATA_LEN_AND_MASK),
  .add64 .r9 (.reg .r1),
  .ldx .byte .r8 .r9 RM_MISC_QUOTE_DUPLICATE_OFF,
  .jne .r8 (.imm ACCT_NON_DUP_MARKER) 12,
  .mov64 .r8 (.reg .r9),
  .add64 .r8 (.imm RM_MISC_QUOTE_ADDR_OFF),
  .stx .dword .r10 RM_FM_PDA_SEEDS_QUOTE_ADDR_OFF .r8,
  .ldx .dword .r8 .r9 RM_MISC_QUOTE_DATA_LEN_OFF,
  .add64 .r8 (.imm DATA_LEN_MAX_PAD),
  .and64 .r8 (.imm DATA_LEN_AND_MASK),
  .add64 .r9 (.imm RM_MISC_QUOTE_OFF),
  .add64 .r9 (.reg .r8),
  .add64 .r9 (.imm SIZE_OF_EMPTY_ACCOUNT),
  .mov64 .r8 (.imm SIZE_OF_ADDRESS),
  .stx .dword .r10 RM_FM_PDA_SEEDS_QUOTE_LEN_OFF .r8,
  .mov64 .r6 (.reg .r1),
  .mov64 .r1 (.reg .r10),
  .add64 .r1 (.imm RM_FM_PDA_SEEDS_OFF),
  .mov64 .r3 (.reg .r2),
  .add64 .r3 (.imm REGISTER_MARKET_DATA_LEN),
  .mov64 .r2 (.imm RM_MISC_TRY_FIND_PDA_SEEDS_LEN),
  .mov64 .r4 (.reg .r10),
  .add64 .r4 (.imm RM_FM_PDA_OFF),
  .mov64 .r5 (.reg .r10),
  .add64 .r5 (.imm RM_FM_BUMP_OFF),
  .call .sol_try_find_program_address,
  .ldx .dword .r7 .r6 IB_MARKET_PUBKEY_CHUNK_0_OFF,
  .ldx .dword .r8 .r10 RM_FM_PDA_CHUNK_0_OFF,
  .jne .r7 (.reg .r8) 14,
  .ldx .dword .r7 .r6 IB_MARKET_PUBKEY_CHUNK_1_OFF,
  .ldx .dword .r8 .r10 RM_FM_PDA_CHUNK_1_OFF,
  .jne .r7 (.reg .r8) 14,
  .ldx .dword .r7 .r6 IB_MARKET_PUBKEY_CHUNK_2_OFF,
  .ldx .dword .r8 .r10 RM_FM_PDA_CHUNK_2_OFF,
  .jne .r7 (.reg .r8) 14,
  .ldx .dword .r7 .r6 IB_MARKET_PUBKEY_CHUNK_3_OFF,
  .ldx .dword .r8 .r10 RM_FM_PDA_CHUNK_3_OFF,
  .jne .r7 (.reg .r8) 14,
  .stx .dword .r10 RM_FM_PDA_SEEDS_BUMP_ADDR_OFF .r5,
  .mov64 .r7 (.imm SIZE_OF_U8),
  .stx .dword .r10 RM_FM_PDA_SEEDS_BUMP_LEN_OFF .r7,
  .ldx .dword .r7 .r3 PUBKEY_CHUNK_0_OFF,
  .stx .dword .r10 RM_FM_CREATE_ACCT_OWNER_CHUNK_0_UOFF .r7,
  .ldx .dword .r7 .r3 PUBKEY_CHUNK_1_OFF,
  .stx .dword .r10 RM_FM_CREATE_ACCT_OWNER_CHUNK_1_UOFF .r7,
  .ldx .dword .r7 .r3 PUBKEY_CHUNK_2_OFF,
  .stx .dword .r10 RM_FM_CREATE_ACCT_OWNER_CHUNK_2_UOFF .r7,
  .ldx .dword .r7 .r3 PUBKEY_CHUNK_3_OFF,
  .stx .dword .r10 RM_FM_CREATE_ACCT_OWNER_CHUNK_3_UOFF .r7,
  .ldx .byte .r7 .r9 ACCT_DUPLICATE_OFF,
  .jne .r7 (.imm ACCT_NON_DUP_MARKER) 16,
  .ldx .dword .r7 .r9 ACCT_ADDRESS_CHUNK_0_OFF,
  .ldx .dword .r8 .r10 RM_FM_SYSTEM_PROGRAM_PUBKEY_CHUNK_0_OFF,
  .jne .r7 (.reg .r8) 18,
  .ldx .dword .r7 .r9 ACCT_ADDRESS_CHUNK_1_OFF,
  .ldx .dword .r8 .r10 RM_FM_SYSTEM_PROGRAM_PUBKEY_CHUNK_1_OFF,
  .jne .r7 (.reg .r8) 18,
  .ldx .dword .r7 .r9 ACCT_ADDRESS_CHUNK_2_OFF,
  .ldx .dword .r8 .r10 RM_FM_SYSTEM_PROGRAM_PUBKEY_CHUNK_2_OFF,
  .jne .r7 (.reg .r8) 18,
  .ldx .dword .r7 .r9 ACCT_ADDRESS_CHUNK_3_OFF,
  .ldx .dword .r8 .r10 RM_FM_SYSTEM_PROGRAM_PUBKEY_CHUNK_3_OFF,
  .jne .r7 (.reg .r8) 18,
  .mov64 .r7 (.reg .r9),
  .add64 .r7 (.imm ACCT_ADDRESS_OFF),
  .stx .dword .r10 RM_FM_SOL_INSN_PROGRAM_ID_UOFF .r7,
  .ldx .dword .r7 .r9 ACCT_DATA_LEN_OFF,
  .add64 .r7 (.imm DATA_LEN_MAX_PAD),
  .and64 .r7 (.imm DATA_LEN_AND_MASK),
  .add64 .r9 (.reg .r7),
  .add64 .r9 (.imm SIZE_OF_EMPTY_ACCOUNT),
  .ldx .byte .r7 .r9 ACCT_DUPLICATE_OFF,
  .jne .r7 (.imm ACCT_NON_DUP_MARKER) 20,
  .ldx .dword .r7 .r9 ACCT_ADDRESS_CHUNK_0_OFF,
  .lddw .r8 PUBKEY_RENT_CHUNK_0,
  .jne .r7 (.reg .r8) 22,
  .ldx .dword .r7 .r9 ACCT_ADDRESS_CHUNK_1_OFF,
  .lddw .r8 PUBKEY_RENT_CHUNK_1,
  .jne .r7 (.reg .r8) 22,
  .ldx .dword .r7 .r9 ACCT_ADDRESS_CHUNK_2_OFF,
  .lddw .r8 PUBKEY_RENT_CHUNK_2,
  .jne .r7 (.reg .r8) 22,
  .ldx .dword .r7 .r9 ACCT_ADDRESS_CHUNK_3_OFF,
  .mov32 .r8 (.imm PUBKEY_RENT_CHUNK_3_LO),
  .jne .r7 (.reg .r8) 22,
  .mov64 .r7 (.imm SIZE_OF_MARKET_HEADER),
  .stx .dword .r10 RM_FM_CREATE_ACCT_SPACE_UOFF .r7,
  .add64 .r7 (.imm ACCT_STORAGE_OVERHEAD),
  .ldx .dword .r8 .r9 ACCT_DATA_OFF,
  .mul64 .r7 (.reg .r8),
  .stx .dword .r10 RM_FM_CREATE_ACCT_LAMPORTS_UOFF .r7,
  .st .half .r10 RM_FM_CPI_USER_ACCT_INFO_IS_SIGNER_UOFF CPI_WRITABLE_SIGNER,
  .st .half .r10 RM_FM_CPI_USER_ACCT_META_IS_WRITABLE_UOFF CPI_WRITABLE_SIGNER,
  .st .half .r10 RM_FM_CPI_TARGET_ACCT_INFO_IS_SIGNER_UOFF CPI_WRITABLE_SIGNER,
  .st .half .r10 RM_FM_CPI_TARGET_ACCT_META_IS_WRITABLE_UOFF CPI_WRITABLE_SIGNER,
  .add64 .r6 (.imm IB_USER_PUBKEY_OFF),
  .stx .dword .r10 RM_FM_CPI_USER_ACCT_META_PUBKEY_UOFF .r6,
  .stx .dword .r10 RM_FM_CPI_USER_ACCT_INFO_KEY_UOFF .r6,
  .add64 .r6 (.imm IB_ADDRESS_TO_OWNER_REL_OFF_IMM),
  .stx .dword .r10 RM_FM_CPI_USER_ACCT_INFO_OWNER_UOFF .r6,
  .add64 .r6 (.imm IB_OWNER_TO_LAMPORTS_REL_OFF_IMM),
  .stx .dword .r10 RM_FM_CPI_USER_ACCT_INFO_LAMPORTS_UOFF .r6,
  .add64 .r6 (.imm IB_LAMPORTS_TO_DATA_REL_OFF_IMM),
  .stx .dword .r10 RM_FM_CPI_USER_ACCT_INFO_DATA_UOFF .r6,
  .add64 .r6 (.imm IB_USER_DATA_TO_MARKET_ADDRESS_REL_OFF_IMM),
  .stx .dword .r10 RM_FM_CPI_TARGET_ACCT_META_PUBKEY_UOFF .r6,
  .stx .dword .r10 RM_FM_CPI_TARGET_ACCT_INFO_KEY_UOFF .r6,
  .add64 .r6 (.imm IB_ADDRESS_TO_OWNER_REL_OFF_IMM),
  .stx .dword .r10 RM_FM_CPI_TARGET_ACCT_INFO_OWNER_UOFF .r6,
  .add64 .r6 (.imm IB_OWNER_TO_LAMPORTS_REL_OFF_IMM),
  .stx .dword .r10 RM_FM_CPI_TARGET_ACCT_INFO_LAMPORTS_UOFF .r6,
  .add64 .r6 (.imm IB_LAMPORTS_TO_DATA_REL_OFF_IMM),
  .stx .dword .r10 RM_FM_CPI_TARGET_ACCT_INFO_DATA_UOFF .r6,
  .stx .dword .r10 RM_FM_SIGNERS_SEEDS_ADDR_UOFF .r1,
  .mov64 .r7 (.imm RM_FM_PDA_SEEDS_N_SEEDS),
  .stx .dword .r10 RM_FM_SIGNERS_SEEDS_LEN_UOFF .r7,
  .mov64 .r7 (.reg .r10),
  .add64 .r7 (.imm RM_FM_CREATE_ACCT_DATA_OFF),
  .stx .dword .r10 RM_FM_SOL_INSN_DATA_UOFF .r7,
  .add64 .r7 (.imm RM_FM_CREATE_ACCT_DATA_TO_CPI_ACCT_METAS_REL_OFF_IMM),
  .stx .dword .r10 RM_FM_SOL_INSN_ACCOUNTS_UOFF .r7,
  .mov64 .r7 (.imm RM_MISC_CREATE_ACCOUNT_N_ACCOUNTS),
  .stx .dword .r10 RM_FM_SOL_INSN_ACCOUNT_LEN_UOFF .r7,
  .mov64 .r7 (.imm SIZE_OF_CREATE_ACCOUNT_DATA),
  .stx .dword .r10 RM_FM_SOL_INSN_DATA_LEN_UOFF .r7,
  .add64 .r1 (.imm RM_FM_PDA_SEEDS_TO_SOL_INSN_REL_OFF_IMM),
  .mov64 .r2 (.reg .r10),
  .add64 .r2 (.imm RM_FM_CPI_SOL_ACCT_INFO_OFF),
  .mov64 .r3 (.imm RM_MISC_CREATE_ACCOUNT_N_ACCOUNTS),
  .add64 .r4 (.imm RM_FM_PDA_TO_SIGNERS_SEEDS_REL_OFF_IMM),
  .mov64 .r5 (.imm RM_MISC_N_PDA_SIGNERS),
  .call .sol_invoke_signed_c,
  .exit
]

end DropsetProg
