// ---- GENERATED BY QEDGEN — DO NOT EDIT ABOVE THIS LINE ---- spec-hash:1e78ae1c31fe9933
use quasar_lang::prelude::*;
use crate::state::*;
use crate::errors::*;

#[derive(Accounts)]
pub struct AddLp {
    #[account(mut)]
    pub authority: Signer,
    #[account(mut)]
    pub vault: Account<()>,
}

impl AddLp {
    #[inline(always)]
    pub fn handler(&mut self, i: AccountIdx) -> Result<(), ProgramError> {
        // AGENT: implement business logic here
        // Spec effect: accounts[i].active set 1
        todo!()
    }
}
// ---- GENERATED BY QEDGEN — DO NOT EDIT BELOW THIS LINE ----
