// ---- GENERATED BY QEDGEN — DO NOT EDIT ABOVE THIS LINE ---- spec-hash:f2e1c45918cd201d
use quasar_lang::prelude::*;
use crate::state::*;
use crate::errors::*;

#[derive(Accounts)]
pub struct CompleteDrain {
    pub authority: Signer,
    #[account(mut)]
    pub vault: Account<()>,
}

impl CompleteDrain {
    #[inline(always)]
    pub fn handler(&mut self) -> Result<(), ProgramError> {
        // AGENT: implement business logic here
        todo!()
    }
}
// ---- GENERATED BY QEDGEN — DO NOT EDIT BELOW THIS LINE ----
