// ---- GENERATED BY QEDGEN — DO NOT EDIT ABOVE THIS LINE ---- spec-hash:d231c4bbb3e1bece
use quasar_lang::prelude::*;
use crate::state::*;
use crate::errors::*;

#[derive(Accounts)]
pub struct Deposit {
    #[account(mut)]
    pub authority: Signer,
    #[account(mut)]
    pub vault: Account<()>,
}

impl Deposit {
    #[inline(always)]
    pub fn handler(&mut self, i: AccountIdx, amount: u128) -> Result<(), ProgramError> {
        // AGENT: implement business logic here
        // Spec effect: V add amount
        // Spec effect: accounts[i].capital add amount
        todo!()
    }
}
// ---- GENERATED BY QEDGEN — DO NOT EDIT BELOW THIS LINE ----
