// ---- GENERATED BY QEDGEN — DO NOT EDIT ABOVE THIS LINE ---- spec-hash:97553809d0f51488
use quasar_lang::prelude::*;
use crate::state::*;
use crate::errors::*;

#[derive(Accounts)]
pub struct DepositFeeCredits {
    #[account(mut)]
    pub authority: Signer,
    #[account(mut)]
    pub vault: Account<()>,
}

impl DepositFeeCredits {
    #[inline(always)]
    pub fn handler(&mut self, i: AccountIdx, amount: u128) -> Result<(), ProgramError> {
        // AGENT: implement business logic here
        // Spec effect: V add amount
        // Spec effect: F add amount
        // Spec effect: accounts[i].fee_credits add amount
        todo!()
    }
}
// ---- GENERATED BY QEDGEN — DO NOT EDIT BELOW THIS LINE ----
