// ---- GENERATED BY QEDGEN — DO NOT EDIT ABOVE THIS LINE ---- spec-hash:b0db49485cbff479
use quasar_lang::prelude::*;
use crate::state::*;
use crate::errors::*;

#[derive(Accounts)]
pub struct ExecuteTrade {
    pub authority: Signer,
    #[account(mut)]
    pub vault: Account<()>,
}

impl ExecuteTrade {
    #[inline(always)]
    pub fn handler(&mut self, a: AccountIdx, b: AccountIdx, size_q: i128, exec_price: u64) -> Result<(), ProgramError> {
        // AGENT: implement business logic here
        todo!()
    }
}
// ---- GENERATED BY QEDGEN — DO NOT EDIT BELOW THIS LINE ----
