// ---- GENERATED BY QEDGEN — DO NOT EDIT ABOVE THIS LINE ---- spec-hash:b67e32b4750099bc
use quasar_lang::prelude::*;
use crate::state::*;
use crate::errors::*;

#[derive(Accounts)]
pub struct LiquidateCase1 {
    pub authority: Signer,
    #[account(mut)]
    pub vault: Account<()>,
}

impl LiquidateCase1 {
    #[inline(always)]
    pub fn handler(&mut self, i: AccountIdx) -> Result<(), ProgramError> {
        // AGENT: implement business logic here
        // Spec effect: accounts[i].active set 0
        todo!()
    }
}
// ---- GENERATED BY QEDGEN — DO NOT EDIT BELOW THIS LINE ----
