// ---- GENERATED BY QEDGEN — DO NOT EDIT ABOVE THIS LINE ---- spec-hash:990ad3b305c553f2
use quasar_lang::prelude::*;
use crate::state::*;
use crate::errors::*;

#[derive(Accounts)]
pub struct LiquidateCase0 {
    pub authority: Signer,
    #[account(mut)]
    pub vault: Account<()>,
}

impl LiquidateCase0 {
    #[inline(always)]
    pub fn handler(&mut self, i: AccountIdx) -> Result<(), ProgramError> {
        // AGENT: implement business logic here
        todo!()
    }
}
// ---- GENERATED BY QEDGEN — DO NOT EDIT BELOW THIS LINE ----
