// ---- GENERATED BY QEDGEN — DO NOT EDIT ABOVE THIS LINE ---- spec-hash:bcd0d057d05c92cf
use quasar_lang::prelude::*;
use crate::state::*;
use crate::errors::*;

#[derive(Accounts)]
pub struct Liquidate {
    pub authority: Signer,
    #[account(mut)]
    pub vault: Account<()>,
}

impl Liquidate {
    #[inline(always)]
    pub fn handler(&mut self, i: AccountIdx) -> Result<(), ProgramError> {
        // AGENT: implement business logic here
        todo!()
    }
}
// ---- GENERATED BY QEDGEN — DO NOT EDIT BELOW THIS LINE ----
