// ---- GENERATED BY QEDGEN — DO NOT EDIT ABOVE THIS LINE ---- spec-hash:053b5b07fe6d9201
use quasar_lang::prelude::*;
use crate::state::*;
use crate::events::*;
use crate::errors::*;

#[derive(Accounts)]
pub struct Approve {
    pub approver: Signer,
    #[account(mut, seeds = MultisigAccount::seeds(vault), bump)]
    pub vault: Account<Multisig>,
}

impl Approve {
    /// Approve the current proposal — each member may approve once
    #[inline(always)]
    pub fn handler(&mut self, member_index: u8, bumps: &ApproveBumps) -> Result<(), ProgramError> {
        if member_index >= self.vault.member_count {
            return Err(ProgramError::Custom(MultisigError::NotAMember as u32));
        }
        self.vault.approval_count = self.vault.approval_count
            .checked_add(1)
            .ok_or(ProgramError::Custom(MultisigError::AlreadyApproved as u32))?;
        Ok(())
    }
}
// ---- GENERATED BY QEDGEN — DO NOT EDIT BELOW THIS LINE ----
