// ---- GENERATED BY QEDGEN — DO NOT EDIT ABOVE THIS LINE ---- spec-hash:058cce9540bb65d9
use quasar_lang::prelude::*;
use crate::state::*;
use crate::events::*;
use crate::errors::*;

#[derive(Accounts)]
pub struct CancelProposal {
    pub canceller: Signer,
    #[account(mut, seeds = MultisigAccount::seeds(vault), bump)]
    pub vault: Account<Multisig>,
}

impl CancelProposal {
    /// Cancel the current proposal and return to accepting new proposals
    #[inline(always)]
    pub fn handler(&mut self, bumps: &CancelProposalBumps) -> Result<(), ProgramError> {
        // AGENT: implement business logic here
        // Spec effect: approval_count set 0
        // Spec: emit!(ProposalCancelled)
        todo!()
    }
}
// ---- GENERATED BY QEDGEN — DO NOT EDIT BELOW THIS LINE ----
