// ---- GENERATED BY QEDGEN — DO NOT EDIT ABOVE THIS LINE ---- spec-hash:ffd18a594bcdca08
use quasar_lang::prelude::*;
use crate::state::*;
use crate::events::*;
use crate::errors::*;

#[derive(Accounts)]
pub struct CreateVault {
    #[account(mut)]
    pub creator: Signer,
    #[account(init, payer = creator, seeds = MultisigAccount::seeds(vault), bump)]
    pub vault: Account<Multisig>,
    pub system_program: Program<System>,
}

impl CreateVault {
    /// Create a new multisig vault with members and approval threshold
    #[inline(always)]
    pub fn handler(&mut self, threshold: u8, member_count: u8, bumps: &CreateVaultBumps) -> Result<(), ProgramError> {
        if threshold == 0 || threshold > member_count {
            return Err(ProgramError::Custom(MultisigError::InvalidThreshold as u32));
        }
        if member_count > 32 {
            return Err(ProgramError::Custom(MultisigError::TooManyMembers as u32));
        }
        self.vault.creator = *self.creator.key;
        self.vault.threshold = threshold;
        self.vault.member_count = member_count;
        self.vault.approval_count = 0;
        self.vault.bump = bumps.vault;
        Ok(())
    }
}
// ---- GENERATED BY QEDGEN — DO NOT EDIT BELOW THIS LINE ----
