// ---- GENERATED BY QEDGEN — DO NOT EDIT ABOVE THIS LINE ---- spec-hash:c1ba2dbec69d7890
use quasar_lang::prelude::*;
use crate::state::*;
use crate::events::*;
use crate::errors::*;

#[derive(Accounts)]
pub struct Execute {
    pub executor: Signer,
    #[account(mut, seeds = MultisigAccount::seeds(vault), bump)]
    pub vault: Account<Multisig>,
}

impl Execute {
    /// Execute the proposal once the approval threshold is met
    #[inline(always)]
    #[qed(verified, hash = "fa9fb27e2a3ab8f3")]
    pub fn handler(&mut self, bumps: &ExecuteBumps) -> Result<(), ProgramError> {
        if self.vault.approval_count < self.vault.threshold {
            return Err(ProgramError::Custom(MultisigError::ThresholdNotMet as u32));
        }
        self.vault.approval_count = 0;
        Ok(())
    }
}
// ---- GENERATED BY QEDGEN — DO NOT EDIT BELOW THIS LINE ----
