// ---- GENERATED BY QEDGEN — DO NOT EDIT ABOVE THIS LINE ---- spec-hash:3d353965951bf1d0
use quasar_lang::prelude::*;
use crate::state::*;
use crate::events::*;
use crate::errors::*;

#[derive(Accounts)]
pub struct Propose {
    pub proposer: Signer,
    #[account(mut, seeds = MultisigAccount::seeds(vault), bump)]
    pub vault: Account<Multisig>,
}

impl Propose {
    /// Submit a new transaction proposal — any vault member can propose
    #[inline(always)]
    #[qed(verified, hash = "1fd7e9f374852b99")]
    pub fn handler(&mut self, bumps: &ProposeBumps) -> Result<(), ProgramError> {
        self.vault.approval_count = 0;
        Ok(())
    }
}
// ---- GENERATED BY QEDGEN — DO NOT EDIT BELOW THIS LINE ----
