use super::*;

/// Emit the brownfield-Anchor impl-targeted harness (#162): a **state-struct**
/// harness per `(handler, ensures)` instead of the greenfield `Accounts`
/// context + `accounts.handler(param)` shape. The Context shape only matches
/// qedgen-generated code; a real Anchor program shares one Accounts struct
/// across handlers, takes `Context<T>` + an `Args` struct, and exposes
/// handlers as associated fns — none of which the Context harness resolves
/// against. The state-struct harness (symbolic state → apply the real effect
/// / call the real `invariant()`/helper → assert `ensures`) is the shape that
/// actually works, validated by the two bundled brownfield harnesses.
///
/// Phase 1 (this): the struct construction and effect application are
/// `todo!()` agent-fill (they need the real struct name/fields — not in the
/// spec). Everything else — the snapshot set (incl. the read-only-field fix),
/// the requires-assume, the ensures-assert, the unwind hint — is generated.
/// Phase 2 (#162 follow-on): thread the Anchor IDL in so the construction is
/// generated too.
pub(crate) fn emit_kani_impl_anchor_brownfield(
    spec: &ParsedSpec,
    output_path: &Path,
    emit_targets: &[&ParsedHandler],
    explicit_flag: bool,
) -> Result<()> {
    let fp = crate::fingerprint::compute_fingerprint(spec);

    let mut out = String::new();

    out.push_str(&crate::codegen_shared::marker_unlabeled(
        &fp,
        "tests/kani_impl.rs",
    ));
    out.push_str("//\n");
    out.push_str("// Impl-targeted Kani harnesses — BROWNFIELD Anchor (#162). Verifies the\n");
    out.push_str("// user's REAL state logic against a symbolic state-account struct, rather\n");
    out.push_str("// than a synthetic `Accounts` context. Use this shape when the program\n");
    out.push_str("// pre-exists qedgen (shared Accounts structs, `Context<T>` + `Args`,\n");
    out.push_str("// associated-fn handlers) — the greenfield `accounts.handler(...)` shape\n");
    out.push_str("// does not resolve against it.\n");
    out.push_str("//\n");
    out.push_str("// Each proof has two AGENT-FILL sites: (1) construct the symbolic state\n");
    out.push_str("// struct, (2) apply the real effect + validity gate. The snapshot /\n");
    out.push_str("// assume / assert scaffolding around them is generated and correct.\n");
    out.push_str("//\n");
    out.push_str("// PLACEMENT: this file must live INSIDE the program crate (e.g.\n");
    out.push_str("// `src/kani_impl.rs` + `#[cfg(kani)] mod kani_impl;` in lib.rs) — a\n");
    out.push_str("// standalone harness crate hits cargo dependency-hell (spl-token-2022 vs\n");
    out.push_str("// solana-program skew). See docs/toolchain-backlog.md G3.\n");
    if !explicit_flag {
        out.push_str("//\n");
        out.push_str("// Auto-triggered (a handler declares `modifies` fields absent from its\n");
        out.push_str("// `effect` block). Pass `--kani-impl` to force emission for every\n");
        out.push_str("// handler with `ensures`.\n");
    }
    out.push_str("//\n");
    out.push_str("// To run:  cargo kani -Z stubbing --harness <name>   (requires cargo-kani)\n");
    out.push_str("// ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----\n");
    out.push_str("#![cfg(kani)]\n\n");

    out.push_str(
        "// ============================================================================\n",
    );
    out.push_str("// Impl-targeted ensures-preservation proofs (brownfield state-struct)\n");
    out.push_str(
        "// ============================================================================\n\n",
    );

    let mut emitted_count = 0;
    for handler in emit_targets {
        for (idx, ensures) in handler.ensures.iter().enumerate() {
            emit_brownfield_handler_harness(&mut out, handler, idx, ensures, spec)?;
            emitted_count += 1;
        }
    }

    out.push_str("// ---- GENERATED BY QEDGEN — DO NOT EDIT BELOW THIS LINE ----\n");

    crate::codegen_shared::write_generated_file(output_path, &out)?;

    eprintln!(
        "Generated {} brownfield impl-targeted Kani harness(es) in {}",
        emitted_count,
        output_path.display()
    );

    Ok(())
}
