// ---- GENERATED BY QEDGEN — DO NOT EDIT — regenerated from .qedspec ----
//! Per-handler guard checks derived from the `.qedspec`.
//! Called from user-owned `instructions/<name>::handler` before
//! business logic; keep guard logic here, policy-free logic there.

#![allow(unused_variables, unused_imports, dead_code, clippy::too_many_arguments)]

use quasar_lang::prelude::*;
use crate::errors::*;
use crate::instructions::*;

/// Guards for `create_vault`.  
/// Generated from the `requires` clauses of the spec handler block.
pub fn create_vault(ctx: &mut CreateVault, threshold: u8, member_count: u8) -> Result<(), ProgramError> {
    // requires: threshold > 0 ∧ threshold ≤ member_count
    if !((threshold > 0) && (threshold <= member_count)) { return Err(ProgramError::from(MultisigError::InvalidThreshold)); }
    // requires: member_count ≤ 32
    if !(member_count <= 32) { return Err(ProgramError::from(MultisigError::TooManyMembers)); }
    Ok(())
}

/// Guards for `propose`.  
/// Generated from the `requires` clauses of the spec handler block.
pub fn propose(ctx: &mut Propose) -> Result<(), ProgramError> {
    // No guards declared in spec — nothing to check.
    Ok(())
}

/// Guards for `approve`.  
/// Generated from the `requires` clauses of the spec handler block.
pub fn approve(ctx: &mut Approve, member_index: u8) -> Result<(), ProgramError> {
    // requires: member_index < s.member_count
    if !(member_index < s.member_count) { return Err(ProgramError::from(MultisigError::NotAMember)); }
    // requires: s.approval_count + s.rejection_count < s.member_count
    if !(s.approval_count + s.rejection_count < s.member_count) { return Err(ProgramError::from(MultisigError::AlreadyVoted)); }
    Ok(())
}

/// Guards for `reject`.  
/// Generated from the `requires` clauses of the spec handler block.
pub fn reject(ctx: &mut Reject, member_index: u8) -> Result<(), ProgramError> {
    // requires: member_index < s.member_count
    if !(member_index < s.member_count) { return Err(ProgramError::from(MultisigError::NotAMember)); }
    // requires: s.approval_count + s.rejection_count < s.member_count
    if !(s.approval_count + s.rejection_count < s.member_count) { return Err(ProgramError::from(MultisigError::AlreadyVoted)); }
    Ok(())
}

/// Guards for `execute`.  
/// Generated from the `requires` clauses of the spec handler block.
pub fn execute(ctx: &mut Execute) -> Result<(), ProgramError> {
    // requires: s.approval_count ≥ s.threshold
    if !(s.approval_count >= s.threshold) { return Err(ProgramError::from(MultisigError::ThresholdNotMet)); }
    Ok(())
}

/// Guards for `cancel_proposal`.  
/// Generated from the `requires` clauses of the spec handler block.
pub fn cancel_proposal(ctx: &mut CancelProposal) -> Result<(), ProgramError> {
    // requires: s.member_count - s.rejection_count < s.threshold
    if !(s.member_count - s.rejection_count < s.threshold) { return Err(ProgramError::from(MultisigError::ThresholdUnreachable)); }
    Ok(())
}

/// Guards for `remove_member`.  
/// Generated from the `requires` clauses of the spec handler block.
pub fn remove_member(ctx: &mut RemoveMember) -> Result<(), ProgramError> {
    // requires: s.member_count > s.threshold
    debug_assert!(s.member_count > s.threshold);
    // requires: s.approval_count = 0 ∧ s.rejection_count = 0
    debug_assert!((s.approval_count == 0) && (s.rejection_count == 0));
    Ok(())
}

// ---- END GENERATED ----
