// ---- GENERATED BY QEDGEN — DO NOT EDIT ---- spec-hash:0869c50b84536e0f
#![cfg_attr(any(target_os = "solana", target_arch = "bpf"), no_std)]

use quasar_lang::prelude::*;

mod instructions;
use instructions::*;
pub mod events;
pub mod errors;
pub mod state;
pub mod guards;

declare_id!("11111111111111111111111111111111");

#[program]
mod multisig {
    use super::*;

    #[instruction(discriminator = 0)]
    pub fn create_vault(ctx: Ctx<CreateVault>, threshold: u8, member_count: u8) -> Result<(), ProgramError> {
        ctx.accounts.handler(threshold, member_count, &ctx.bumps)
    }

    #[instruction(discriminator = 1)]
    pub fn propose(ctx: Ctx<Propose>) -> Result<(), ProgramError> {
        ctx.accounts.handler(&ctx.bumps)
    }

    #[instruction(discriminator = 2)]
    pub fn approve(ctx: Ctx<Approve>, member_index: u8) -> Result<(), ProgramError> {
        ctx.accounts.handler(member_index, &ctx.bumps)
    }

    #[instruction(discriminator = 3)]
    pub fn reject(ctx: Ctx<Reject>, member_index: u8) -> Result<(), ProgramError> {
        ctx.accounts.handler(member_index, &ctx.bumps)
    }

    #[instruction(discriminator = 4)]
    pub fn execute(ctx: Ctx<Execute>) -> Result<(), ProgramError> {
        ctx.accounts.handler(&ctx.bumps)
    }

    #[instruction(discriminator = 5)]
    pub fn cancel_proposal(ctx: Ctx<CancelProposal>) -> Result<(), ProgramError> {
        ctx.accounts.handler(&ctx.bumps)
    }

    #[instruction(discriminator = 6)]
    pub fn remove_member(ctx: Ctx<RemoveMember>) -> Result<(), ProgramError> {
        ctx.accounts.handler(&ctx.bumps)
    }

}
// ---- END GENERATED ----
