// ---- GENERATED BY QEDGEN ---- spec-hash:6905d903db8f6b15
//
// Self-contained Kani proof harnesses for the spec.
//
// These proofs verify the spec's transition design using Kani bounded model
// checking. They operate on a pure model of the state machine (derived from
// the qedspec), independent of framework (Quasar/Anchor) types.
//
//   Lean proves:  transition functions preserve invariants (∀ states)
//   Kani checks:  same properties via bounded model checking + overflow detection
//   Together:     high assurance that the spec design is correct
//
// To run:  cargo kani --harness <name>   (requires cargo-kani)
// ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----
#![cfg(kani)]

// ============================================================================
// State model (derived from qedspec — no framework dependencies)
// ============================================================================

#[derive(Clone, Copy)]
struct State {
    initializer_amount: u64,
    taker_amount: u64,
}

// ============================================================================
// Transition functions (from qedspec operations — effects + guards)
//
// Each returns true if the guard passes and the transition fires,
// false if the guard rejects the operation.
// ============================================================================

fn initialize(s: &mut State, deposit_amount: u64, receive_amount: u64) -> bool {
    if !((deposit_amount > 0) && (receive_amount > 0)) {
        return false;
    }
    s.initializer_amount = deposit_amount;
    s.taker_amount = receive_amount;
    true
}

fn exchange(s: &mut State) -> bool {
    true
}

fn cancel(s: &mut State) -> bool {
    true
}

// ============================================================================
// Guard enforcement — transitions reject invalid inputs
// ============================================================================

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_initialize_rejects_invalid() {
    let mut s = State {
        initializer_amount: kani::any(),
        taker_amount: kani::any(),
    };
    let deposit_amount: u64 = kani::any();
    let receive_amount: u64 = kani::any();
    kani::assume(!((deposit_amount > 0) && (receive_amount > 0)));
    assert!(!initialize(&mut s, deposit_amount, receive_amount),
        "initialize must reject when guard is violated");
}

// ============================================================================
// Effect conformance — verify transition effects match spec
//
// Each proof applies a transition to symbolic state and checks that every
// field changed/unchanged matches the spec's effect: declarations.
// ============================================================================

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_initialize_effect_initializer_amount() {
    let mut s = State {
        initializer_amount: 0,
        taker_amount: 0,
    };
    let deposit_amount: u64 = kani::any();
    let receive_amount: u64 = kani::any();
    let pre_taker_amount = s.taker_amount;
    if initialize(&mut s, deposit_amount, receive_amount) {
        assert!(s.initializer_amount == deposit_amount, "initializer_amount must equal deposit_amount");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_initialize_effect_taker_amount() {
    let mut s = State {
        initializer_amount: 0,
        taker_amount: 0,
    };
    let deposit_amount: u64 = kani::any();
    let receive_amount: u64 = kani::any();
    let pre_initializer_amount = s.initializer_amount;
    if initialize(&mut s, deposit_amount, receive_amount) {
        assert!(s.taker_amount == receive_amount, "taker_amount must equal receive_amount");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_initialize_effect_initializer_token_account() {
    let mut s = State {
        initializer_amount: 0,
        taker_amount: 0,
    };
    let deposit_amount: u64 = kani::any();
    let receive_amount: u64 = kani::any();
    let pre_initializer_amount = s.initializer_amount;
    let pre_taker_amount = s.taker_amount;
    if initialize(&mut s, deposit_amount, receive_amount) {
        assert!(s.initializer_token_account == initializer_ta.pubkey, "initializer_token_account must equal initializer_ta.pubkey");
    }
}

// ============================================================================
// Cover properties — reachability via kani::cover!
// ============================================================================

#[kani::proof]
#[kani::unwind(3)]
#[kani::solver(cadical)]
fn cover_happy_path() {
    let mut s = State {
        initializer_amount: kani::any(),
        taker_amount: kani::any(),
    };
    let deposit_amount_0: u64 = kani::any();
    let receive_amount_0: u64 = kani::any();
    if initialize(&mut s, deposit_amount_0, receive_amount_0) {
        kani::cover!(exchange(&mut s), "happy_path trace is reachable");
    }
}

#[kani::proof]
#[kani::unwind(3)]
#[kani::solver(cadical)]
fn cover_cancel_path() {
    let mut s = State {
        initializer_amount: kani::any(),
        taker_amount: kani::any(),
    };
    let deposit_amount_0: u64 = kani::any();
    let receive_amount_0: u64 = kani::any();
    if initialize(&mut s, deposit_amount_0, receive_amount_0) {
        kani::cover!(cancel(&mut s), "cancel_path trace is reachable");
    }
}

// ============================================================================
// Liveness properties — bounded reachability via non-deterministic ops
// ============================================================================

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_liveness_escrow_settles() {
    let mut s = State {
        initializer_amount: kani::any(),
        taker_amount: kani::any(),
    };
    for _ in 0..1 {
        let op: u8 = kani::any();
        match op {
            0 => {
                exchange(&mut s);
            }
            1 => {
                cancel(&mut s);
            }
            _ => {}
        }
    }
    // Target: from Open to Closed within 1 steps
}

// ---- GENERATED BY QEDGEN — DO NOT EDIT BELOW THIS LINE ----
