// ---- GENERATED BY QEDGEN ---- spec-hash:
//
// Proptest harnesses — property-based testing for the spec's state machine.
// Tier 1 of the verification waterfall: finds counterexamples in milliseconds.
//
//   Proptest: random testing, fast counterexamples (~100ms)
//   Kani:     bounded model checking, exhaustive within bounds (~5-30s)
//   Lean:     mathematical proof, universal guarantees (minutes-hours)
//
// To run:  cargo test --test proptest
// Deep:    PROPTEST_CASES=10000 cargo test --test proptest
// ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----

use proptest::prelude::*;

#[derive(Debug, Clone, Copy)]
struct State {
    initializer_amount: u64,
    taker_amount: u64,
}

/// Proptest strategy for generating arbitrary State values.
fn arb_state() -> impl Strategy<Value = State> {
    (
        0u64..=u64::MAX,
        0u64..=u64::MAX,
    ).prop_map(|(initializer_amount, taker_amount)| State {
        initializer_amount,
        taker_amount,
    })
}

/// Boundary-biased strategy for guard rejection tests.
fn arb_boundary_state() -> impl Strategy<Value = State> {
    (
        prop_oneof![0u64..=3u64, (u64::MAX - 3)..=u64::MAX],
        prop_oneof![0u64..=3u64, (u64::MAX - 3)..=u64::MAX],
    ).prop_map(|(initializer_amount, taker_amount)| State {
        initializer_amount,
        taker_amount,
    })
}

/// Initializer deposits tokens and opens the escrow
fn initialize(s: &mut State, deposit_amount: u64, receive_amount: u64) -> bool {
    if !(deposit_amount > 0 && receive_amount > 0) {
        return false;
    }
    s.initializer_amount = deposit_amount;
    s.taker_amount = receive_amount;
    true
}

/// Taker completes the trade by sending their tokens
fn exchange(s: &mut State) -> bool {
    true
}

/// Initializer reclaims their deposit and closes the escrow
fn cancel(s: &mut State) -> bool {
    true
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn initialize_rejects_invalid(s in arb_boundary_state(), deposit_amount in prop_oneof![0u64..=3u64, (u64::MAX - 3)..=u64::MAX], receive_amount in prop_oneof![0u64..=3u64, (u64::MAX - 3)..=u64::MAX]) {
        let mut s = s;
        prop_assume!(!(deposit_amount > 0 && receive_amount > 0));
        prop_assert!(!initialize(&mut s, deposit_amount, receive_amount),
            "initialize must reject when guard is violated");
    }
}

