// ---- GENERATED BY QEDGEN ----
//
// Proptest harnesses — property-based testing for the spec's state machine.
// Tier 1 of the verification waterfall: finds counterexamples in milliseconds.
//
//   Proptest: random testing, fast counterexamples (~100ms)
//   Kani:     bounded model checking, exhaustive within bounds (~5-30s)
//   Lean:     mathematical proof, universal guarantees (minutes-hours)
//
// To run:  cargo test --test proptest
// Deep:    PROPTEST_CASES=10000 cargo test --test proptest
// ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----

use proptest::prelude::*;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Status {
    Uninitialized,
    Open,
    Closed,
}

#[derive(Debug, Clone, Copy)]
struct State {
    initializer_amount: u64,
    taker_amount: u64,
    status: Status,
}

/// Proptest strategy for generating arbitrary State values.
fn arb_state() -> impl Strategy<Value = State> {
    (
        0u64..=u64::MAX,
        0u64..=u64::MAX,
        prop_oneof![Just(Status::Uninitialized), Just(Status::Open), Just(Status::Closed)],
    ).prop_map(|(initializer_amount, taker_amount, status)| State {
        initializer_amount,
        taker_amount,
        status,
    })
}

/// Boundary-biased strategy for guard rejection tests.
fn arb_boundary_state() -> impl Strategy<Value = State> {
    (
        prop_oneof![0u64..=3u64, (u64::MAX - 3)..=u64::MAX],
        prop_oneof![0u64..=3u64, (u64::MAX - 3)..=u64::MAX],
        prop_oneof![Just(Status::Uninitialized), Just(Status::Open), Just(Status::Closed)],
    ).prop_map(|(initializer_amount, taker_amount, status)| State {
        initializer_amount,
        taker_amount,
        status,
    })
}

fn initialize(s: &mut State, deposit_amount: u64, receive_amount: u64) -> bool {
    if !((deposit_amount > 0) && (receive_amount > 0)) {
        return false;
    }
    if s.status != Status::Uninitialized {
        return false;
    }
    s.initializer_amount = deposit_amount;
    s.taker_amount = receive_amount;
    s.status = Status::Open;
    true
}

fn exchange(s: &mut State) -> bool {
    if !(initializer_ta.pubkey == s.initializer_token_account) {
        return false;
    }
    if s.status != Status::Open {
        return false;
    }
    s.status = Status::Closed;
    true
}

fn cancel(s: &mut State) -> bool {
    if !(initializer_ta.pubkey == s.initializer_token_account) {
        return false;
    }
    if s.status != Status::Open {
        return false;
    }
    s.status = Status::Closed;
    true
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn initialize_rejects_invalid(s in arb_boundary_state(), deposit_amount in prop_oneof![0u64..=3u64, (u64::MAX - 3)..=u64::MAX], receive_amount in prop_oneof![0u64..=3u64, (u64::MAX - 3)..=u64::MAX]) {
        let mut s = s;
        prop_assume!(!((deposit_amount > 0) && (receive_amount > 0)));
        prop_assert!(!initialize(&mut s, deposit_amount, receive_amount),
            "initialize must reject when guard is violated");
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn exchange_rejects_invalid(s in arb_boundary_state()) {
        let mut s = s;
        prop_assume!(!(initializer_ta.pubkey == s.initializer_token_account));
        prop_assert!(!exchange(&mut s),
            "exchange must reject when guard is violated");
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn cancel_rejects_invalid(s in arb_boundary_state()) {
        let mut s = s;
        prop_assume!(!(initializer_ta.pubkey == s.initializer_token_account));
        prop_assert!(!cancel(&mut s),
            "cancel must reject when guard is violated");
    }
}

