// ---- GENERATED BY QEDGEN — DO NOT EDIT ---- spec-hash:fbbb6a767bb7a16c
use quasar_lang::prelude::*;

#[error_code]
pub enum MultisigError {
    InvalidThreshold = 0,
    TooManyMembers = 1,
    AlreadyApproved = 2,
    ThresholdNotMet = 3,
    NotAMember = 4,
}
// ---- END GENERATED ----
