-- Auto-generated by qedgen asm2lean from guard.s
-- DO NOT EDIT — regenerate with: qedgen asm2lean --input guard.s
-- source-hash: sha256:232675c05997b51772023981e022f0477a86f002f8273b9db11516a9f7ebc454
-- sbpf-version: v3

import SVM.SBPF

namespace GuardProg

open SVM.SBPF

/-! ## .equ constants -/

abbrev TAG_OFF : Int := 96
abbrev LIMIT_OFF : Int := 104
abbrev TAG : Nat := 1
abbrev E_TAG : Nat := 1
abbrev E_ORDER : Nat := 2

/-! ## effectiveAddr lemmas -/

section EffectiveAddr

open SVM.SBPF.Memory

@[simp] theorem ea_LIMIT_OFF (b : Nat) : effectiveAddr b LIMIT_OFF = b + 104 := by
  unfold effectiveAddr LIMIT_OFF; omega

@[simp] theorem ea_TAG_OFF (b : Nat) : effectiveAddr b TAG_OFF = b + 96 := by
  unfold effectiveAddr TAG_OFF; omega

end EffectiveAddr

/-! ## Program -/

@[simp] def prog : Program := #[
  .ldx .dword .r2 .r1 TAG_OFF,                     -- 0: entrypoint
  .ldx .dword .r3 .r1 LIMIT_OFF,                   -- 1
  .jmp32 .ne .r2 (.imm TAG) 6,                     -- 2
  .jmp32 .lt .r3 (.reg .r2) 8,                     -- 3
  .mov64 .r0 (.imm 0),                             -- 4
  .exit,                                           -- 5
  .mov32 .r0 (.imm E_TAG),                         -- 6: e_tag
  .exit,                                           -- 7
  .mov32 .r0 (.imm E_ORDER),                       -- 8: e_order
  .exit                                             -- 9
]

@[simp] def progAt : Nat → Option SVM.SBPF.Insn
  | 0 => some (.ldx .dword .r2 .r1 TAG_OFF)
  | 1 => some (.ldx .dword .r3 .r1 LIMIT_OFF)
  | 2 => some (.jmp32 .ne .r2 (.imm TAG) 6)
  | 3 => some (.jmp32 .lt .r3 (.reg .r2) 8)
  | 4 => some (.mov64 .r0 (.imm 0))
  | 5 => some (.exit)
  | 6 => some (.mov32 .r0 (.imm E_TAG))
  | 7 => some (.exit)
  | 8 => some (.mov32 .r0 (.imm E_ORDER))
  | 9 => some (.exit)
  | _ => none

/-! ## Instruction fetch cache -/

@[simp] theorem insn_0 : progAt 0 = some (.ldx .dword .r2 .r1 TAG_OFF) := by rfl
@[simp] theorem insn_1 : progAt 1 = some (.ldx .dword .r3 .r1 LIMIT_OFF) := by rfl
@[simp] theorem insn_2 : progAt 2 = some (.jmp32 .ne .r2 (.imm TAG) 6) := by rfl
@[simp] theorem insn_3 : progAt 3 = some (.jmp32 .lt .r3 (.reg .r2) 8) := by rfl
@[simp] theorem insn_4 : progAt 4 = some (.mov64 .r0 (.imm 0)) := by rfl
@[simp] theorem insn_5 : progAt 5 = some (.exit) := by rfl
@[simp] theorem insn_6 : progAt 6 = some (.mov32 .r0 (.imm E_TAG)) := by rfl
@[simp] theorem insn_7 : progAt 7 = some (.exit) := by rfl
@[simp] theorem insn_8 : progAt 8 = some (.mov32 .r0 (.imm E_ORDER)) := by rfl
@[simp] theorem insn_9 : progAt 9 = some (.exit) := by rfl

end GuardProg
