-- Generated by qedgen lean-gen from tree.qedspec
-- Source of truth: the .qedspec file. Regenerate with:
--   qedgen lean-gen --spec <spec>.qedspec --output <this-file>

import QEDGen
import TreeProg

open QEDGen.Solana.SBPF
open QEDGen.Solana.SBPF.Memory

namespace Dispatch

-- Global constants (from prog module, not re-declared):
--   IB_N_ACCOUNTS_INIT = 5
--   INSN_DISCRIMINATOR_INITIALIZE = 0
--   INSN_DISCRIMINATOR_INSERT = 1
--   INSN_DISCRIMINATOR_REMOVE = 2
--   SIZE_OF_INITIALIZE_INSTRUCTION = 1

-- Error constants
abbrev E_NACCOUNTS : Nat := 1
abbrev E_USER_DATA_LEN : Nat := 2
abbrev E_TREE_DATA_LEN : Nat := 3
abbrev E_SYSTEM_PROGRAM_DATA_LEN : Nat := 4
abbrev E_TREE_DUPLICATE : Nat := 5
abbrev E_SYSTEM_PROGRAM_DUPLICATE : Nat := 6
abbrev E_RENT_DUPLICATE : Nat := 7
abbrev E_RENT_ADDRESS : Nat := 8
abbrev E_INSTRUCTION_DATA : Nat := 9
abbrev E_PDA_MISMATCH : Nat := 10
abbrev E_INSTRUCTION_DISCRIMINATOR : Nat := 11
abbrev E_INSTRUCTION_DATA_LEN : Nat := 12
abbrev E_NACCOUNTS_INSERT_ALLOCATION : Nat := 13
abbrev E_KEY_EXISTS : Nat := 14
abbrev E_KEY_DOES_NOT_EXIST : Nat := 15

-- Offset constants
abbrev N_ACCOUNTS : Int := 0
abbrev INSN_LEN : Int := -8
abbrev DISCRIMINANT : Int := 0

-- Effective address lemmas
@[simp] theorem ea_N_ACCOUNTS (b : Nat) : effectiveAddr b N_ACCOUNTS = b := by
  unfold effectiveAddr N_ACCOUNTS; omega

@[simp] theorem ea_INSN_LEN (b : Nat) : effectiveAddr b INSN_LEN = b - 8 := by
  unfold effectiveAddr INSN_LEN; omega

@[simp] theorem ea_DISCRIMINANT (b : Nat) : effectiveAddr b DISCRIMINANT = b := by
  unfold effectiveAddr DISCRIMINANT; omega

-- Guard theorem stubs
-- Hypotheses derived from checks + layout. Fill proofs with wp_exec.

/-- Discriminator must be 0, 1, or 2 -/
theorem rejects_invalid_discriminator
    (inputAddr insnAddr : Nat) (mem : Mem)
    -- TODO: add guard-specific hypotheses
    :
    (executeFn TreeProg.progAt (initState2 inputAddr insnAddr mem 0) 11).exitCode
      = some E_INSTRUCTION_DISCRIMINATOR := sorry

/-- Initialize: instruction data must be 1 byte -/
theorem init_rejects_wrong_data_len
    (inputAddr insnAddr : Nat) (mem : Mem)
    -- TODO: add guard-specific hypotheses
    :
    (executeFn TreeProg.progAt (initState2 inputAddr insnAddr mem 0) 12).exitCode
      = some E_INSTRUCTION_DATA_LEN := sorry

/-- Initialize: must have 5 accounts -/
theorem init_rejects_wrong_account_count
    (inputAddr insnAddr : Nat) (mem : Mem)
    -- TODO: add guard-specific hypotheses
    :
    (executeFn TreeProg.progAt (initState2 inputAddr insnAddr mem 0) 13).exitCode
      = some E_NACCOUNTS := sorry

-- Completeness structure: fill all fields to prove every guard is covered
structure Spec (progAt : Nat → Option Insn) where
  rejects_invalid_discriminator :
    ∀ (inputAddr insnAddr : Nat) (mem : Mem),
    (executeFn progAt (initState2 inputAddr insnAddr mem 0) 11).exitCode = some E_INSTRUCTION_DISCRIMINATOR
  init_rejects_wrong_data_len :
    ∀ (inputAddr insnAddr : Nat) (mem : Mem),
    (executeFn progAt (initState2 inputAddr insnAddr mem 0) 12).exitCode = some E_INSTRUCTION_DATA_LEN
  init_rejects_wrong_account_count :
    ∀ (inputAddr insnAddr : Nat) (mem : Mem),
    (executeFn progAt (initState2 inputAddr insnAddr mem 0) 13).exitCode = some E_NACCOUNTS

end Dispatch
