//! Top-level orchestration: the public `generate` entry point, the pure
//! `render`/`render_inner` pipeline, and the single- vs multi-account section
//! dispatch (including the per-account scoped `ParsedSpec` view).

use super::*;

/// Generate the Kani harness file at `output_path` from a pre-lowered
/// `Mir` + the originating `ParsedSpec`.
pub fn generate(mir: &Mir, parsed: &ParsedSpec, output_path: &Path) -> Result<()> {
    if mir.handlers.is_empty() {
        anyhow::bail!("No operations found in the spec — is this a valid qedspec file?");
    }

    crate::rust_codegen_util::check_effect_targets(parsed)?;

    let content = render_with_progress(mir, parsed);
    write_generated_file(output_path, &content)?;

    eprintln!("Generated Kani harnesses in {}", output_path.display());
    Ok(())
}

/// Pure render: deterministic structural prefix, then the per-account
/// body, branching on single- vs multi-account.
#[cfg_attr(not(test), allow(dead_code))]
pub fn render(mir: &Mir, parsed: &ParsedSpec) -> String {
    render_inner(mir, parsed, false, false)
}

pub(crate) fn render_with_progress(mir: &Mir, parsed: &ParsedSpec) -> String {
    render_inner(mir, parsed, true, skip_guard_proofs_from_env())
}

pub(crate) fn render_inner(
    mir: &Mir,
    parsed: &ParsedSpec,
    progress: bool,
    skip_guard_proofs: bool,
) -> String {
    let mut out = String::new();
    if progress {
        eprintln!(
            "Rendering Kani model harnesses for {} handler(s), {} propertie(s), {} invariant(s)",
            parsed.handlers.len(),
            parsed.properties.len(),
            parsed.invariants.len()
        );
    }
    emit_header(&mut out, parsed);
    emit_math_helpers(&mut out, parsed);
    if crate::rust_codegen_util::spec_uses_pubkey(parsed) {
        crate::rust_codegen_util::emit_kani_pubkey_helpers(&mut out);
    }
    emit_state_model_header(&mut out);
    emit_constants(&mut out, mir);

    if parsed.account_types.len() > 1 {
        // Multi-account: per-account `mod <lowercase>` blocks; file-level
        // features (covers / liveness / env) emit in single mode only.
        if let Err(e) =
            emit_multi_account_sections(&mut out, mir, parsed, progress, skip_guard_proofs)
        {
            out.push_str(&format!("// MIR-ERROR: multi-account emit failed: {}\n", e));
        }
    } else {
        if let Err(e) =
            emit_single_account_sections(&mut out, mir, parsed, progress, skip_guard_proofs)
        {
            out.push_str(&format!(
                "// MIR-ERROR: single-account emit failed: {}\n",
                e
            ));
        }
    }

    out.push_str("// ---- GENERATED BY QEDGEN — DO NOT EDIT BELOW THIS LINE ----\n");
    out
}

pub(crate) fn skip_guard_proofs_from_env() -> bool {
    matches!(
        std::env::var("QEDGEN_KANI_SKIP_GUARD_PROOFS")
            .ok()
            .as_deref(),
        Some("1" | "true" | "TRUE" | "yes" | "YES")
    )
}

/// Single-account dispatch — every section emitter in snapshot-pinned order.
pub(crate) fn emit_single_account_sections(
    out: &mut String,
    mir: &Mir,
    parsed: &ParsedSpec,
    progress: bool,
    skip_guard_proofs: bool,
) -> Result<()> {
    if progress {
        eprintln!("Rendering Kani section: state model");
    }
    emit_account_section_structural(out, mir, parsed)?;
    if skip_guard_proofs {
        if progress {
            eprintln!(
                "Skipping Kani section: guard rejection proofs (QEDGEN_KANI_SKIP_GUARD_PROOFS=1)"
            );
        }
    } else {
        if progress {
            eprintln!("Rendering Kani section: guard rejection proofs");
        }
        emit_guard_enforcement_harnesses(out, parsed, progress)?;
    }
    if progress {
        eprintln!("Rendering Kani section: abort-condition proofs");
    }
    emit_abort_condition_harnesses(out, parsed)?;
    if progress {
        eprintln!("Rendering Kani section: property preservation proofs");
    }
    emit_property_preservation_harnesses(out, parsed)?;
    // Section order (property → ensures → invariant → effect → overflow)
    // is load-bearing for snapshot byte-equivalence.
    if progress {
        eprintln!("Rendering Kani section: ensures preservation proofs");
    }
    emit_ensures_preservation_harnesses(out, parsed)?;
    if progress {
        eprintln!("Rendering Kani section: invariant preservation proofs");
    }
    emit_invariant_preservation_harnesses(out, parsed)?;
    if progress {
        eprintln!("Rendering Kani section: effect conformance proofs");
    }
    emit_effect_conformance_harnesses(out, mir, parsed)?;
    if progress {
        eprintln!("Rendering Kani section: overflow proofs");
    }
    emit_overflow_detection_harnesses(out, mir, parsed)?;
    // File-level features (covers / liveness / environment) —
    // single-mode only; multi-account specs skip these entirely.
    if progress {
        eprintln!("Rendering Kani section: cover/liveness/environment proofs");
    }
    emit_file_level_features(out, parsed)?;
    Ok(())
}

/// Multi-account dispatch — one `mod <lowercase> { use super::*; ... }`
/// per account_type, each driven by a per-account scoped `ParsedSpec`
/// (see `scope_parsed_to_account`). Sections follow the same order as
/// single-mode; file-level features (covers / liveness / environment)
/// are not emitted in multi-mode at all.
pub(crate) fn emit_multi_account_sections(
    out: &mut String,
    mir: &Mir,
    parsed: &ParsedSpec,
    progress: bool,
    skip_guard_proofs: bool,
) -> Result<()> {
    use crate::rust_codegen_util as util;

    for acct in &parsed.account_types {
        let acct_fields_view = util::field_refs(&acct.fields);
        if acct_fields_view.is_empty() {
            continue;
        }

        let scoped = scope_parsed_to_account(parsed, acct);

        if scoped.handlers.is_empty() {
            continue;
        }

        let mod_name = acct.name.to_lowercase();
        if progress {
            eprintln!("Rendering Kani account module: {mod_name}");
        }
        out.push_str(&format!("mod {} {{\n", mod_name));
        out.push_str("    use super::*;\n\n");

        emit_account_section_structural(out, mir, &scoped)?;
        if skip_guard_proofs {
            if progress {
                eprintln!(
                    "Skipping Kani section: guard rejection proofs (QEDGEN_KANI_SKIP_GUARD_PROOFS=1)"
                );
            }
        } else {
            emit_guard_enforcement_harnesses(out, &scoped, progress)?;
        }
        emit_abort_condition_harnesses(out, &scoped)?;
        emit_property_preservation_harnesses(out, &scoped)?;
        emit_ensures_preservation_harnesses(out, &scoped)?;
        emit_invariant_preservation_harnesses(out, &scoped)?;
        emit_effect_conformance_harnesses(out, mir, &scoped)?;
        emit_overflow_detection_harnesses(out, mir, &scoped)?;

        out.push_str(&format!("}} // mod {}\n\n", mod_name));
    }

    Ok(())
}

/// Build a per-account scoped `ParsedSpec` view the section emitters can
/// consume unchanged:
///
///   * `account_types` → `vec![acct]` so the single-account view resolve
///     picks up this account's fields/lifecycle.
///   * `handlers` → strict `on_account == Some(acct.name)` (no primary
///     fallback).
///   * `properties` → substring match against any field of this account.
///   * `invariants` → those mentioned by at least one filtered handler.
///   * Spec-wide collections (records, sum_types, constants, interfaces,
///     ref_impls, lifecycle_states, state_fields, error_codes) cloned
///     verbatim — file-scoped, shared across `mod` blocks via `use super::*;`.
pub(crate) fn scope_parsed_to_account(
    parsed: &ParsedSpec,
    acct: &crate::check::ParsedAccountType,
) -> ParsedSpec {
    let mut scoped = parsed.clone();

    scoped.account_types = vec![acct.clone()];

    scoped.handlers = parsed
        .handlers
        .iter()
        .filter(|h| h.on_account.as_deref() == Some(acct.name.as_str()))
        .cloned()
        .collect();

    let acct_field_names: Vec<&str> = acct.fields.iter().map(|(n, _)| n.as_str()).collect();
    scoped.properties = parsed
        .properties
        .iter()
        .filter(|p| {
            if let Some(ref expr) = p.expression {
                acct_field_names.iter().any(|f| expr.contains(f))
            } else {
                false
            }
        })
        .cloned()
        .collect();

    let claimed_inv_names: std::collections::HashSet<&str> = scoped
        .handlers
        .iter()
        .flat_map(|h| h.invariants.iter().chain(h.establishes.iter()))
        .map(|s| s.as_str())
        .collect();
    scoped.invariants = parsed
        .invariants
        .iter()
        .filter(|i| claimed_inv_names.contains(i.name.as_str()))
        .cloned()
        .collect();

    scoped
}
