import Spec
import Mathlib.Tactic
open Percolator
open QEDGen.Solana

/-!
# Percolator Risk Engine — Proofs

All properties generated by the `qedspec` DSL, proven against
parameterized transitions with real state mutations.

With DSL type mapping (U64→Nat), `omega` works directly on
conservation proofs — no more `calc` + `ring` workarounds.
-/

-- ============================================================================
-- Conservation: V ≥ C_tot + I
-- ============================================================================

/-- Deposit: V += a, C_tot += a ⟹ V+a ≥ (C_tot+a) + I -/
theorem deposit_preserves_conservation (s s' : State) (p : Pubkey) (amount : Nat)
    (h_inv : conservation s) (h : depositTransition s p amount = some s') :
    conservation s' := by
  unfold depositTransition at h; split_ifs at h; cases h
  unfold conservation at h_inv ⊢; simp; omega

/-- Top-up insurance: V += a, I += a ⟹ V+a ≥ C_tot + (I+a) -/
theorem topup_preserves_conservation (s s' : State) (p : Pubkey) (amount : Nat)
    (h_inv : conservation s) (h : top_up_insuranceTransition s p amount = some s') :
    conservation s' := by
  unfold top_up_insuranceTransition at h; split_ifs at h; cases h
  unfold conservation at h_inv ⊢; simp; omega

/-- Withdraw: V -= a, C_tot -= a ⟹ V-a ≥ (C_tot-a) + I -/
theorem withdraw_preserves_conservation (s s' : State) (p : Pubkey) (amount : Nat)
    (h_inv : conservation s) (h : withdrawTransition s p amount = some s') :
    conservation s' := by
  unfold withdrawTransition at h; split_ifs at h with h_cond; cases h
  unfold conservation at h_inv ⊢; simp; omega

/-- Lifecycle transitions preserve conservation (no V/C_tot/I mutation) -/
theorem trigger_adl_preserves_conservation (s s' : State) (p : Pubkey)
    (h_inv : conservation s) (h : trigger_adlTransition s p = some s') :
    conservation s' := by
  unfold trigger_adlTransition at h; split_ifs at h; cases h; exact h_inv

theorem complete_drain_preserves_conservation (s s' : State) (p : Pubkey)
    (h_inv : conservation s) (h : complete_drainTransition s p = some s') :
    conservation s' := by
  unfold complete_drainTransition at h; split_ifs at h; cases h; exact h_inv

theorem reset_preserves_conservation (s s' : State) (p : Pubkey)
    (h_inv : conservation s) (h : resetTransition s p = some s') :
    conservation s' := by
  unfold resetTransition at h; split_ifs at h; cases h; exact h_inv

-- ============================================================================
-- Vault bounded: V ≤ 10_000_000_000_000_000
-- ============================================================================

/-- Deposit guard ensures V + amount ≤ MAX -/
theorem deposit_preserves_vault_bounded (s s' : State) (p : Pubkey) (amount : Nat)
    (_ : vault_bounded s) (h : depositTransition s p amount = some s') :
    vault_bounded s' := by
  unfold depositTransition at h; split_ifs at h with h_cond; cases h
  unfold vault_bounded; simp; exact h_cond.2.2

/-- Top-up guard ensures V + amount ≤ MAX -/
theorem topup_preserves_vault_bounded (s s' : State) (p : Pubkey) (amount : Nat)
    (_ : vault_bounded s) (h : top_up_insuranceTransition s p amount = some s') :
    vault_bounded s' := by
  unfold top_up_insuranceTransition at h; split_ifs at h with h_cond; cases h
  unfold vault_bounded; simp; exact h_cond.2.2

-- ============================================================================
-- Access control: only authority can call operations
-- ============================================================================

theorem deposit_access_control (s : State) (p : Pubkey) (amount : Nat)
    (h : depositTransition s p amount ≠ none) : p = s.authority := by
  unfold depositTransition at h; split_ifs at h with hc; exact hc.1; contradiction

theorem withdraw_access_control (s : State) (p : Pubkey) (amount : Nat)
    (h : withdrawTransition s p amount ≠ none) : p = s.authority := by
  unfold withdrawTransition at h; split_ifs at h with hc; exact hc.1; contradiction

theorem topup_access_control (s : State) (p : Pubkey) (amount : Nat)
    (h : top_up_insuranceTransition s p amount ≠ none) : p = s.authority := by
  unfold top_up_insuranceTransition at h; split_ifs at h with hc; exact hc.1; contradiction

-- ============================================================================
-- ADL lifecycle state machine: Active → Draining → Resetting → Active
-- ============================================================================

theorem trigger_adl_state_machine (s s' : State) (p : Pubkey)
    (h : trigger_adlTransition s p = some s') :
    s.status = .Active ∧ s'.status = .Draining := by
  unfold trigger_adlTransition at h; split_ifs at h with hc
  cases h; exact ⟨hc.2, rfl⟩

theorem complete_drain_state_machine (s s' : State) (p : Pubkey)
    (h : complete_drainTransition s p = some s') :
    s.status = .Draining ∧ s'.status = .Resetting := by
  unfold complete_drainTransition at h; split_ifs at h with hc
  cases h; exact ⟨hc.2, rfl⟩

theorem reset_state_machine (s s' : State) (p : Pubkey)
    (h : resetTransition s p = some s') :
    s.status = .Resetting ∧ s'.status = .Active := by
  unfold resetTransition at h; split_ifs at h with hc
  cases h; exact ⟨hc.2, rfl⟩
