// ---- GENERATED BY QEDGEN — DO NOT EDIT ---- spec-hash:55ad3387c76e8476
// Parallax integration test scaffold.
// Tests run against the compiled .so binary via parallax-svm/LiteSVM.
//
// AGENT: fill instruction builder data and assertions marked with todo!().
//
// Prerequisites:
//   1. Build your program: cargo build-sbf (or cargo build --target bpfel-unknown-none)
//   2. Run tests: cargo test --features client
//
// Dev-dependencies (upserted into Cargo.toml by qedgen):
//   [dev-dependencies]
//   parallax-svm = { git = "https://github.com/blueshift-gg/parallax", rev = "804c5662832c65330e7299901cc5195a78d87256" }
//   solana-sdk-ids = "3.1"
//   # Parallax 0.1 compatibility pins; dependency Cargo.lock files are not inherited.
//   solana-address = "=2.6.1"
//   solana-hash = "=4.5.0"
//   solana-nonce = "=3.2.0"
//   solana-short-vec = "=3.2.2"
//   solana-last-restart-slot = "=3.1.0"
//   solana-slot-history = "=3.1.0"
//   solana-epoch-rewards = "=3.1.0"
//   solana-slot-hashes = "=3.1.0"
//   solana-rent = "=4.3.0"
//   solana-signature = "=3.4.1"
//   solana-epoch-schedule = "=3.2.0"
//   solana-fee-calculator = "=3.2.2"
//   spl-token = { version = "=9.0.0", default-features = false, features = ["no-entrypoint"] }
//   wincode = { version = "0.5", features = ["derive"] }

extern crate std;
use {
    lending as program,
    parallax_svm::prelude::*,
    program::client::*,
    program::state::*,
    spl_token::{
        solana_program::{program_option::COption, program_pack::Pack},
        state::{Account as SplTokenAccount, AccountState, Mint as SplMint},
    },
    std::vec,
};

// ── Setup ────────────────────────────────────────────────────────

fn setup() -> Ctx {
    Ctx::builder(program::ID)
        .crate_name(env!("CARGO_PKG_NAME"))
        .build()
        .expect("load compiled program into Parallax")
}

// ── Account helpers ──────────────────────────────────────────────

#[allow(dead_code)]
fn signer_account(address: Pubkey) -> Account {
    Account::new(address, system_program::ID, DEFAULT_WALLET_LAMPORTS, vec![])
}

#[allow(dead_code)]
fn empty_account(address: Pubkey) -> Account {
    Account::new(address, system_program::ID, 0, vec![])
}
/// Create a pre-populated LendingAccount account (program-owned).
#[allow(dead_code)]
fn state_account(
    address: Pubkey,
    authority: Pubkey,
    total_deposits: u64,
    total_borrows: u64,
    interest_rate: u64,
    bump: u8,
) -> Account {
    let state = LendingAccount {
        authority,
        total_deposits,
        total_borrows,
        interest_rate,
        bump,
    };
    Account {
        address,
        lamports: 2_000_000,
        data: wincode::serialize(&state).unwrap(),
        owner: program::ID,
        executable: false,
    }
}

#[allow(dead_code)]
fn mint_account(address: Pubkey, authority: Pubkey) -> Account {
    let mint = SplMint {
        mint_authority: COption::Some(authority),
        supply: 1_000_000_000,
        decimals: 9,
        is_initialized: true,
        freeze_authority: COption::None,
    };
    let mut data = vec![0; SplMint::LEN];
    SplMint::pack(mint, &mut data).expect("encode SPL mint fixture");
    Account::new(address, SPL_TOKEN_PROGRAM_ID, 2_000_000, data)
}

#[allow(dead_code)]
fn token_account(address: Pubkey, mint: Pubkey, owner: Pubkey, amount: u64) -> Account {
    let token = SplTokenAccount {
        mint,
        owner,
        amount,
        delegate: COption::None,
        state: AccountState::Initialized,
        is_native: COption::None,
        delegated_amount: 0,
        close_authority: COption::None,
    };
    let mut data = vec![0; SplTokenAccount::LEN];
    SplTokenAccount::pack(token, &mut data).expect("encode SPL token fixture");
    Account::new(address, SPL_TOKEN_PROGRAM_ID, 2_000_000, data)
}
// ── init_pool ──

#[test]
fn test_init_pool() {
    let mut ctx = setup();

    // Account addresses
    let system_program = system_program::ID;
    let authority = Pubkey::new_unique();
    let (pool, _pool_bump) =
        Pubkey::find_program_address(&[b"pool", authority.as_ref()], &program::ID);

    // Instruction parameters
    let rate: u64 = 1_000_000; // AGENT: set appropriate value

    let instruction: Instruction = InitPoolInstruction {
        authority,
        pool,
        system_program,
        rate,
    }
    .into();

    let outcome = ctx.execute_with(
        instruction,
        vec![signer_account(authority), empty_account(pool)],
    );

    outcome.check(Outcome::success()); // init_pool

    // AGENT: verify account state after instruction
    // let pool_data = &outcome.account(pool).unwrap().data;
    // Spec effect: interest_rate set rate
    // Spec effect: total_deposits set 0
    // Spec effect: total_borrows set 0

    // AGENT: pin a compute budget once measured, e.g.
    //   outcome.check(Cu::spent(|cu| cu <= 20_000));
}

// ── deposit ──

#[test]
fn test_deposit() {
    let mut ctx = setup();

    // Account addresses
    let token_program = SPL_TOKEN_PROGRAM_ID;
    let authority = Pubkey::new_unique(); // AGENT: replace with the authority from pre-state
    let depositor = Pubkey::new_unique();
    let (pool, _pool_bump) =
        Pubkey::find_program_address(&[b"pool", authority.as_ref()], &program::ID);
    let pool_vault = Pubkey::new_unique();
    let depositor_ta = Pubkey::new_unique();

    // Instruction parameters
    let amount: u64 = 1_000_000; // AGENT: set appropriate value

    let instruction: Instruction = DepositInstruction {
        depositor,
        pool,
        pool_vault,
        depositor_ta,
        token_program,
        amount,
    }
    .into();

    let outcome = ctx.execute_with(
        instruction,
        vec![
            signer_account(depositor),
            empty_account(pool) /* AGENT: use state_account() with appropriate fields */,
            token_account(pool_vault, Pubkey::new_unique(), pool, 1_000_000) /* AGENT: set mint; tune amount */,
            token_account(depositor_ta, Pubkey::new_unique(), depositor, 1_000_000) /* AGENT: set mint, owner; tune amount */,
        ],
    );

    outcome.check(Outcome::success()); // deposit

    // AGENT: verify account state after instruction
    // let pool_data = &outcome.account(pool).unwrap().data;
    // let pool_vault_data = &outcome.account(pool_vault).unwrap().data;
    // let depositor_ta_data = &outcome.account(depositor_ta).unwrap().data;
    // Spec effect: total_deposits add amount

    // AGENT: pin a compute budget once measured, e.g.
    //   outcome.check(Cu::spent(|cu| cu <= 20_000));
}

// ── borrow ──

#[test]
fn test_borrow() {
    let mut ctx = setup();

    // Account addresses
    let system_program = system_program::ID;
    let token_program = SPL_TOKEN_PROGRAM_ID;
    let authority = Pubkey::new_unique(); // AGENT: replace with the authority from pre-state
    let borrower = Pubkey::new_unique();
    let (loan, _loan_bump) =
        Pubkey::find_program_address(&[b"loan", pool.as_ref(), borrower.as_ref()], &program::ID);
    let (pool, _pool_bump) =
        Pubkey::find_program_address(&[b"pool", authority.as_ref()], &program::ID);
    let pool_vault = Pubkey::new_unique();
    let borrower_ta = Pubkey::new_unique();

    // Instruction parameters
    let amount: u64 = 1_000_000; // AGENT: set appropriate value
    let collateral: u64 = 1_000_000; // AGENT: set appropriate value

    let instruction: Instruction = BorrowInstruction {
        borrower,
        loan,
        pool,
        pool_vault,
        borrower_ta,
        token_program,
        system_program,
        amount,
        collateral,
    }
    .into();

    let outcome = ctx.execute_with(
        instruction,
        vec![
            signer_account(borrower),
            empty_account(loan),
            empty_account(pool),
            token_account(pool_vault, Pubkey::new_unique(), pool, 1_000_000) /* AGENT: set mint; tune amount */,
            token_account(borrower_ta, Pubkey::new_unique(), borrower, 1_000_000) /* AGENT: set mint, owner; tune amount */,
        ],
    );

    outcome.check(Outcome::success()); // borrow

    // AGENT: verify account state after instruction
    // let loan_data = &outcome.account(loan).unwrap().data;
    // let pool_data = &outcome.account(pool).unwrap().data;
    // let pool_vault_data = &outcome.account(pool_vault).unwrap().data;
    // let borrower_ta_data = &outcome.account(borrower_ta).unwrap().data;
    // Spec effect: amount set amount
    // Spec effect: collateral set collateral

    // AGENT: pin a compute budget once measured, e.g.
    //   outcome.check(Cu::spent(|cu| cu <= 20_000));
}

// ── repay ──

#[test]
fn test_repay() {
    let mut ctx = setup();

    // Account addresses
    let token_program = SPL_TOKEN_PROGRAM_ID;
    let authority = Pubkey::new_unique(); // AGENT: replace with the authority from pre-state
    let borrower = Pubkey::new_unique();
    let (loan, _loan_bump) =
        Pubkey::find_program_address(&[b"loan", pool.as_ref(), borrower.as_ref()], &program::ID);
    let (pool, _pool_bump) =
        Pubkey::find_program_address(&[b"pool", authority.as_ref()], &program::ID);
    let pool_vault = Pubkey::new_unique();
    let borrower_ta = Pubkey::new_unique();

    let instruction: Instruction = RepayInstruction {
        borrower,
        loan,
        pool,
        pool_vault,
        borrower_ta,
        token_program,
    }
    .into();

    let outcome = ctx.execute_with(
        instruction,
        vec![
            signer_account(borrower),
            empty_account(loan) /* AGENT: use state_account() with appropriate fields */,
            empty_account(pool) /* AGENT: use state_account() with appropriate fields */,
            token_account(pool_vault, Pubkey::new_unique(), pool, 1_000_000) /* AGENT: set mint; tune amount */,
            token_account(borrower_ta, Pubkey::new_unique(), borrower, 1_000_000) /* AGENT: set mint, owner; tune amount */,
        ],
    );

    outcome.check(Outcome::success()); // repay

    // AGENT: verify account state after instruction
    // let loan_data = &outcome.account(loan).unwrap().data;
    // let pool_data = &outcome.account(pool).unwrap().data;
    // let pool_vault_data = &outcome.account(pool_vault).unwrap().data;
    // let borrower_ta_data = &outcome.account(borrower_ta).unwrap().data;
    // Spec effect: amount set 0
    // Spec effect: collateral set 0

    // AGENT: pin a compute budget once measured, e.g.
    //   outcome.check(Cu::spent(|cu| cu <= 20_000));
}

// ── liquidate ──

#[test]
fn test_liquidate() {
    let mut ctx = setup();

    // Account addresses
    let token_program = SPL_TOKEN_PROGRAM_ID;
    let borrower = Pubkey::new_unique(); // AGENT: replace with the borrower from pre-state
    let authority = Pubkey::new_unique(); // AGENT: replace with the authority from pre-state
    let liquidator = Pubkey::new_unique();
    let (loan, _loan_bump) =
        Pubkey::find_program_address(&[b"loan", pool.as_ref(), borrower.as_ref()], &program::ID);
    let (pool, _pool_bump) =
        Pubkey::find_program_address(&[b"pool", authority.as_ref()], &program::ID);
    let pool_vault = Pubkey::new_unique();
    let liquidator_ta = Pubkey::new_unique();

    let instruction: Instruction = LiquidateInstruction {
        liquidator,
        loan,
        pool,
        pool_vault,
        liquidator_ta,
        token_program,
    }
    .into();

    let outcome = ctx.execute_with(
        instruction,
        vec![
            signer_account(liquidator),
            empty_account(loan) /* AGENT: use state_account() with appropriate fields */,
            empty_account(pool) /* AGENT: use state_account() with appropriate fields */,
            token_account(pool_vault, Pubkey::new_unique(), pool, 1_000_000) /* AGENT: set mint; tune amount */,
            token_account(liquidator_ta, Pubkey::new_unique(), liquidator, 1_000_000) /* AGENT: set mint, owner; tune amount */,
        ],
    );

    outcome.check(Outcome::success()); // liquidate

    // AGENT: verify account state after instruction
    // let loan_data = &outcome.account(loan).unwrap().data;
    // let pool_data = &outcome.account(pool).unwrap().data;
    // let pool_vault_data = &outcome.account(pool_vault).unwrap().data;
    // let liquidator_ta_data = &outcome.account(liquidator_ta).unwrap().data;
    // Spec effect: amount set 0

    // AGENT: pin a compute budget once measured, e.g.
    //   outcome.check(Cu::spent(|cu| cu <= 20_000));
}

/// init_pool must reject unauthorized callers (wrong authority).
#[test]
fn test_init_pool_unauthorized() {
    let mut ctx = setup();

    let system_program = system_program::ID;
    let wrong_authority = Pubkey::new_unique();
    let pool = Pubkey::new_unique();

    let instruction: Instruction = InitPoolInstruction {
        authority: wrong_authority,
        pool,
        system_program,
        rate: 1_000_000,
    }
    .into();

    let outcome = ctx.execute_with(
        instruction,
        vec![signer_account(wrong_authority), empty_account(pool)],
    );

    // init_pool must reject a forged authority with the spec's authorization error.
    outcome.check(Outcome::error(program::errors::LendingError::Unauthorized));
}

/// borrow must reject unauthorized callers (wrong borrower).
#[test]
fn test_borrow_unauthorized() {
    let mut ctx = setup();

    let system_program = system_program::ID;
    let token_program = SPL_TOKEN_PROGRAM_ID;
    let wrong_borrower = Pubkey::new_unique();
    let loan = Pubkey::new_unique();
    let pool = Pubkey::new_unique();
    let pool_vault = Pubkey::new_unique();
    let borrower_ta = Pubkey::new_unique();

    let instruction: Instruction = BorrowInstruction {
        borrower: wrong_borrower,
        loan,
        pool,
        pool_vault,
        borrower_ta,
        token_program,
        system_program,
        amount: 1_000_000,
        collateral: 1_000_000,
    }
    .into();

    let outcome = ctx.execute_with(
        instruction,
        vec![
            signer_account(wrong_borrower),
            empty_account(loan),
            empty_account(pool),
            token_account(pool_vault, Pubkey::new_unique(), pool, 1_000_000) /* AGENT: set mint; tune amount */,
            token_account(borrower_ta, Pubkey::new_unique(), wrong_borrower, 1_000_000) /* AGENT: set mint, owner; tune amount */,
        ],
    );

    // borrow must reject a forged borrower with the spec's authorization error.
    outcome.check(Outcome::error(program::errors::LendingError::Unauthorized));
}

/// repay must reject unauthorized callers (wrong borrower).
#[test]
fn test_repay_unauthorized() {
    let mut ctx = setup();

    let token_program = SPL_TOKEN_PROGRAM_ID;
    let wrong_borrower = Pubkey::new_unique();
    let loan = Pubkey::new_unique();
    let pool = Pubkey::new_unique();
    let pool_vault = Pubkey::new_unique();
    let borrower_ta = Pubkey::new_unique();

    let instruction: Instruction = RepayInstruction {
        borrower: wrong_borrower,
        loan,
        pool,
        pool_vault,
        borrower_ta,
        token_program,
    }
    .into();

    let outcome = ctx.execute_with(
        instruction,
        vec![
            signer_account(wrong_borrower),
            empty_account(loan) /* AGENT: use state_account() with appropriate fields */,
            empty_account(pool) /* AGENT: use state_account() with appropriate fields */,
            token_account(pool_vault, Pubkey::new_unique(), pool, 1_000_000) /* AGENT: set mint; tune amount */,
            token_account(borrower_ta, Pubkey::new_unique(), wrong_borrower, 1_000_000) /* AGENT: set mint, owner; tune amount */,
        ],
    );

    // repay must reject a forged borrower with the spec's authorization error.
    outcome.check(Outcome::error(program::errors::LendingError::Unauthorized));
}

// ── Lifecycle sequence ────────────────────────────────────────────

/// End-to-end lifecycle: execute operations in spec order.
/// AGENT: fill in instruction parameters and account setup for each step.
#[test]
#[allow(unused_mut, unused_variables)] // until the sequence is filled in
fn test_lifecycle_sequence() {
    let mut ctx = setup();

    // Lifecycle transitions:
    //   init_pool : Uninitialized → Active
    //   deposit : Active → Active
    //   borrow : Empty → Active
    //   repay : Active → Empty
    //   liquidate : Active → Liquidated

    // Step 1: init_pool (Uninitialized → Active)
    // AGENT: build and execute init_pool instruction
    todo!("build instruction sequence");
}
