use anyhow::{bail, Context, Result};
use std::path::Path;
use std::process::Command;

/// Until qedsvm ships sBPF v3 semantics (#429), the proofs run against its V0
/// model. The layout of `.rodata` symbols is v3 (asm2lean), but the
/// instruction and memory semantics are not.
const QEDSVM_V3_NOTE: &str = "the Lean proofs use qedsvm's sBPF V0 semantics until qedsvm \
     adds v3 (qedgen #429). They cover the instructions V0 and v3 share. v3-only JMP32 \
     instructions are not modeled yet, and asm2lean rejects them.";

/// Verify an sBPF project: check source hash and sBPF version, regenerate if
/// stale, run lake build.
///
/// `spec_version` is the spec's `pragma sbpf_version`, if any. When set and it
/// differs from the version recorded in the generated module, the module is
/// regenerated even if the source is unchanged, because `.rodata` addresses
/// depend on the version.
///
/// Returns Ok(()) if proofs are valid, Err if stale/broken.
pub fn verify(
    asm_source: &Path,
    proofs_dir: &Path,
    spec_version: Option<crate::asm2lean::SbpfVersion>,
) -> Result<()> {
    let source = std::fs::read_to_string(asm_source)
        .with_context(|| format!("reading {}", asm_source.display()))?;

    let current_hash = crate::asm2lean::source_hash(&source);

    let generated_file = find_generated_module(proofs_dir)?;
    let generated_content = std::fs::read_to_string(&generated_file)
        .with_context(|| format!("reading {}", generated_file.display()))?;

    let embedded_hash = crate::asm2lean::extract_source_hash(&generated_content);

    let hash_stale = match &embedded_hash {
        Some(h) => h != &current_hash,
        None => {
            eprintln!(
                "Warning: {} has no source hash (generated before v1.5). Regenerating.",
                generated_file.display()
            );
            true
        }
    };

    let recorded_version = crate::asm2lean::extract_sbpf_version(&generated_content);
    let version = crate::asm2lean::resolve_and_report_sbpf_version(
        None,
        spec_version,
        Some(&generated_content),
        &generated_file,
    );
    let version_stale = recorded_version != Some(version);
    if version == crate::asm2lean::SbpfVersion::V3 {
        eprintln!("note: {}", QEDSVM_V3_NOTE);
    }

    if hash_stale || version_stale {
        let why = match (hash_stale, version_stale) {
            (true, true) => format!("source hash and sBPF version ({}) changed", version.label()),
            (true, false) => "source hash mismatch".to_string(),
            (false, _) => format!("sBPF version is now {}", version.label()),
        };
        eprintln!(
            "{} — regenerating {} from {}",
            why,
            generated_file.display(),
            asm_source.display()
        );
        let namespace = generated_file
            .file_stem()
            .map(|s| s.to_string_lossy().to_string())
            .unwrap_or_else(|| "Program".to_string());
        crate::asm2lean::asm2lean(asm_source, &generated_file, Some(&namespace), version)?;
    } else {
        eprintln!(
            "Source hash matches (sha256:{}...), sBPF {}",
            &current_hash[..12],
            version.label()
        );
    }

    eprintln!("Running lake build in {}", proofs_dir.display());
    let status = Command::new("lake")
        .arg("build")
        .current_dir(proofs_dir)
        .status()
        .with_context(|| "failed to run `lake build`")?;

    if !status.success() {
        bail!("lake build failed — proofs are broken");
    }

    eprintln!("Verification passed.");
    Ok(())
}

/// Find the asm2lean-generated Lean file in a proofs directory.
/// Looks for files containing "Auto-generated by qedgen asm2lean".
fn find_generated_module(proofs_dir: &Path) -> Result<std::path::PathBuf> {
    for entry in std::fs::read_dir(proofs_dir)
        .with_context(|| format!("reading directory {}", proofs_dir.display()))?
    {
        let entry = entry?;
        let path = entry.path();
        if path.extension().and_then(|e| e.to_str()) == Some("lean") {
            if let Ok(content) = std::fs::read_to_string(&path) {
                if content.contains("Auto-generated by qedgen asm2lean") {
                    return Ok(path);
                }
            }
        }
    }
    bail!(
        "No asm2lean-generated .lean file found in {}. Run `qedgen init --asm` first.",
        proofs_dir.display()
    );
}
