// ---- GENERATED BY QEDGEN — DO NOT EDIT ---- spec-hash:4c889fc8b4512b14
use quasar_lang::prelude::*;

#[error_code]
pub enum PercolatorError {
    InsufficientFunds = 0,
}
// ---- END GENERATED ----
