// ---- GENERATED BY QEDGEN — DO NOT EDIT ---- spec-hash:59c564b023d10c9b
// QuasarSVM integration test scaffold.
// Tests run against the compiled .so binary via quasar-svm.
//
// AGENT: fill instruction builder data and assertions marked with todo!().
//
// Prerequisites:
//   1. Build your program: cargo build-sbf (or cargo build --target bpfel-unknown-none)
//   2. Run tests: cargo test --features client
//
// Dev-dependencies (add to Cargo.toml):
//   [dev-dependencies]
//   percolator-client = { path = "client" }
//   quasar-svm = { git = "https://github.com/blueshift-gg/quasar-svm" }

extern crate std;
use {
    percolator_client::*,
    quasar_svm::{Account, Instruction, Pubkey, QuasarSvm},
    std::{println, vec},
};

// ── Setup ────────────────────────────────────────────────────────

fn setup() -> QuasarSvm {
    let elf = std::fs::read("../../target/deploy/percolator.so").unwrap();
    QuasarSvm::new().with_program(&crate::ID, &elf)
}

// ── Account helpers ──────────────────────────────────────────────

fn signer(address: Pubkey) -> Account {
    quasar_svm::token::create_keyed_system_account(&address, 10_000_000_000)
}

fn empty(address: Pubkey) -> Account {
    Account {
        address,
        lamports: 0,
        data: vec![],
        owner: quasar_svm::system_program::ID,
        executable: false,
    }
}

/// Create a pre-populated PercolatorAccount account (program-owned).
fn state_account(
    address: Pubkey,
    authority: Pubkey,
    V: u128,
    C_tot: u128,
    I: u128,
    bump: u8,
) -> Account {
    let state = PercolatorAccount {
        authority,
        V,
        C_tot,
        I,
        bump,
    };
    Account {
        address,
        lamports: 2_000_000,
        data: wincode::serialize(&state).unwrap(),
        owner: crate::ID,
        executable: false,
    }
}

// ── deposit ──

/// Happy path: User adds capital — V and C_tot increase by same amount
#[test]
fn test_deposit() {
    let mut svm = setup();

    // Account addresses
    let authority = Pubkey::new_unique();
    let vault = Pubkey::new_unique();

    // Instruction parameters
    let amount: u128 = 1_000_000; // AGENT: set appropriate value

    let instruction: Instruction = DepositInstruction {
        authority,
        vault,
        amount,
    }
    .into();

    let result = svm.process_instruction(
        &instruction,
        &[
            signer(authority),
            empty(vault) /* AGENT: use state_account() with appropriate fields */,
        ],
    );

    assert!(result.is_ok(), "deposit failed: {:?}", result.raw_result);

    // AGENT: verify account state after instruction
    // let vault_data = &result.account(&vault).unwrap().data;
    // Spec effect: V add amount
    // Spec effect: C_tot add amount

    println!("  DEPOSIT CU: {}", result.compute_units_consumed);
}

// ── withdraw ──

/// Happy path: User removes capital — V and C_tot decrease by same amount
#[test]
fn test_withdraw() {
    let mut svm = setup();

    // Account addresses
    let authority = Pubkey::new_unique();
    let vault = Pubkey::new_unique();

    // Instruction parameters
    let amount: u128 = 1_000_000; // AGENT: set appropriate value

    let instruction: Instruction = WithdrawInstruction {
        authority,
        vault,
        amount,
    }
    .into();

    let result = svm.process_instruction(
        &instruction,
        &[
            signer(authority),
            empty(vault) /* AGENT: use state_account() with appropriate fields */,
        ],
    );

    assert!(result.is_ok(), "withdraw failed: {:?}", result.raw_result);

    // AGENT: verify account state after instruction
    // let vault_data = &result.account(&vault).unwrap().data;
    // Spec effect: V sub amount
    // Spec effect: C_tot sub amount

    println!("  WITHDRAW CU: {}", result.compute_units_consumed);
}

// ── top_up_insurance ──

/// Happy path: External deposit into insurance fund
#[test]
fn test_top_up_insurance() {
    let mut svm = setup();

    // Account addresses
    let authority = Pubkey::new_unique();
    let vault = Pubkey::new_unique();

    // Instruction parameters
    let amount: u128 = 1_000_000; // AGENT: set appropriate value

    let instruction: Instruction = TopUpInsuranceInstruction {
        authority,
        vault,
        amount,
    }
    .into();

    let result = svm.process_instruction(
        &instruction,
        &[
            signer(authority),
            empty(vault) /* AGENT: use state_account() with appropriate fields */,
        ],
    );

    assert!(result.is_ok(), "top_up_insurance failed: {:?}", result.raw_result);

    // AGENT: verify account state after instruction
    // let vault_data = &result.account(&vault).unwrap().data;
    // Spec effect: V add amount
    // Spec effect: I add amount

    println!("  TOP_UP_INSURANCE CU: {}", result.compute_units_consumed);
}

// ── trigger_adl ──

/// Happy path: Begin auto-deleveraging cycle
#[test]
fn test_trigger_adl() {
    let mut svm = setup();

    // Account addresses
    let authority = Pubkey::new_unique();
    let vault = Pubkey::new_unique();

    let instruction: Instruction = TriggerAdlInstruction {
        authority,
        vault,
    }
    .into();

    let result = svm.process_instruction(
        &instruction,
        &[
            signer(authority),
            empty(vault) /* AGENT: use state_account() with appropriate fields */,
        ],
    );

    assert!(result.is_ok(), "trigger_adl failed: {:?}", result.raw_result);

    println!("  TRIGGER_ADL CU: {}", result.compute_units_consumed);
}

// ── complete_drain ──

/// Happy path: Complete the drain phase of ADL
#[test]
fn test_complete_drain() {
    let mut svm = setup();

    // Account addresses
    let authority = Pubkey::new_unique();
    let vault = Pubkey::new_unique();

    let instruction: Instruction = CompleteDrainInstruction {
        authority,
        vault,
    }
    .into();

    let result = svm.process_instruction(
        &instruction,
        &[
            signer(authority),
            empty(vault) /* AGENT: use state_account() with appropriate fields */,
        ],
    );

    assert!(result.is_ok(), "complete_drain failed: {:?}", result.raw_result);

    println!("  COMPLETE_DRAIN CU: {}", result.compute_units_consumed);
}

// ── reset ──

/// Happy path: Reset risk engine after ADL cycle
#[test]
fn test_reset() {
    let mut svm = setup();

    // Account addresses
    let authority = Pubkey::new_unique();
    let vault = Pubkey::new_unique();

    let instruction: Instruction = ResetInstruction {
        authority,
        vault,
    }
    .into();

    let result = svm.process_instruction(
        &instruction,
        &[
            signer(authority),
            empty(vault) /* AGENT: use state_account() with appropriate fields */,
        ],
    );

    assert!(result.is_ok(), "reset failed: {:?}", result.raw_result);

    println!("  RESET CU: {}", result.compute_units_consumed);
}

/// deposit must reject unauthorized callers (wrong authority).
#[test]
fn test_deposit_unauthorized() {
    let mut svm = setup();

    let wrong_authority = Pubkey::new_unique();
    let vault = Pubkey::new_unique();

    let instruction: Instruction = DepositInstruction {
        authority: wrong_authority,
        vault,
        amount: 1_000_000,
    }
    .into();

    let result = svm.process_instruction(
        &instruction,
        &[
            signer(wrong_authority),
            empty(vault) /* AGENT: use state_account() with appropriate fields */,
        ],
    );

    assert!(result.is_err(), "deposit should reject wrong authority");
}

/// withdraw must reject unauthorized callers (wrong authority).
#[test]
fn test_withdraw_unauthorized() {
    let mut svm = setup();

    let wrong_authority = Pubkey::new_unique();
    let vault = Pubkey::new_unique();

    let instruction: Instruction = WithdrawInstruction {
        authority: wrong_authority,
        vault,
        amount: 1_000_000,
    }
    .into();

    let result = svm.process_instruction(
        &instruction,
        &[
            signer(wrong_authority),
            empty(vault) /* AGENT: use state_account() with appropriate fields */,
        ],
    );

    assert!(result.is_err(), "withdraw should reject wrong authority");
}

/// top_up_insurance must reject unauthorized callers (wrong authority).
#[test]
fn test_top_up_insurance_unauthorized() {
    let mut svm = setup();

    let wrong_authority = Pubkey::new_unique();
    let vault = Pubkey::new_unique();

    let instruction: Instruction = TopUpInsuranceInstruction {
        authority: wrong_authority,
        vault,
        amount: 1_000_000,
    }
    .into();

    let result = svm.process_instruction(
        &instruction,
        &[
            signer(wrong_authority),
            empty(vault) /* AGENT: use state_account() with appropriate fields */,
        ],
    );

    assert!(result.is_err(), "top_up_insurance should reject wrong authority");
}

/// trigger_adl must reject unauthorized callers (wrong authority).
#[test]
fn test_trigger_adl_unauthorized() {
    let mut svm = setup();

    let wrong_authority = Pubkey::new_unique();
    let vault = Pubkey::new_unique();

    let instruction: Instruction = TriggerAdlInstruction {
        authority: wrong_authority,
        vault,
    }
    .into();

    let result = svm.process_instruction(
        &instruction,
        &[
            signer(wrong_authority),
            empty(vault) /* AGENT: use state_account() with appropriate fields */,
        ],
    );

    assert!(result.is_err(), "trigger_adl should reject wrong authority");
}

/// complete_drain must reject unauthorized callers (wrong authority).
#[test]
fn test_complete_drain_unauthorized() {
    let mut svm = setup();

    let wrong_authority = Pubkey::new_unique();
    let vault = Pubkey::new_unique();

    let instruction: Instruction = CompleteDrainInstruction {
        authority: wrong_authority,
        vault,
    }
    .into();

    let result = svm.process_instruction(
        &instruction,
        &[
            signer(wrong_authority),
            empty(vault) /* AGENT: use state_account() with appropriate fields */,
        ],
    );

    assert!(result.is_err(), "complete_drain should reject wrong authority");
}

/// reset must reject unauthorized callers (wrong authority).
#[test]
fn test_reset_unauthorized() {
    let mut svm = setup();

    let wrong_authority = Pubkey::new_unique();
    let vault = Pubkey::new_unique();

    let instruction: Instruction = ResetInstruction {
        authority: wrong_authority,
        vault,
    }
    .into();

    let result = svm.process_instruction(
        &instruction,
        &[
            signer(wrong_authority),
            empty(vault) /* AGENT: use state_account() with appropriate fields */,
        ],
    );

    assert!(result.is_err(), "reset should reject wrong authority");
}

// ── Lifecycle sequence ────────────────────────────────────────────

/// End-to-end lifecycle: execute operations in spec order.
/// AGENT: fill in instruction parameters and account setup for each step.
#[test]
fn test_lifecycle_sequence() {
    let mut svm = setup();

    // Lifecycle transitions:
    //   deposit : Active → Active
    //   withdraw : Active → Active
    //   top_up_insurance : Active → Active
    //   trigger_adl : Active → Draining
    //   complete_drain : Draining → Resetting
    //   reset : Resetting → Active

    // AGENT: build instruction sequence to exercise lifecycle
    todo!("build instruction sequence");
}

