// ---- GENERATED BY QEDGEN — DO NOT EDIT ---- spec-hash:234256ab01782e9d
#![no_std]

use quasar_lang::prelude::*;

mod instructions;
use instructions::*;
pub mod errors;
pub mod state;

declare_id!("11111111111111111111111111111111");

#[program]
mod percolator {
    use super::*;

    /// User adds capital — V and C_tot increase by same amount
    #[instruction(discriminator = 0)]
    pub fn deposit(ctx: Ctx<Deposit>, amount: u128) -> Result<(), ProgramError> {
        ctx.accounts.handler(amount)
    }

    /// User removes capital — V and C_tot decrease by same amount
    #[instruction(discriminator = 1)]
    pub fn withdraw(ctx: Ctx<Withdraw>, amount: u128) -> Result<(), ProgramError> {
        ctx.accounts.handler(amount)
    }

    /// External deposit into insurance fund
    #[instruction(discriminator = 2)]
    pub fn top_up_insurance(ctx: Ctx<TopUpInsurance>, amount: u128) -> Result<(), ProgramError> {
        ctx.accounts.handler(amount)
    }

    /// Begin auto-deleveraging cycle
    #[instruction(discriminator = 3)]
    pub fn trigger_adl(ctx: Ctx<TriggerAdl>) -> Result<(), ProgramError> {
        ctx.accounts.handler()
    }

    /// Complete the drain phase of ADL
    #[instruction(discriminator = 4)]
    pub fn complete_drain(ctx: Ctx<CompleteDrain>) -> Result<(), ProgramError> {
        ctx.accounts.handler()
    }

    /// Reset risk engine after ADL cycle
    #[instruction(discriminator = 5)]
    pub fn reset(ctx: Ctx<Reset>) -> Result<(), ProgramError> {
        ctx.accounts.handler()
    }

}
// ---- END GENERATED ----
