// ---- GENERATED BY QEDGEN — DO NOT EDIT ---- spec-hash:e3eae08a5465eb86
use quasar_lang::prelude::*;

#[account(discriminator = 1, set_inner)]
pub struct PercolatorAccount {
    pub authority: Address,
    pub V: u128,
    pub C_tot: u128,
    pub I: u128,
}

/// Program lifecycle states.
#[derive(Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
pub enum Status {
    Active = 0,
    Draining = 1,
    Resetting = 2,
}
// ---- END GENERATED ----
