// ---- GENERATED BY QEDGEN — DO NOT EDIT ---- spec-hash:59c564b023d10c9b
// Unit tests generated from qedspec.
// These test effects, guards, and properties on a plain state struct.
// No SVM or Quasar runtime required — just `cargo test`.

type Address = [u8; 32];

#[derive(Debug, Clone, PartialEq)]
struct PercolatorState {
    authority: Address,
    V: u128,
    C_tot: u128,
    I: u128,
}

impl Default for PercolatorState {
    fn default() -> Self {
        PercolatorState {
            authority: [0u8; 32],
            V: 0u128,
            C_tot: 0u128,
            I: 0u128,
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Status {
    Active,
    Draining,
    Resetting,
}

/// Apply `deposit` effects to state.
fn apply_deposit(state: &mut PercolatorState, amount: u128) {
    state.V += amount;
    state.C_tot += amount;
}

/// Apply `withdraw` effects to state.
fn apply_withdraw(state: &mut PercolatorState, amount: u128) {
    state.V -= amount;
    state.C_tot -= amount;
}

/// Apply `top_up_insurance` effects to state.
fn apply_top_up_insurance(state: &mut PercolatorState, amount: u128) {
    state.V += amount;
    state.I += amount;
}

/// Guard predicate for `deposit`.
fn guard_deposit(_state: &PercolatorState, amount: u128) -> bool {
    true
}

/// Guard predicate for `withdraw`.
fn guard_withdraw(_state: &PercolatorState, amount: u128) -> bool {
    true
}

/// Guard predicate for `top_up_insurance`.
fn guard_top_up_insurance(_state: &PercolatorState, amount: u128) -> bool {
    true
}

#[cfg(test)]
mod tests {
    use super::*;

    // ====================================================================
    // Effect tests — verify state mutations match spec
    // ====================================================================

    #[test]
    fn test_deposit_effects() {
        let mut state = PercolatorState {
            authority: [1u8; 32],
            V: 0u128,
            C_tot: 0u128,
            I: 0u128,
        };
        let amount: u128 = 1;
        let pre_V = state.V;
        let pre_C_tot = state.C_tot;
        apply_deposit(&mut state, amount);
        assert_eq!(state.V, pre_V + amount);
        assert_eq!(state.C_tot, pre_C_tot + amount);
    }

    #[test]
    fn test_withdraw_effects() {
        let mut state = PercolatorState {
            authority: [1u8; 32],
            V: 0u128,
            C_tot: 0u128,
            I: 0u128,
        };
        let amount: u128 = 1;
        let pre_V = state.V;
        let pre_C_tot = state.C_tot;
        apply_withdraw(&mut state, amount);
        assert_eq!(state.V, pre_V - amount);
        assert_eq!(state.C_tot, pre_C_tot - amount);
    }

    #[test]
    fn test_top_up_insurance_effects() {
        let mut state = PercolatorState {
            authority: [1u8; 32],
            V: 0u128,
            C_tot: 0u128,
            I: 0u128,
        };
        let amount: u128 = 1;
        let pre_V = state.V;
        let pre_I = state.I;
        apply_top_up_insurance(&mut state, amount);
        assert_eq!(state.V, pre_V + amount);
        assert_eq!(state.I, pre_I + amount);
    }

    // ====================================================================
    // Guard tests — verify boundary conditions
    // ====================================================================

    #[test]
    fn test_deposit_guard_accepts_valid() {
        let state = PercolatorState {
            authority: [1u8; 32],
            V: 0u128,
            C_tot: 0u128,
            I: 0u128,
        };
        let amount: u128 = 1;
        assert!(guard_deposit(&state, amount));
    }

    #[test]
    fn test_deposit_guard_rejects_invalid() {
        let state = PercolatorState {
            authority: [1u8; 32],
            V: 0u128,
            C_tot: 0u128,
            I: 0u128,
        };
        let amount: u128 = 0;
        assert!(!guard_deposit(&state, amount));
    }

    #[test]
    fn test_withdraw_guard_accepts_valid() {
        let state = PercolatorState {
            authority: [1u8; 32],
            V: 0u128,
            C_tot: 0u128,
            I: 0u128,
        };
        let amount: u128 = 1;
        assert!(guard_withdraw(&state, amount));
    }

    #[test]
    fn test_withdraw_guard_rejects_invalid() {
        let state = PercolatorState {
            authority: [1u8; 32],
            V: 0u128,
            C_tot: 0u128,
            I: 0u128,
        };
        let amount: u128 = 0;
        assert!(!guard_withdraw(&state, amount));
    }

    #[test]
    fn test_top_up_insurance_guard_accepts_valid() {
        let state = PercolatorState {
            authority: [1u8; 32],
            V: 0u128,
            C_tot: 0u128,
            I: 0u128,
        };
        let amount: u128 = 1;
        assert!(guard_top_up_insurance(&state, amount));
    }

    #[test]
    fn test_top_up_insurance_guard_rejects_invalid() {
        let state = PercolatorState {
            authority: [1u8; 32],
            V: 0u128,
            C_tot: 0u128,
            I: 0u128,
        };
        let amount: u128 = 0;
        assert!(!guard_top_up_insurance(&state, amount));
    }

    // ====================================================================
    // Property tests — verify invariants hold after effects
    // ====================================================================

    #[test]
    fn test_deposit_preserves_conservation() {
        let mut state = PercolatorState {
            authority: [1u8; 32],
            V: 0u128,
            C_tot: 0u128,
            I: 0u128,
        };
        let amount: u128 = 1;
        apply_deposit(&mut state, amount);
        // Property: conservation must hold after deposit
        assert!(state.V >= state.C_tot + state.I, "conservation must hold after deposit");
    }

    #[test]
    fn test_withdraw_preserves_conservation() {
        let mut state = PercolatorState {
            authority: [1u8; 32],
            V: 0u128,
            C_tot: 0u128,
            I: 0u128,
        };
        let amount: u128 = 1;
        apply_withdraw(&mut state, amount);
        // Property: conservation must hold after withdraw
        assert!(state.V >= state.C_tot + state.I, "conservation must hold after withdraw");
    }

    #[test]
    fn test_top_up_insurance_preserves_conservation() {
        let mut state = PercolatorState {
            authority: [1u8; 32],
            V: 0u128,
            C_tot: 0u128,
            I: 0u128,
        };
        let amount: u128 = 1;
        apply_top_up_insurance(&mut state, amount);
        // Property: conservation must hold after top_up_insurance
        assert!(state.V >= state.C_tot + state.I, "conservation must hold after top_up_insurance");
    }

    #[test]
    fn test_deposit_preserves_vault_bounded() {
        let mut state = PercolatorState {
            authority: [1u8; 32],
            V: 0u128,
            C_tot: 0u128,
            I: 0u128,
        };
        let amount: u128 = 1;
        apply_deposit(&mut state, amount);
        // Property: vault bounded must hold after deposit
        assert!(state.V <= 10000000000000000, "vault_bounded must hold after deposit");
    }

    #[test]
    fn test_top_up_insurance_preserves_vault_bounded() {
        let mut state = PercolatorState {
            authority: [1u8; 32],
            V: 0u128,
            C_tot: 0u128,
            I: 0u128,
        };
        let amount: u128 = 1;
        apply_top_up_insurance(&mut state, amount);
        // Property: vault bounded must hold after top_up_insurance
        assert!(state.V <= 10000000000000000, "vault_bounded must hold after top_up_insurance");
    }

    // ====================================================================
    // Unchanged field tests — fields not in effects must not change
    // ====================================================================

    #[test]
    fn test_deposit_unchanged_fields() {
        let mut state = PercolatorState {
            authority: [1u8; 32],
            V: 0u128,
            C_tot: 0u128,
            I: 0u128,
        };
        let amount: u128 = 1;
        let pre_I = state.I.clone();
        apply_deposit(&mut state, amount);
        assert_eq!(state.I, pre_I, "I must not change after deposit");
    }

    #[test]
    fn test_withdraw_unchanged_fields() {
        let mut state = PercolatorState {
            authority: [1u8; 32],
            V: 0u128,
            C_tot: 0u128,
            I: 0u128,
        };
        let amount: u128 = 1;
        let pre_I = state.I.clone();
        apply_withdraw(&mut state, amount);
        assert_eq!(state.I, pre_I, "I must not change after withdraw");
    }

    #[test]
    fn test_top_up_insurance_unchanged_fields() {
        let mut state = PercolatorState {
            authority: [1u8; 32],
            V: 0u128,
            C_tot: 0u128,
            I: 0u128,
        };
        let amount: u128 = 1;
        let pre_C_tot = state.C_tot.clone();
        apply_top_up_insurance(&mut state, amount);
        assert_eq!(state.C_tot, pre_C_tot, "C_tot must not change after top_up_insurance");
    }

    // ====================================================================
    // State machine tests — verify lifecycle transitions
    // ====================================================================

    #[test]
    fn test_deposit_transition_active_to_active() {
        // deposit requires status == Active and moves to Active
        assert_eq!(Status::Active, Status::Active, "deposit is a self-transition");
        let _pre = Status::Active;
        let _post = Status::Active;
        // AGENT: verify handler transitions status from _pre to _post
    }

    #[test]
    fn test_withdraw_transition_active_to_active() {
        // withdraw requires status == Active and moves to Active
        assert_eq!(Status::Active, Status::Active, "withdraw is a self-transition");
        let _pre = Status::Active;
        let _post = Status::Active;
        // AGENT: verify handler transitions status from _pre to _post
    }

    #[test]
    fn test_top_up_insurance_transition_active_to_active() {
        // top_up_insurance requires status == Active and moves to Active
        assert_eq!(Status::Active, Status::Active, "top_up_insurance is a self-transition");
        let _pre = Status::Active;
        let _post = Status::Active;
        // AGENT: verify handler transitions status from _pre to _post
    }

    #[test]
    fn test_trigger_adl_transition_active_to_draining() {
        // trigger_adl requires status == Active and moves to Draining
        assert_ne!(Status::Active, Status::Draining, "trigger_adl changes status");
        let _pre = Status::Active;
        let _post = Status::Draining;
        // AGENT: verify handler transitions status from _pre to _post
    }

    #[test]
    fn test_complete_drain_transition_draining_to_resetting() {
        // complete_drain requires status == Draining and moves to Resetting
        assert_ne!(Status::Draining, Status::Resetting, "complete_drain changes status");
        let _pre = Status::Draining;
        let _post = Status::Resetting;
        // AGENT: verify handler transitions status from _pre to _post
    }

    #[test]
    fn test_reset_transition_resetting_to_active() {
        // reset requires status == Resetting and moves to Active
        assert_ne!(Status::Resetting, Status::Active, "reset changes status");
        let _pre = Status::Resetting;
        let _post = Status::Active;
        // AGENT: verify handler transitions status from _pre to _post
    }

}
