use anyhow::Result;
use std::path::Path;

use crate::check::{self, ParsedAccountEntry, ParsedContext, ParsedSpec};
use crate::fingerprint::SpecFingerprint;

/// Map DSL type to Quasar Rust type.
pub fn map_type(dsl_type: &str) -> &str {
    match dsl_type {
        "Pubkey" => "Address",
        "U64" => "u64",
        "U128" => "u128",
        "U8" => "u8",
        "I128" => "i128",
        "Bool" => "bool",
        other => other,
    }
}

/// Convert a snake_case operation name to PascalCase for struct names.
pub fn to_pascal_case(s: &str) -> String {
    s.split('_')
        .map(|word| {
            let mut chars = word.chars();
            match chars.next() {
                None => String::new(),
                Some(c) => c.to_uppercase().to_string() + &chars.collect::<String>(),
            }
        })
        .collect()
}

/// Find the context for a given operation.
fn find_context<'a>(spec: &'a ParsedSpec, op_name: &str) -> Option<&'a ParsedContext> {
    spec.contexts.iter().find(|c| c.operation == op_name)
}

/// Check if any account in a context has a bump attribute.
fn context_has_bumps(ctx: &ParsedContext) -> bool {
    ctx.accounts.iter().any(|a| a.has_bump)
}

/// Generate #[account(...)] attribute string for a context entry.
fn gen_account_attr(entry: &ParsedAccountEntry, state_name: &str) -> String {
    let mut parts = Vec::new();

    if entry.is_mut {
        parts.push("mut".to_string());
    }
    if entry.is_init {
        parts.push("init".to_string());
    }
    if entry.is_init_if_needed {
        parts.push("init_if_needed".to_string());
    }
    if let Some(ref payer) = entry.payer {
        parts.push(format!("payer = {}", payer));
    }
    if let Some(ref seeds_ref) = entry.seeds_ref {
        // Use the Type::seeds(args) pattern
        parts.push(format!("seeds = {}::seeds({})", state_name, seeds_ref));
    }
    if entry.has_bump {
        parts.push("bump".to_string());
    }
    if let Some(ref close) = entry.close_target {
        parts.push(format!("close = {}", close));
    }
    if let Some(ref has_one) = entry.has_one {
        parts.push(format!("has_one = {}", has_one));
    }
    if let Some(ref mint) = entry.token_mint {
        parts.push(format!("token::mint = {}", mint));
    }
    if let Some(ref auth) = entry.token_authority {
        parts.push(format!("token::authority = {}", auth));
    }

    if parts.is_empty() {
        String::new()
    } else {
        format!("    #[account({})]\n", parts.join(", "))
    }
}

/// Generate the Quasar field type from a context entry.
fn gen_field_type(entry: &ParsedAccountEntry) -> String {
    match entry.account_type.as_str() {
        "Signer" => "Signer".to_string(),
        "Account" => {
            if let Some(ref inner) = entry.inner_type {
                format!("Account<{}>", inner)
            } else {
                "Account<()>".to_string()
            }
        }
        "Program" => {
            if let Some(ref inner) = entry.inner_type {
                format!("Program<{}>", inner)
            } else {
                "Program<()>".to_string()
            }
        }
        "Sysvar" => {
            if let Some(ref inner) = entry.inner_type {
                format!("Sysvar<{}>", inner)
            } else {
                "Sysvar<()>".to_string()
            }
        }
        other => other.to_string(),
    }
}

/// Format the "GENERATED BY QEDGEN" marker with an optional spec hash.
fn marker(label: &str, fp: &SpecFingerprint, file_key: &str) -> String {
    match fp.file_hashes.get(file_key) {
        Some(hash) => format!(
            "// ---- GENERATED BY QEDGEN — {} ---- spec-hash:{}\n",
            label, hash
        ),
        None => format!("// ---- GENERATED BY QEDGEN — {} ----\n", label),
    }
}

// ============================================================================
// File generators
// ============================================================================

/// Generate src/lib.rs
fn generate_lib(spec: &ParsedSpec, fp: &SpecFingerprint, output_dir: &Path) -> Result<()> {
    let src_dir = output_dir.join("src");
    std::fs::create_dir_all(&src_dir)?;

    let program_name = spec.program_name.to_lowercase();
    let program_id = spec
        .program_id
        .as_deref()
        .unwrap_or("11111111111111111111111111111111");

    let mut out = String::new();
    out.push_str(&marker("DO NOT EDIT", fp, "src/lib.rs"));
    out.push_str("#![no_std]\n\n");
    out.push_str("use quasar_lang::prelude::*;\n\n");
    out.push_str("mod instructions;\nuse instructions::*;\n");

    if !spec.events.is_empty() {
        out.push_str("pub mod events;\n");
    }
    if !spec.error_codes.is_empty() {
        out.push_str("pub mod errors;\n");
    }
    out.push_str("pub mod state;\n\n");

    out.push_str(&format!("declare_id!(\"{}\");\n\n", program_id));

    out.push_str("#[program]\n");
    out.push_str(&format!("mod {} {{\n", program_name));
    out.push_str("    use super::*;\n\n");

    for (i, op) in spec.operations.iter().enumerate() {
        let pascal = to_pascal_case(&op.name);
        let ctx = find_context(spec, &op.name);
        let has_bumps = ctx.is_some_and(context_has_bumps);

        // Doc comment
        if let Some(ref doc) = op.doc {
            out.push_str(&format!("    /// {}\n", doc));
        }
        out.push_str(&format!("    #[instruction(discriminator = {})]\n", i));

        // Build param list
        let mut params = String::from("ctx: Ctx<");
        params.push_str(&pascal);
        params.push('>');

        for (pname, ptype) in &op.takes_params {
            params.push_str(&format!(", {}: {}", pname, map_type(ptype)));
        }

        out.push_str(&format!(
            "    pub fn {}({}) -> Result<(), ProgramError> {{\n",
            op.name, params
        ));

        if has_bumps {
            out.push_str(&format!(
                "        ctx.accounts.handler({}&ctx.bumps)\n",
                op.takes_params
                    .iter()
                    .map(|(n, _)| format!("{}, ", n))
                    .collect::<String>()
            ));
        } else {
            out.push_str(&format!(
                "        ctx.accounts.handler({})\n",
                op.takes_params
                    .iter()
                    .map(|(n, _)| n.clone())
                    .collect::<Vec<_>>()
                    .join(", ")
            ));
        }
        out.push_str("    }\n\n");
    }

    out.push_str("}\n");
    out.push_str("// ---- END GENERATED ----\n");

    std::fs::write(src_dir.join("lib.rs"), &out)?;
    Ok(())
}

/// Generate src/state.rs
fn generate_state(spec: &ParsedSpec, fp: &SpecFingerprint, output_dir: &Path) -> Result<()> {
    let src_dir = output_dir.join("src");
    std::fs::create_dir_all(&src_dir)?;

    let is_multi = spec.account_types.len() > 1;

    let mut out = String::new();
    out.push_str(&marker("DO NOT EDIT", fp, "src/state.rs"));
    out.push_str("use quasar_lang::prelude::*;\n\n");

    if is_multi {
        // Multi-account: one struct + lifecycle enum per account type
        for (idx, acct) in spec.account_types.iter().enumerate() {
            let struct_name = format!("{}Account", acct.name);

            // Find matching PDA
            let pda_seeds = if let Some(ref pda_name) = acct.pda_ref {
                if let Some(pda) = spec.pdas.iter().find(|p| &p.name == pda_name) {
                    gen_pda_seeds_attr(pda, &acct.fields)
                } else {
                    String::new()
                }
            } else {
                String::new()
            };

            out.push_str(&format!(
                "#[account(discriminator = {}, set_inner)]\n{}pub struct {} {{\n",
                idx + 1,
                pda_seeds,
                struct_name
            ));

            for (fname, ftype) in &acct.fields {
                out.push_str(&format!("    pub {}: {},\n", fname, map_type(ftype)));
            }

            // Add bump field if PDA-derived
            if acct.pda_ref.is_some() && !acct.fields.iter().any(|(n, _)| n == "bump") {
                out.push_str("    pub bump: u8,\n");
            }

            out.push_str("}\n\n");

            // Per-account lifecycle enum
            if !acct.lifecycle.is_empty() {
                out.push_str(&format!("/// {} lifecycle states.\n", acct.name));
                out.push_str("#[derive(Clone, Copy, PartialEq, Eq)]\n");
                out.push_str("#[repr(u8)]\n");
                out.push_str(&format!("pub enum {}Status {{\n", acct.name));
                for (i, state) in acct.lifecycle.iter().enumerate() {
                    out.push_str(&format!("    {} = {},\n", state, i));
                }
                out.push_str("}\n\n");
            }
        }
    } else {
        // Single-account: original behavior
        let state_name = format!("{}Account", to_pascal_case(&spec.program_name));

        let pda_seeds = if !spec.pdas.is_empty() {
            gen_pda_seeds_attr(&spec.pdas[0], &spec.state_fields)
        } else {
            String::new()
        };

        out.push_str(&format!(
            "#[account(discriminator = 1, set_inner)]\n{}pub struct {} {{\n",
            pda_seeds, state_name
        ));

        for (fname, ftype) in &spec.state_fields {
            out.push_str(&format!("    pub {}: {},\n", fname, map_type(ftype)));
        }

        if !spec.pdas.is_empty() && !spec.state_fields.iter().any(|(n, _)| n == "bump") {
            out.push_str("    pub bump: u8,\n");
        }

        out.push_str("}\n");

        if !spec.lifecycle_states.is_empty() {
            out.push_str("\n/// Program lifecycle states.\n");
            out.push_str("#[derive(Clone, Copy, PartialEq, Eq)]\n");
            out.push_str("#[repr(u8)]\n");
            out.push_str("pub enum Status {\n");
            for (i, state) in spec.lifecycle_states.iter().enumerate() {
                out.push_str(&format!("    {} = {},\n", state, i));
            }
            out.push_str("}\n");
        }
    }

    out.push_str("// ---- END GENERATED ----\n");

    std::fs::write(src_dir.join("state.rs"), &out)?;
    Ok(())
}

/// Generate PDA seeds attribute for a PDA declaration.
fn gen_pda_seeds_attr(pda: &crate::check::ParsedPda, fields: &[(String, String)]) -> String {
    let mut seed_parts = Vec::new();
    for seed in &pda.seeds {
        let trimmed = seed.trim_matches('"');
        if seed.starts_with('"') || seed.starts_with('\"') {
            seed_parts.push(format!("b\"{}\"", trimmed));
        } else {
            let field_type = fields
                .iter()
                .find(|(n, _)| n == trimmed)
                .map(|(_, t)| map_type(t))
                .unwrap_or("Address");
            seed_parts.push(format!("{}: {}", trimmed, field_type));
        }
    }
    format!("#[seeds({})]\n", seed_parts.join(", "))
}

/// Generate src/events.rs (only if events are declared)
fn generate_events(spec: &ParsedSpec, fp: &SpecFingerprint, output_dir: &Path) -> Result<()> {
    if spec.events.is_empty() {
        return Ok(());
    }

    let src_dir = output_dir.join("src");
    std::fs::create_dir_all(&src_dir)?;

    let mut out = String::new();
    out.push_str(&marker("DO NOT EDIT", fp, "src/events.rs"));
    out.push_str("use quasar_lang::prelude::*;\n\n");

    for (i, event) in spec.events.iter().enumerate() {
        out.push_str(&format!("#[event(discriminator = {})]\n", i + 1));
        out.push_str(&format!("pub struct {} {{\n", event.name));
        for (fname, ftype) in &event.fields {
            out.push_str(&format!("    pub {}: {},\n", fname, map_type(ftype)));
        }
        out.push_str("}\n\n");
    }

    out.push_str("// ---- END GENERATED ----\n");

    std::fs::write(src_dir.join("events.rs"), &out)?;
    Ok(())
}

/// Generate src/errors.rs (only if error codes are declared)
fn generate_errors(spec: &ParsedSpec, fp: &SpecFingerprint, output_dir: &Path) -> Result<()> {
    if spec.error_codes.is_empty() {
        return Ok(());
    }

    let src_dir = output_dir.join("src");
    std::fs::create_dir_all(&src_dir)?;

    let error_name = format!("{}Error", to_pascal_case(&spec.program_name));

    let mut out = String::new();
    out.push_str(&marker("DO NOT EDIT", fp, "src/errors.rs"));
    out.push_str("use quasar_lang::prelude::*;\n\n");

    out.push_str("#[error_code]\n");
    out.push_str(&format!("pub enum {} {{\n", error_name));
    for (i, code) in spec.error_codes.iter().enumerate() {
        out.push_str(&format!("    {} = {},\n", code, i));
    }
    out.push_str("}\n");
    out.push_str("// ---- END GENERATED ----\n");

    std::fs::write(src_dir.join("errors.rs"), &out)?;
    Ok(())
}

/// Generate src/instructions/mod.rs and per-operation files.
fn generate_instructions(spec: &ParsedSpec, fp: &SpecFingerprint, output_dir: &Path) -> Result<()> {
    let instr_dir = output_dir.join("src").join("instructions");
    std::fs::create_dir_all(&instr_dir)?;

    let is_multi = spec.account_types.len() > 1;
    let default_state_name = format!("{}Account", to_pascal_case(&spec.program_name));

    // mod.rs
    let mut mod_out = String::new();
    mod_out.push_str(&marker("DO NOT EDIT", fp, "src/instructions/mod.rs"));
    for op in &spec.operations {
        mod_out.push_str(&format!("pub mod {};\n", op.name));
    }
    mod_out.push('\n');
    for op in &spec.operations {
        let pascal = to_pascal_case(&op.name);
        mod_out.push_str(&format!("pub use {}::{};\n", op.name, pascal));
    }
    mod_out.push_str("// ---- END GENERATED ----\n");
    std::fs::write(instr_dir.join("mod.rs"), &mod_out)?;

    // Per-operation instruction files
    for op in &spec.operations {
        let pascal = to_pascal_case(&op.name);
        let ctx = find_context(spec, &op.name);
        let has_bumps = ctx.is_some_and(context_has_bumps);
        let bumps_name = format!("{}Bumps", pascal);
        let any_mut = ctx.is_some_and(|c| c.accounts.iter().any(|a| a.is_mut));

        let mut out = String::new();
        let file_key = format!("src/instructions/{}.rs", op.name);
        out.push_str(&marker("DO NOT EDIT ABOVE THIS LINE", fp, &file_key));
        out.push_str("use quasar_lang::prelude::*;\n");
        out.push_str("use crate::state::*;\n");
        if !spec.events.is_empty() && !op.emits.is_empty() {
            out.push_str("use crate::events::*;\n");
        }
        if !spec.error_codes.is_empty() {
            out.push_str("use crate::errors::*;\n");
        }
        out.push('\n');

        // #[derive(Accounts)] struct
        out.push_str("#[derive(Accounts)]\n");
        out.push_str(&format!("pub struct {} {{\n", pascal));

        if let Some(ctx) = ctx {
            for entry in &ctx.accounts {
                // Determine which state struct this account references
                let acct_state_name = if is_multi {
                    // For multi-account, use the inner type name + "Account"
                    entry
                        .inner_type
                        .as_ref()
                        .map(|t| format!("{}Account", t))
                        .unwrap_or_else(|| default_state_name.clone())
                } else {
                    default_state_name.clone()
                };
                let attr = gen_account_attr(entry, &acct_state_name);
                let field_type = gen_field_type(entry);
                out.push_str(&format!(
                    "{}    pub {}: {},\n",
                    attr, entry.name, field_type
                ));
            }
        } else {
            // No context: generate minimal accounts (signer if who: specified)
            if op.who.is_some() {
                out.push_str("    pub signer: Signer,\n");
            }
        }

        out.push_str("}\n\n");

        // impl block with handler
        out.push_str(&format!("impl {} {{\n", pascal));

        // Doc comment
        if let Some(ref doc) = op.doc {
            out.push_str(&format!("    /// {}\n", doc));
        }

        out.push_str("    #[inline(always)]\n");

        // Handler signature
        let self_ref = if any_mut { "&mut self" } else { "&self" };
        let mut handler_params = vec![self_ref.to_string()];
        for (pname, ptype) in &op.takes_params {
            handler_params.push(format!("{}: {}", pname, map_type(ptype)));
        }
        if has_bumps {
            handler_params.push(format!("bumps: &{}", bumps_name));
        }

        out.push_str(&format!(
            "    pub fn handler({}) -> Result<(), ProgramError> {{\n",
            handler_params.join(", ")
        ));

        // AGENT hook body
        out.push_str("        // AGENT: implement business logic here\n");

        if let Some(ref guard) = op.guard_str {
            out.push_str(&format!("        // Spec guard: \"{}\"\n", guard));
        }
        for (field, op_kind, value) in &op.effects {
            out.push_str(&format!(
                "        // Spec effect: {} {} {}\n",
                field, op_kind, value
            ));
        }
        for emit in &op.emits {
            out.push_str(&format!("        // Spec: emit!({})\n", emit));
        }

        out.push_str("        todo!()\n");
        out.push_str("    }\n");
        out.push_str("}\n");
        out.push_str("// ---- GENERATED BY QEDGEN — DO NOT EDIT BELOW THIS LINE ----\n");

        std::fs::write(instr_dir.join(format!("{}.rs", op.name)), &out)?;
    }

    Ok(())
}

/// Generate Cargo.toml
fn generate_cargo_toml(spec: &ParsedSpec, fp: &SpecFingerprint, output_dir: &Path) -> Result<()> {
    let program_name = spec.program_name.to_lowercase().replace('_', "-");

    // Detect if SPL Token is needed (any account uses Token/Mint types)
    let needs_spl = spec.contexts.iter().any(|ctx| {
        ctx.accounts.iter().any(|a| {
            a.inner_type
                .as_ref()
                .is_some_and(|t| t == "Token" || t == "Mint")
        })
    });

    let hash = fp
        .file_hashes
        .get("Cargo.toml")
        .cloned()
        .unwrap_or_default();

    let mut out = String::new();
    out.push_str(&format!(
        "# ---- GENERATED BY QEDGEN ---- spec-hash:{}\n",
        hash
    ));
    out.push_str(&format!(
        r#"[package]
name = "{}"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[features]
client = []
debug = []

[dependencies]
quasar-lang = {{ version = "0.1" }}
"#,
        program_name
    ));

    if needs_spl {
        out.push_str("quasar-spl = { version = \"0.1\" }\n");
    }

    std::fs::write(output_dir.join("Cargo.toml"), &out)?;
    Ok(())
}

// ============================================================================
// Public API
// ============================================================================

/// Generate a Quasar program skeleton from a spec file (.lean or .qedspec).
pub fn generate(spec_path: &Path, output_dir: &Path) -> Result<()> {
    let spec = check::parse_spec_file(spec_path)?;

    if spec.operations.is_empty() {
        anyhow::bail!(
            "No operations found in {}. Is this a valid qedspec file?",
            spec_path.display()
        );
    }

    std::fs::create_dir_all(output_dir)?;

    let fp = crate::fingerprint::compute_fingerprint(&spec);

    generate_lib(&spec, &fp, output_dir)?;
    generate_state(&spec, &fp, output_dir)?;
    generate_events(&spec, &fp, output_dir)?;
    generate_errors(&spec, &fp, output_dir)?;
    generate_instructions(&spec, &fp, output_dir)?;
    generate_cargo_toml(&spec, &fp, output_dir)?;

    let file_count = 4 + spec.operations.len() // lib, state, mod.rs, Cargo.toml + per-op files
        + if spec.events.is_empty() { 0 } else { 1 }
        + if spec.error_codes.is_empty() { 0 } else { 1 };

    eprintln!("Generated {} files in {}", file_count, output_dir.display());
    eprintln!("  src/lib.rs              — program entry point");
    eprintln!("  src/state.rs            — account state struct");
    if !spec.events.is_empty() {
        eprintln!("  src/events.rs           — event structs");
    }
    if !spec.error_codes.is_empty() {
        eprintln!("  src/errors.rs           — error codes");
    }
    eprintln!("  src/instructions/mod.rs — instruction exports");
    for op in &spec.operations {
        eprintln!(
            "  src/instructions/{}.rs — {} handler (AGENT fills todo!())",
            op.name, op.name
        );
    }
    eprintln!("  Cargo.toml              — project manifest");

    Ok(())
}
