use anyhow::Result;
use std::path::Path;

use crate::check::{self, ParsedHandler, ParsedSpec};
use crate::fingerprint::SpecFingerprint;
use crate::spec_hash;

/// Compute a path, as a string, from a program `Cargo.toml` directory to the
/// spec file. This value is embedded verbatim in the `#[qed(spec = "...")]`
/// attribute and resolved at compile time relative to `CARGO_MANIFEST_DIR`.
///
/// Best-effort: if the spec isn't under a path we can express relatively,
/// fall back to the absolute path (works as long as the repo doesn't move).
fn relative_spec_path(spec_path: &Path, manifest_dir: &Path) -> String {
    // Canonicalize both; fall back to the raw paths on failure.
    let spec = spec_path
        .canonicalize()
        .unwrap_or_else(|_| spec_path.to_path_buf());
    let manifest = manifest_dir
        .canonicalize()
        .unwrap_or_else(|_| manifest_dir.to_path_buf());
    let spec_components: Vec<_> = spec.components().collect();
    let manifest_components: Vec<_> = manifest.components().collect();

    // Find common prefix length.
    let common = spec_components
        .iter()
        .zip(manifest_components.iter())
        .take_while(|(a, b)| a == b)
        .count();

    let mut out = std::path::PathBuf::new();
    for _ in 0..(manifest_components.len().saturating_sub(common)) {
        out.push("..");
    }
    for comp in &spec_components[common..] {
        out.push(comp.as_os_str());
    }
    if out.as_os_str().is_empty() {
        spec.display().to_string()
    } else {
        out.to_string_lossy().replace('\\', "/")
    }
}

/// Map a DSL primitive type name to its Rust type.
///
/// Returns an error for unrecognized types rather than silently passing them
/// through — a fall-through was the root cause of the v2.6.1 codegen-bug
/// class where types like `U16` or compound types like `Map[N] T` leaked
/// verbatim into generated Rust (see docs/prds/PRD-v2.6.2.md G1).
///
/// Compound types (`Map[N] T`, sum types) are handled by their own renderers
/// — this function is the primitive-level translator only.
pub fn map_type(dsl_type: &str) -> Result<String> {
    let rust = match dsl_type {
        "Pubkey" => "Address",
        "U8" => "u8",
        "U16" => "u16",
        "U32" => "u32",
        "U64" => "u64",
        "U128" => "u128",
        "I8" => "i8",
        "I16" => "i16",
        "I32" => "i32",
        "I64" => "i64",
        "I128" => "i128",
        "Bool" => "bool",
        other => {
            anyhow::bail!(
                "unsupported DSL type `{}` — expected a primitive (U8/U16/U32/U64/U128, I8/I16/I32/I64/I128, Bool, Pubkey) or a compound type handled by its own renderer (Map[N] T, sum variant)",
                other
            );
        }
    };
    Ok(rust.to_string())
}

/// Convert a snake_case operation name to PascalCase for struct names.
pub fn to_pascal_case(s: &str) -> String {
    s.split('_')
        .map(|word| {
            let mut chars = word.chars();
            match chars.next() {
                None => String::new(),
                Some(c) => c.to_uppercase().to_string() + &chars.collect::<String>(),
            }
        })
        .collect()
}

/// Format the "GENERATED BY QEDGEN" marker with the per-file spec hash.
/// Thin wrapper around `crate::banner::banner` that resolves the hash from
/// the fingerprint table by file_key.
fn marker(label: &str, fp: &SpecFingerprint, file_key: &str) -> String {
    let hash = fp
        .file_hashes
        .get(file_key)
        .map(String::as_str)
        .unwrap_or("");
    crate::banner::banner(Some(label), hash)
}

// ============================================================================
// File generators
// ============================================================================

/// Generate src/lib.rs. Skip if the file already exists — once the user has
/// stamped custom imports or extra modules onto the crate shell, regenerating
/// it would silently clobber that edit. Paired with the per-handler
/// `instructions/<name>.rs` skip, this keeps `qedgen codegen` idempotent.
fn generate_lib(spec: &ParsedSpec, fp: &SpecFingerprint, output_dir: &Path) -> Result<()> {
    let src_dir = output_dir.join("src");
    std::fs::create_dir_all(&src_dir)?;

    let lib_path = src_dir.join("lib.rs");
    if lib_path.exists() {
        eprintln!(
            "programs/{}/src/lib.rs already exists — skipping (user-owned). guards.rs regenerated.",
            output_dir
                .file_name()
                .and_then(|n| n.to_str())
                .unwrap_or("<program>")
        );
        return Ok(());
    }

    let program_name = spec.program_name.to_lowercase();
    let program_id = spec
        .program_id
        .as_deref()
        .unwrap_or("11111111111111111111111111111111");

    let mut out = String::new();
    out.push_str(&marker("DO NOT EDIT", fp, "src/lib.rs"));
    out.push_str("#![no_std]\n\n");
    out.push_str("use anchor_lang::prelude::*;\n\n");
    out.push_str("mod instructions;\nuse instructions::*;\n");

    if !spec.events.is_empty() {
        out.push_str("pub mod events;\n");
    }
    if !spec.error_codes.is_empty() {
        out.push_str("pub mod errors;\n");
    }
    out.push_str("pub mod state;\n");
    out.push_str("pub mod guards;\n\n");

    out.push_str(&format!("declare_id!(\"{}\");\n\n", program_id));

    out.push_str("#[program]\n");
    out.push_str(&format!("mod {} {{\n", program_name));
    out.push_str("    use super::*;\n\n");

    for (i, handler) in spec.handlers.iter().enumerate() {
        let pascal = to_pascal_case(&handler.name);

        if let Some(ref doc) = handler.doc {
            out.push_str(&format!("    /// {}\n", doc));
        }
        out.push_str(&format!("    #[instruction(discriminator = {})]\n", i));

        let mut params = String::from("ctx: Ctx<");
        params.push_str(&pascal);
        params.push('>');

        for (pname, ptype) in &handler.takes_params {
            params.push_str(&format!(", {}: {}", pname, map_type(ptype)?));
        }

        out.push_str(&format!(
            "    pub fn {}({}) -> Result<(), ProgramError> {{\n",
            handler.name, params
        ));

        if handler.has_bumps() {
            out.push_str(&format!(
                "        ctx.accounts.handler({}&ctx.bumps)\n",
                handler
                    .takes_params
                    .iter()
                    .map(|(n, _)| format!("{}, ", n))
                    .collect::<String>()
            ));
        } else {
            out.push_str(&format!(
                "        ctx.accounts.handler({})\n",
                handler
                    .takes_params
                    .iter()
                    .map(|(n, _)| n.clone())
                    .collect::<Vec<_>>()
                    .join(", ")
            ));
        }
        out.push_str("    }\n\n");
    }

    out.push_str("}\n");
    out.push_str("// ---- END GENERATED ----\n");

    std::fs::write(src_dir.join("lib.rs"), &out)?;
    Ok(())
}

/// Generate src/state.rs
fn generate_state(spec: &ParsedSpec, fp: &SpecFingerprint, output_dir: &Path) -> Result<()> {
    let src_dir = output_dir.join("src");
    std::fs::create_dir_all(&src_dir)?;

    let is_multi = spec.account_types.len() > 1;

    let mut out = String::new();
    out.push_str(&marker("DO NOT EDIT", fp, "src/state.rs"));
    out.push_str("use anchor_lang::prelude::*;\n\n");

    if is_multi {
        for (idx, acct) in spec.account_types.iter().enumerate() {
            let struct_name = format!("{}Account", acct.name);

            let pda_seeds = if let Some(ref pda_name) = acct.pda_ref {
                if let Some(pda) = spec.pdas.iter().find(|p| &p.name == pda_name) {
                    gen_pda_seeds_attr(pda, &acct.fields)?
                } else {
                    String::new()
                }
            } else {
                String::new()
            };

            out.push_str(&format!(
                "#[account(discriminator = {}, set_inner)]\n{}pub struct {} {{\n",
                idx + 1,
                pda_seeds,
                struct_name
            ));

            for (fname, ftype) in &acct.fields {
                out.push_str(&format!("    pub {}: {},\n", fname, map_type(ftype)?));
            }

            if acct.pda_ref.is_some() && !acct.fields.iter().any(|(n, _)| n == "bump") {
                out.push_str("    pub bump: u8,\n");
            }

            out.push_str("}\n\n");

            if !acct.lifecycle.is_empty() {
                out.push_str(&format!("/// {} lifecycle states.\n", acct.name));
                out.push_str("#[derive(Clone, Copy, PartialEq, Eq)]\n");
                out.push_str("#[repr(u8)]\n");
                out.push_str(&format!("pub enum {}Status {{\n", acct.name));
                for (i, state) in acct.lifecycle.iter().enumerate() {
                    out.push_str(&format!("    {} = {},\n", state, i));
                }
                out.push_str("}\n\n");
            }
        }
    } else {
        let state_name = format!("{}Account", to_pascal_case(&spec.program_name));

        let pda_seeds = if !spec.pdas.is_empty() {
            gen_pda_seeds_attr(&spec.pdas[0], &spec.state_fields)?
        } else {
            String::new()
        };

        out.push_str(&format!(
            "#[account(discriminator = 1, set_inner)]\n{}pub struct {} {{\n",
            pda_seeds, state_name
        ));

        for (fname, ftype) in &spec.state_fields {
            out.push_str(&format!("    pub {}: {},\n", fname, map_type(ftype)?));
        }

        if !spec.pdas.is_empty() && !spec.state_fields.iter().any(|(n, _)| n == "bump") {
            out.push_str("    pub bump: u8,\n");
        }

        out.push_str("}\n");

        if !spec.lifecycle_states.is_empty() {
            out.push_str("\n/// Program lifecycle states.\n");
            out.push_str("#[derive(Clone, Copy, PartialEq, Eq)]\n");
            out.push_str("#[repr(u8)]\n");
            out.push_str("pub enum Status {\n");
            for (i, state) in spec.lifecycle_states.iter().enumerate() {
                out.push_str(&format!("    {} = {},\n", state, i));
            }
            out.push_str("}\n");
        }
    }

    out.push_str("// ---- END GENERATED ----\n");

    std::fs::write(src_dir.join("state.rs"), &out)?;
    Ok(())
}

/// Generate PDA seeds attribute for a PDA declaration.
fn gen_pda_seeds_attr(
    pda: &crate::check::ParsedPda,
    fields: &[(String, String)],
) -> Result<String> {
    let mut seed_parts = Vec::new();
    for seed in &pda.seeds {
        let trimmed = seed.trim_matches('"');
        if seed.starts_with('"') || seed.starts_with('\"') {
            seed_parts.push(format!("b\"{}\"", trimmed));
        } else {
            let field_type = match fields.iter().find(|(n, _)| n == trimmed) {
                Some((_, t)) => map_type(t)?,
                None => "Address".to_string(),
            };
            seed_parts.push(format!("{}: {}", trimmed, field_type));
        }
    }
    Ok(format!("#[seeds({})]\n", seed_parts.join(", ")))
}

/// Generate src/events.rs (only if events are declared)
fn generate_events(spec: &ParsedSpec, fp: &SpecFingerprint, output_dir: &Path) -> Result<()> {
    if spec.events.is_empty() {
        return Ok(());
    }

    let src_dir = output_dir.join("src");
    std::fs::create_dir_all(&src_dir)?;

    let mut out = String::new();
    out.push_str(&marker("DO NOT EDIT", fp, "src/events.rs"));
    out.push_str("use anchor_lang::prelude::*;\n\n");

    for (i, event) in spec.events.iter().enumerate() {
        out.push_str(&format!("#[event(discriminator = {})]\n", i + 1));
        out.push_str(&format!("pub struct {} {{\n", event.name));
        for (fname, ftype) in &event.fields {
            out.push_str(&format!("    pub {}: {},\n", fname, map_type(ftype)?));
        }
        out.push_str("}\n\n");
    }

    out.push_str("// ---- END GENERATED ----\n");

    std::fs::write(src_dir.join("events.rs"), &out)?;
    Ok(())
}

/// Generate src/errors.rs (only if error codes are declared)
fn generate_errors(spec: &ParsedSpec, fp: &SpecFingerprint, output_dir: &Path) -> Result<()> {
    if spec.error_codes.is_empty() {
        return Ok(());
    }

    let src_dir = output_dir.join("src");
    std::fs::create_dir_all(&src_dir)?;

    let error_name = format!("{}Error", to_pascal_case(&spec.program_name));

    let mut out = String::new();
    out.push_str(&marker("DO NOT EDIT", fp, "src/errors.rs"));
    out.push_str("use anchor_lang::prelude::*;\n\n");

    out.push_str("#[error_code]\n");
    out.push_str(&format!("pub enum {} {{\n", error_name));
    for (i, code) in spec.error_codes.iter().enumerate() {
        out.push_str(&format!("    {} = {},\n", code, i));
    }
    out.push_str("}\n");
    out.push_str("// ---- END GENERATED ----\n");

    std::fs::write(src_dir.join("errors.rs"), &out)?;
    Ok(())
}

/// Generate src/instructions/mod.rs and per-handler files.
///
/// `mod.rs` is always regenerated (pure scaffold: `pub mod` declarations).
/// Per-handler `src/instructions/<name>.rs` files are USER-OWNED: emitted
/// only when missing. Each scaffolded handler body calls
/// `crate::guards::<name>(...)?` then falls through to `todo!()` for the
/// agent to fill in business logic. The `#[qed(verified, spec, handler,
/// hash, spec_hash)]` attribute ties the body and the spec contract
/// together at compile time.
fn generate_instructions(
    spec: &ParsedSpec,
    fp: &SpecFingerprint,
    spec_path: &Path,
    output_dir: &Path,
) -> Result<()> {
    let instr_dir = output_dir.join("src").join("instructions");
    std::fs::create_dir_all(&instr_dir)?;

    let is_multi = spec.account_types.len() > 1;
    let default_state_name = format!("{}Account", to_pascal_case(&spec.program_name));

    // mod.rs — always regenerated, pure scaffold.
    let mut mod_out = String::new();
    mod_out.push_str(&marker("DO NOT EDIT", fp, "src/instructions/mod.rs"));
    for handler in &spec.handlers {
        mod_out.push_str(&format!("pub mod {};\n", handler.name));
    }
    mod_out.push('\n');
    for handler in &spec.handlers {
        let pascal = to_pascal_case(&handler.name);
        mod_out.push_str(&format!("pub use {}::{};\n", handler.name, pascal));
    }
    mod_out.push_str("// ---- END GENERATED ----\n");
    std::fs::write(instr_dir.join("mod.rs"), &mod_out)?;

    // Read spec source once — used for spec_hash attributes.
    // `read_spec_source` handles both single-file and multi-file (directory)
    // specs, concatenating fragments in the same order the loader merges them.
    let spec_src = crate::check::read_spec_source(spec_path).unwrap_or_default();
    let spec_attr = relative_spec_path(spec_path, output_dir);

    // Per-handler instruction files — skip if existing (user-owned).
    for handler in &spec.handlers {
        let handler_path = instr_dir.join(format!("{}.rs", handler.name));
        if handler_path.exists() {
            eprintln!(
                "programs/{}/src/instructions/{}.rs already exists — skipping (user-owned). guards.rs regenerated.",
                output_dir.file_name().and_then(|n| n.to_str()).unwrap_or("<program>"),
                handler.name
            );
            continue;
        }

        let out = render_handler_scaffold(
            handler,
            spec,
            is_multi,
            &default_state_name,
            &spec_src,
            &spec_attr,
        )?;
        std::fs::write(&handler_path, &out)?;
    }

    Ok(())
}

/// Render the initial scaffold for a single user-owned handler file.
/// Identify the writable state-holding account in a handler. A handler's
/// accounts include user signers, token/mint accounts, programs, and
/// PDA-derived state holders; only the last category can receive a `self.X.field = ...`
/// effect expansion. Returns None when the handler has zero or multiple
/// plausible state accounts — in which case the caller must fall back to
/// `todo!()` and let a human (or M4 agent) disambiguate.
fn find_state_account(handler: &ParsedHandler) -> Option<&crate::check::ParsedHandlerAccount> {
    let mut candidates: Vec<&crate::check::ParsedHandlerAccount> = handler
        .accounts
        .iter()
        .filter(|a| a.is_writable && !a.is_signer && !a.is_program)
        .filter(|a| {
            // Drop token/mint accounts — they hold balances, not program state.
            !matches!(a.account_type.as_deref(), Some("token") | Some("mint"))
        })
        .collect();

    // Prefer PDA-derived candidates when available.
    let pda_candidates: Vec<_> = candidates
        .iter()
        .copied()
        .filter(|a| a.pda_seeds.is_some())
        .collect();
    if !pda_candidates.is_empty() {
        candidates = pda_candidates;
    }

    if candidates.len() == 1 {
        Some(candidates[0])
    } else {
        None
    }
}

/// Try to translate a single effect tuple to a real Rust statement. Returns
/// None when the RHS is too complex for mechanical expansion (match/arith/
/// pre-rendered Lean form); the caller falls through to a `todo!()` so an
/// LLM or human fills the body.
fn mechanize_effect(
    effect: &(String, String, String),
    state_acct: &crate::check::ParsedHandlerAccount,
    handler: &ParsedHandler,
    spec: &ParsedSpec,
) -> Option<String> {
    let (field, op_kind, value) = effect;

    // Refuse complex RHS. `render_effect` pre-renders match/record/arith into
    // Lean string form; those start looking nothing like Rust identifiers.
    // A simple param / literal / constant is what's always safe.
    let simple_rhs = value
        .chars()
        .all(|c| c.is_alphanumeric() || c == '_' || c == '-');
    if !simple_rhs {
        return None;
    }

    let rhs = crate::rust_codegen_util::resolve_value(value, handler, spec);
    let acct = &state_acct.name;
    let line = match op_kind.as_str() {
        "set" => format!("        self.{}.{} = {};\n", acct, field, rhs),
        "add" => format!(
            "        self.{}.{} = self.{}.{}.wrapping_add({});\n",
            acct, field, acct, field, rhs
        ),
        "sub" => format!(
            "        self.{}.{} = self.{}.{}.wrapping_sub({});\n",
            acct, field, acct, field, rhs
        ),
        _ => return None,
    };
    Some(line)
}

fn render_handler_scaffold(
    handler: &ParsedHandler,
    spec: &ParsedSpec,
    is_multi: bool,
    default_state_name: &str,
    spec_src: &str,
    spec_attr: &str,
) -> Result<String> {
    let pascal = to_pascal_case(&handler.name);
    let bumps_name = format!("{}Bumps", pascal);
    let any_mut = handler.accounts.iter().any(|a| a.is_writable);

    let mut out = String::new();
    out.push_str("// User-owned. Regenerating the spec does NOT overwrite this file.\n");
    out.push_str("// Guard checks live in the sibling `crate::guards` module and ARE\n");
    out.push_str("// regenerated on every `qedgen codegen`. Drift between the spec\n");
    out.push_str("// handler block and the `spec_hash` below fires a compile_error!\n");
    out.push_str("// via the `#[qed(verified, ...)]` macro.\n\n");
    out.push_str("use anchor_lang::prelude::*;\n");
    out.push_str("use crate::state::*;\n");
    out.push_str("use crate::guards;\n");
    out.push_str("use qedgen_macros::qed;\n");
    if !spec.events.is_empty() && !handler.emits.is_empty() {
        out.push_str("use crate::events::*;\n");
    }
    if !spec.error_codes.is_empty() {
        out.push_str("use crate::errors::*;\n");
    }
    out.push('\n');

    // #[derive(Accounts)] struct
    out.push_str("#[derive(Accounts)]\n");
    out.push_str(&format!("pub struct {} {{\n", pascal));

    if !handler.accounts.is_empty() {
        for acct in &handler.accounts {
            let state_name = if is_multi {
                infer_state_name(acct, spec, default_state_name)
            } else {
                default_state_name.to_string()
            };
            let attr = acct.quasar_account_attr(handler, &state_name);
            let field_type = acct.quasar_field_type();
            out.push_str(&format!("{}    pub {}: {},\n", attr, acct.name, field_type));
        }
    } else if handler.who.is_some() {
        out.push_str("    pub signer: Signer,\n");
    }

    out.push_str("}\n\n");

    // impl block with handler
    out.push_str(&format!("impl {} {{\n", pascal));
    if let Some(ref doc) = handler.doc {
        out.push_str(&format!("    /// {}\n", doc));
    }

    // Emit the spec-bound #[qed(...)] attribute. Hashes are empty on first
    // scaffold — the macro errors with the computed values for copy-paste.
    let spec_h = spec_hash::spec_hash_for_handler(spec_src, &handler.name).unwrap_or_default();
    out.push_str(&format!(
        "    #[qed(verified, spec = \"{}\", handler = \"{}\", spec_hash = \"{}\")]\n",
        spec_attr, handler.name, spec_h
    ));

    out.push_str("    #[inline(always)]\n");

    let self_ref = if any_mut { "&mut self" } else { "&self" };
    let mut handler_params = vec![self_ref.to_string()];
    let mut param_names: Vec<String> = Vec::new();
    for (pname, ptype) in &handler.takes_params {
        handler_params.push(format!("{}: {}", pname, map_type(ptype)?));
        param_names.push(pname.clone());
    }
    if handler.has_bumps() {
        handler_params.push(format!("bumps: &{}", bumps_name));
    }

    out.push_str(&format!(
        "    pub fn handler({}) -> Result<(), ProgramError> {{\n",
        handler_params.join(", ")
    ));

    // Call the always-regenerated guards module. Signature: takes `&Self`
    // plus every handler-level parameter, returns `Result<(), ProgramError>`.
    let guard_args = if param_names.is_empty() {
        "self".to_string()
    } else {
        format!("self, {}", param_names.join(", "))
    };
    out.push_str(&format!(
        "        guards::{}({})?;\n",
        handler.name, guard_args
    ));

    // Spec-level `let` bindings (e.g. `let total_fee = amount * 125 / 10000`)
    // must be emitted BEFORE the effect block — effect RHSs reference them.
    // Pre-fix: they were dropped on the Rust side, leaving undefined-variable
    // errors on `cargo build`.
    for (binding_name, _lean_expr, rust_expr) in &handler.let_bindings {
        out.push_str(&format!("        let {} = {};\n", binding_name, rust_expr));
    }

    // Mechanical-effect expansion (v2.4-M3). For each spec effect we try to
    // emit a real Rust statement; anything non-mechanical stays as a comment
    // and forces a trailing `todo!()` so the user / an LLM (M4) fills it in.
    let state_acct = find_state_account(handler);
    let mut any_unmechanized = false;
    for effect in &handler.effects {
        let mechanized = state_acct.and_then(|sa| mechanize_effect(effect, sa, handler, spec));
        match mechanized {
            Some(line) => out.push_str(&line),
            None => {
                let (field, op_kind, value) = effect;
                out.push_str(&format!(
                    "        // Spec effect (needs fill): {} {} {}\n",
                    field, op_kind, value
                ));
                any_unmechanized = true;
            }
        }
    }

    // Events are always agent-fill for now (M4): the spec declares the event
    // name but not the payload binding.
    for emit in &handler.emits {
        out.push_str(&format!("        // Spec: emit!({})\n", emit));
    }
    let has_events = !handler.emits.is_empty();

    // Token transfers (CPI calls) are also agent-fill: building the CPI
    // context from the handler accounts is mechanical-ish but involves
    // framework-specific helpers that differ per Quasar/Anchor/raw.
    let has_transfers = !handler.transfers.is_empty();
    for t in &handler.transfers {
        out.push_str(&format!(
            "        // Spec transfer: {} -> {} amount={}\n",
            t.from,
            t.to,
            t.amount.as_deref().unwrap_or("?")
        ));
    }

    // `call Interface.handler(name = expr, ...)` sites — the uniform CPI
    // surface introduced in v2.5 (slice 2). For MVP this follows the same
    // agent-fill shape as `transfers { }`: emit a structured comment so the
    // prompt in fill.rs has everything it needs to generate a correct CPI
    // envelope. Real codegen from a resolved interface lands in v2.6 once
    // `import` is in play (see docs/design/spec-composition.md §2).
    let has_calls = !handler.calls.is_empty();
    for c in &handler.calls {
        let args = c
            .args
            .iter()
            .map(|a| format!("{}={}", a.name, a.rust_expr))
            .collect::<Vec<_>>()
            .join(", ");
        out.push_str(&format!(
            "        // Spec call: {}.{}({})\n",
            c.target_interface, c.target_handler, args
        ));
    }

    let needs_fill = any_unmechanized || has_events || has_transfers || has_calls;
    if needs_fill {
        out.push_str("        todo!(\"fill non-mechanical effects, events, transfers, calls\")\n");
    } else {
        out.push_str("        Ok(())\n");
    }
    out.push_str("    }\n");
    out.push_str("}\n");
    Ok(out)
}

/// Generate src/guards.rs — one function per handler containing all the
/// spec-declared guard checks. This file is always regenerated; any edit
/// is clobbered on the next `qedgen codegen` (by design).
fn generate_guards(spec: &ParsedSpec, fp: &SpecFingerprint, output_dir: &Path) -> Result<()> {
    let src_dir = output_dir.join("src");
    std::fs::create_dir_all(&src_dir)?;

    let mut out = String::new();
    out.push_str(&marker(
        "DO NOT EDIT — regenerated from .qedspec",
        fp,
        "src/guards.rs",
    ));
    out.push_str("//! Per-handler guard checks derived from the `.qedspec`.\n");
    out.push_str("//! Called from user-owned `instructions/<name>::handler` before\n");
    out.push_str("//! business logic; keep guard logic here, policy-free logic there.\n\n");
    out.push_str(
        "#![allow(unused_variables, unused_imports, dead_code, clippy::too_many_arguments)]\n\n",
    );
    out.push_str("use anchor_lang::prelude::*;\n");
    if !spec.error_codes.is_empty() {
        out.push_str("use crate::errors::*;\n");
    }
    out.push_str("use crate::instructions::*;\n\n");

    for handler in &spec.handlers {
        let pascal = to_pascal_case(&handler.name);
        let any_mut = handler.accounts.iter().any(|a| a.is_writable);
        let self_ref = if any_mut { "&mut " } else { "&" };
        let mut params = vec![format!("ctx: {}{}", self_ref, pascal)];
        for (pname, ptype) in &handler.takes_params {
            params.push(format!("{}: {}", pname, map_type(ptype)?));
        }
        out.push_str(&format!(
            "/// Guards for `{}`.  \n/// Generated from the `requires` clauses of the spec handler block.\n",
            handler.name
        ));
        out.push_str(&format!(
            "pub fn {}({}) -> Result<(), ProgramError> {{\n",
            handler.name,
            params.join(", ")
        ));

        if handler.requires.is_empty() && handler.aborts_if.is_empty() {
            out.push_str("    // No guards declared in spec — nothing to check.\n");
        }

        for req in &handler.requires {
            // Emit as a comment for human readers + an executable check.
            // The Rust expression comes directly from the spec; callers are
            // expected to bring the identifiers in scope (typically via
            // `ctx.<account>.<field>` style access).
            out.push_str(&format!("    // requires: {}\n", req.lean_expr.trim()));
            let err_enum = format!("{}Error", to_pascal_case(&spec.program_name));
            if let Some(err) = &req.error_name {
                out.push_str(&format!(
                    "    if !({}) {{ return Err(ProgramError::from({}::{})); }}\n",
                    req.rust_expr.trim(),
                    err_enum,
                    err
                ));
            } else {
                out.push_str(&format!("    debug_assert!({});\n", req.rust_expr.trim()));
            }
        }

        let err_enum = format!("{}Error", to_pascal_case(&spec.program_name));
        for ab in &handler.aborts_if {
            out.push_str(&format!(
                "    if ({}) {{ return Err(ProgramError::from({}::{})); }}\n",
                ab.rust_expr.trim(),
                err_enum,
                ab.error_name
            ));
        }

        out.push_str("    Ok(())\n");
        out.push_str("}\n\n");
    }

    out.push_str("// ---- END GENERATED ----\n");
    std::fs::write(src_dir.join("guards.rs"), &out)?;
    Ok(())
}

/// Infer the state struct name for a handler account in multi-account specs.
fn infer_state_name(
    acct: &crate::check::ParsedHandlerAccount,
    spec: &ParsedSpec,
    default: &str,
) -> String {
    // Check if this account name matches any account type name (lowercase match)
    for at in &spec.account_types {
        if acct.name == at.name.to_lowercase() || acct.name.starts_with(&at.name.to_lowercase()) {
            return format!("{}Account", at.name);
        }
    }
    default.to_string()
}

/// Generate Cargo.toml
fn generate_cargo_toml(spec: &ParsedSpec, fp: &SpecFingerprint, output_dir: &Path) -> Result<()> {
    const TEMPLATE: &str = include_str!("../templates/program-Cargo.toml");
    let program_name = spec.program_name.to_lowercase().replace('_', "-");
    let needs_spl = spec.handlers.iter().any(|h| h.has_token_accounts());
    let hash = fp
        .file_hashes
        .get("Cargo.toml")
        .cloned()
        .unwrap_or_default();

    let mut out = TEMPLATE
        .replace("{SPEC_HASH}", &hash)
        .replace("{PROGRAM_NAME}", &program_name)
        .replace("{QEDGEN_VERSION}", env!("CARGO_PKG_VERSION"));
    if needs_spl {
        out.push_str("\n# TODO: SPL helper crate (spec declares token transfers) — e.g.:\n");
        out.push_str("# anchor-spl = \"0.32.1\"\n");
    }
    std::fs::write(output_dir.join("Cargo.toml"), &out)?;
    Ok(())
}

// ============================================================================
// Public API
// ============================================================================

/// Generate a Quasar program skeleton from a spec file (.lean or .qedspec).
pub fn generate(spec_path: &Path, output_dir: &Path) -> Result<()> {
    let spec = check::parse_spec_file(spec_path)?;

    if spec.handlers.is_empty() {
        anyhow::bail!(
            "No handlers found in {}. Is this a valid qedspec file?",
            spec_path.display()
        );
    }

    // Check that the project is initialized (.qed/ next to the spec file)
    if crate::init::find_qed_dir(spec_path).is_none() {
        anyhow::bail!(
            "No .qed/ directory found next to {} — run `qedgen init` first.",
            spec_path.display()
        );
    }

    std::fs::create_dir_all(output_dir)?;

    let fp = crate::fingerprint::compute_fingerprint(&spec);

    generate_lib(&spec, &fp, output_dir)?;
    generate_state(&spec, &fp, output_dir)?;
    generate_events(&spec, &fp, output_dir)?;
    generate_errors(&spec, &fp, output_dir)?;
    generate_instructions(&spec, &fp, spec_path, output_dir)?;
    generate_guards(&spec, &fp, output_dir)?;
    generate_cargo_toml(&spec, &fp, output_dir)?;

    let file_count = 4
        + spec.handlers.len()
        + if spec.events.is_empty() { 0 } else { 1 }
        + if spec.error_codes.is_empty() { 0 } else { 1 };

    eprintln!("Generated {} files in {}", file_count, output_dir.display());

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn map_type_covers_all_primitives() {
        // Integer primitives
        assert_eq!(map_type("U8").unwrap(), "u8");
        assert_eq!(map_type("U16").unwrap(), "u16");
        assert_eq!(map_type("U32").unwrap(), "u32");
        assert_eq!(map_type("U64").unwrap(), "u64");
        assert_eq!(map_type("U128").unwrap(), "u128");
        assert_eq!(map_type("I8").unwrap(), "i8");
        assert_eq!(map_type("I16").unwrap(), "i16");
        assert_eq!(map_type("I32").unwrap(), "i32");
        assert_eq!(map_type("I64").unwrap(), "i64");
        assert_eq!(map_type("I128").unwrap(), "i128");

        // Non-integer primitives
        assert_eq!(map_type("Bool").unwrap(), "bool");
        assert_eq!(map_type("Pubkey").unwrap(), "Address");
    }

    #[test]
    fn map_type_errors_on_unknown_type() {
        // v2.6.1 bug: DSL types not in the four-item allowlist (U8/U64/U128/I128)
        // fell through as-is, leaking `U16` and `Map[N] T` verbatim into Rust.
        // v2.6.2: unknown types must surface as errors at codegen time.
        let err = map_type("Blorb").unwrap_err().to_string();
        assert!(
            err.contains("Blorb"),
            "error should name the bad type: {err}"
        );
        assert!(
            err.contains("unsupported DSL type"),
            "error should call it out as unsupported: {err}"
        );

        // Compound types aren't primitives — they're routed through their own
        // renderers. Until those land (v2.6.2 G1 Map[N] T / G3 sum types),
        // bare `map_type` must still reject them rather than silently pass
        // them through.
        assert!(map_type("Map[MAX_ACCOUNTS] UserAccount").is_err());
    }
}
