use anyhow::Result;
use std::path::Path;

use crate::check::{self, ParsedOperation};
use crate::codegen::map_type;

/// Translate a Lean guard expression to Rust.
/// Handles common patterns: s.field → state.field, ≤ → <=, ≥ → >=
fn translate_guard_to_rust(guard: &str, state_var: &str) -> String {
    guard
        .replace("s.", &format!("{}.", state_var))
        .replace('≤', "<=")
        .replace('≥', ">=")
        .replace('∧', "&&")
        .replace('∨', "||")
        .replace('≠', "!=")
}

/// Generate Kani proof harnesses from a spec file (.lean or .qedspec).
pub fn generate(spec_path: &Path, output_path: &Path) -> Result<()> {
    let spec = check::parse_spec_file(spec_path)?;

    if spec.operations.is_empty() {
        anyhow::bail!(
            "No operations found in {}. Is this a valid qedspec file?",
            spec_path.display()
        );
    }

    // Ensure parent directory exists
    if let Some(parent) = output_path.parent() {
        std::fs::create_dir_all(parent)?;
    }

    let fp = crate::fingerprint::compute_fingerprint(&spec);
    let hash = fp
        .file_hashes
        .get("tests/kani.rs")
        .cloned()
        .unwrap_or_default();

    let mut out = String::new();

    // File header
    out.push_str(&format!(
        "// ---- GENERATED BY QEDGEN — DO NOT EDIT ABOVE THIS LINE ---- spec-hash:{}\n",
        hash
    ));
    out.push_str("#![cfg(kani)]\n\n");
    out.push_str("use crate::state::*;\n");
    if !spec.events.is_empty() {
        out.push_str("use crate::events::*;\n");
    }
    if !spec.error_codes.is_empty() {
        out.push_str("use crate::errors::*;\n");
    }
    out.push_str("use crate::instructions::*;\n\n");

    // Access control harnesses — one per operation with who:
    let access_ops: Vec<&ParsedOperation> = spec
        .operations
        .iter()
        .filter(|op| op.who.is_some())
        .collect();
    if !access_ops.is_empty() {
        out.push_str(
            "// ============================================================================\n",
        );
        out.push_str("// Access control — only authorized signer can execute\n");
        out.push_str(
            "// ============================================================================\n\n",
        );

        for op in &access_ops {
            let who = op.who.as_ref().unwrap();
            out.push_str("#[kani::proof]\n");
            out.push_str("#[kani::unwind(2)]\n");
            out.push_str("#[kani::solver(cadical)]\n");
            out.push_str(&format!("fn verify_{}_access_control() {{\n", op.name));
            out.push_str(&format!("    let {}: Address = kani::any();\n", who));
            out.push_str("    let signer: Address = kani::any();\n");
            out.push_str(&format!("    kani::assume(signer != {});\n", who));
            out.push_str(&format!(
                "    // AGENT: construct {} accounts with wrong signer, call handler, assert it fails\n",
                op.name
            ));
            out.push_str("    todo!()\n");
            out.push_str("}\n\n");
        }
    }

    // Guard harnesses — one per operation with guard:
    let guard_ops: Vec<&ParsedOperation> =
        spec.operations.iter().filter(|op| op.has_guard).collect();
    if !guard_ops.is_empty() {
        out.push_str(
            "// ============================================================================\n",
        );
        out.push_str("// Guard enforcement — operations reject invalid inputs\n");
        out.push_str(
            "// ============================================================================\n\n",
        );

        for op in &guard_ops {
            let guard = op.guard_str.as_deref().unwrap_or("(unknown)");
            out.push_str("#[kani::proof]\n");
            out.push_str("#[kani::unwind(2)]\n");
            out.push_str("#[kani::solver(cadical)]\n");
            out.push_str(&format!("fn verify_{}_rejects_invalid() {{\n", op.name));

            // Emit symbolic variables for each takes param
            for (pname, ptype) in &op.takes_params {
                out.push_str(&format!(
                    "    let {}: {} = kani::any();\n",
                    pname,
                    map_type(ptype)
                ));
            }
            out.push_str(&format!(
                "    // AGENT: assume guard violation (negation of \"{}\")\n",
                guard
            ));
            out.push_str(&format!(
                "    // AGENT: construct {} accounts, call handler, assert it returns Err\n",
                op.name
            ));
            out.push_str("    todo!()\n");
            out.push_str("}\n\n");
        }
    }

    // State transition harnesses — one per operation with when:/then:
    let transition_ops: Vec<&ParsedOperation> = spec
        .operations
        .iter()
        .filter(|op| op.pre_status.is_some() && op.post_status.is_some())
        .collect();
    if !transition_ops.is_empty() {
        out.push_str(
            "// ============================================================================\n",
        );
        out.push_str("// State transitions — operations move state correctly\n");
        out.push_str(
            "// ============================================================================\n\n",
        );

        for op in &transition_ops {
            let pre = op.pre_status.as_ref().unwrap();
            let post = op.post_status.as_ref().unwrap();
            out.push_str("#[kani::proof]\n");
            out.push_str("#[kani::unwind(2)]\n");
            out.push_str("#[kani::solver(cadical)]\n");
            out.push_str(&format!(
                "fn verify_{}_transition_{}_to_{}() {{\n",
                op.name,
                pre.to_lowercase(),
                post.to_lowercase()
            ));

            // Emit symbolic params
            for (pname, ptype) in &op.takes_params {
                out.push_str(&format!(
                    "    let {}: {} = kani::any();\n",
                    pname,
                    map_type(ptype)
                ));
            }
            if op.has_guard {
                out.push_str(&format!(
                    "    // AGENT: assume guard holds (\"{}\")\n",
                    op.guard_str.as_deref().unwrap_or("")
                ));
            }
            out.push_str(&format!(
                "    // AGENT: set up state in Status::{}, call {}, assert state is Status::{}\n",
                pre, op.name, post
            ));
            out.push_str("    todo!()\n");
            out.push_str("}\n\n");
        }
    }

    // Conservation / property harnesses — one per property × preserved_by operation
    if !spec.properties.is_empty() {
        out.push_str(
            "// ============================================================================\n",
        );
        out.push_str("// Properties — spec-declared invariants preserved by operations\n");
        out.push_str(
            "// ============================================================================\n\n",
        );

        let is_multi_prop = spec.account_types.len() > 1;

        for prop in &spec.properties {
            for op_name in &prop.preserved_by {
                // Find the operation to get its params
                let op = spec.operations.iter().find(|o| &o.name == op_name);

                out.push_str("#[kani::proof]\n");
                out.push_str("#[kani::unwind(4)]\n");
                out.push_str("#[kani::solver(cadical)]\n");
                out.push_str(&format!(
                    "fn verify_{}_preserves_{}() {{\n",
                    op_name, prop.name
                ));

                // Get the correct fields for this operation's target account
                let prop_fields: &[(String, String)] = if is_multi_prop {
                    let target = op
                        .and_then(|o| o.on_account.as_deref())
                        .unwrap_or(&spec.account_types[0].name);
                    spec.account_types
                        .iter()
                        .find(|a| a.name == target)
                        .map(|a| a.fields.as_slice())
                        .unwrap_or(&spec.state_fields)
                } else {
                    &spec.state_fields
                };

                // State fields as symbolic
                for (fname, ftype) in prop_fields {
                    out.push_str(&format!(
                        "    let {}: {} = kani::any();\n",
                        fname,
                        map_type(ftype)
                    ));
                }

                // Operation params as symbolic (skip if already declared as state field)
                let state_field_names: Vec<&str> =
                    prop_fields.iter().map(|(n, _)| n.as_str()).collect();
                if let Some(op) = op {
                    for (pname, ptype) in &op.takes_params {
                        if !state_field_names.contains(&pname.as_str()) {
                            out.push_str(&format!(
                                "    let {}: {} = kani::any();\n",
                                pname,
                                map_type(ptype)
                            ));
                        }
                    }
                    if op.has_guard {
                        out.push_str(&format!(
                            "    // AGENT: assume guard holds — \"{}\"\n",
                            op.guard_str.as_deref().unwrap_or("true")
                        ));
                    }
                }

                out.push_str(&format!(
                    "    // AGENT: assume {} holds before {}, execute, assert it holds after\n",
                    prop.name, op_name
                ));
                out.push_str("    todo!()\n");
                out.push_str("}\n\n");
            }
        }
    }

    // Effect conformance — mechanically generated assertions (no agent involvement)
    // These mirror the Lean transition functions: both derive from the same effect declarations.
    let effect_ops: Vec<&ParsedOperation> =
        spec.operations.iter().filter(|op| op.has_effect).collect();
    if !effect_ops.is_empty() {
        out.push_str(
            "// ============================================================================\n",
        );
        out.push_str("// Effect conformance — generated from spec effects (NOT agent-written)\n");
        out.push_str("// These assertions are the mechanical tie between Lean and Kani:\n");
        out.push_str("//   Lean proves:  transition_fn preserves properties (∀ states)\n");
        out.push_str("//   Kani checks:  handler() computes the same transition_fn\n");
        out.push_str("// Both derive from the same `effect:` declarations in the spec.\n");
        out.push_str(
            "// ============================================================================\n\n",
        );

        let is_multi = spec.account_types.len() > 1;
        let default_state_name = format!(
            "{}Account",
            crate::codegen::to_pascal_case(&spec.program_name)
        );

        for op in &effect_ops {
            let pascal = crate::codegen::to_pascal_case(&op.name);

            // Determine state struct name based on on_account
            let state_name = if is_multi {
                if let Some(ref acct_name) = op.on_account {
                    format!("{}Account", acct_name)
                } else {
                    format!("{}Account", spec.account_types[0].name)
                }
            } else {
                default_state_name.clone()
            };

            // Get the correct fields for this account
            let acct_fields: &[(String, String)] = if is_multi {
                let target = op
                    .on_account
                    .as_deref()
                    .unwrap_or(&spec.account_types[0].name);
                spec.account_types
                    .iter()
                    .find(|a| a.name == target)
                    .map(|a| a.fields.as_slice())
                    .unwrap_or(&spec.state_fields)
            } else {
                &spec.state_fields
            };

            out.push_str("#[kani::proof]\n");
            out.push_str("#[kani::unwind(2)]\n");
            out.push_str("#[kani::solver(cadical)]\n");
            out.push_str(&format!("fn verify_{}_effects() {{\n", op.name));

            // Symbolic state
            out.push_str(&format!(
                "    let mut state = {}::arbitrary();\n",
                state_name
            ));

            // Symbolic params
            for (pname, ptype) in &op.takes_params {
                out.push_str(&format!(
                    "    let {}: {} = kani::any();\n",
                    pname,
                    map_type(ptype)
                ));
            }

            // Snapshot pre-state for all numeric fields (for effect + unchanged assertions)
            let affected_fields: Vec<&str> =
                op.effects.iter().map(|(f, _, _)| f.as_str()).collect();
            for (fname, ftype) in acct_fields {
                if ftype == "Pubkey" {
                    continue; // identity fields, not mutable state
                }
                out.push_str(&format!("    let pre_{} = state.{};\n", fname, fname));
            }

            // Guard assumption — translate spec guard to Rust
            if op.has_guard {
                let guard_rust =
                    translate_guard_to_rust(op.guard_str.as_deref().unwrap_or("true"), "state");
                out.push_str(&format!("    kani::assume({});\n", guard_rust));
            }

            // Call handler — AGENT must wire this up
            out.push_str(&format!(
                "    // AGENT: call {}.handler({}) and unwrap\n",
                op.name,
                op.takes_params
                    .iter()
                    .map(|(n, _)| n.as_str())
                    .collect::<Vec<_>>()
                    .join(", ")
            ));
            out.push_str(&format!(
                "    // let mut accounts = {} {{ ... }};\n",
                pascal
            ));
            out.push_str(&format!(
                "    // accounts.handler({}).unwrap();\n",
                op.takes_params
                    .iter()
                    .map(|(n, _)| n.as_str())
                    .collect::<Vec<_>>()
                    .join(", ")
            ));
            out.push('\n');

            // Generated assertions — these are deterministic, matching Lean's transition
            out.push_str("    // --- GENERATED ASSERTIONS (match Lean transition function) ---\n");
            for (field, op_kind, value) in &op.effects {
                match op_kind.as_str() {
                    "add" => {
                        // Lean: { s with field := s.field + value }
                        // Assert: no overflow AND correct result
                        out.push_str(&format!(
                            "    assert!(pre_{field}.checked_add({value}).is_some(), \"{field} + {value} overflows\");\n",
                        ));
                        out.push_str(&format!(
                            "    assert!(state.{field} == pre_{field} + {value}, \"{field} must equal pre + {value}\");\n",
                        ));
                    }
                    "sub" => {
                        // Lean: { s with field := s.field - value }
                        out.push_str(&format!(
                            "    assert!(pre_{field} >= {value}, \"{field} - {value} underflows\");\n",
                        ));
                        out.push_str(&format!(
                            "    assert!(state.{field} == pre_{field} - {value}, \"{field} must equal pre - {value}\");\n",
                        ));
                    }
                    "set" => {
                        // Lean: { s with field := value }
                        out.push_str(&format!(
                            "    assert!(state.{field} == {value}, \"{field} must equal {value}\");\n",
                        ));
                    }
                    _ => {
                        out.push_str(&format!(
                            "    // Unknown effect operator: {} {} {}\n",
                            field, op_kind, value
                        ));
                    }
                }
            }

            // Assert unchanged fields
            let unchanged: Vec<&(String, String)> = acct_fields
                .iter()
                .filter(|(f, _)| !affected_fields.contains(&f.as_str()))
                .collect();
            if !unchanged.is_empty() {
                out.push_str("    // Fields NOT in effects must be unchanged\n");
                for (field, ftype) in &unchanged {
                    // Skip pubkey/address fields — they're identity, not mutable state
                    if *ftype == "Pubkey" {
                        continue;
                    }
                    out.push_str(&format!(
                        "    assert!(state.{field} == pre_{field}, \"{field} must not change\");\n",
                    ));
                }
            }

            out.push_str("}\n\n");
        }
    }

    out.push_str("// ---- GENERATED BY QEDGEN — DO NOT EDIT BELOW THIS LINE ----\n");

    std::fs::write(output_path, &out)?;

    // Count harnesses
    let harness_count = access_ops.len()
        + guard_ops.len()
        + transition_ops.len()
        + spec
            .properties
            .iter()
            .map(|p| p.preserved_by.len())
            .sum::<usize>()
        + effect_ops.len();

    eprintln!(
        "Generated {} Kani harnesses in {}",
        harness_count,
        output_path.display()
    );
    if !access_ops.is_empty() {
        eprintln!("  {} access control harness(es)", access_ops.len());
    }
    if !guard_ops.is_empty() {
        eprintln!("  {} guard enforcement harness(es)", guard_ops.len());
    }
    if !transition_ops.is_empty() {
        eprintln!("  {} state transition harness(es)", transition_ops.len());
    }
    if !spec.properties.is_empty() {
        let prop_count: usize = spec.properties.iter().map(|p| p.preserved_by.len()).sum();
        eprintln!("  {} property preservation harness(es)", prop_count);
    }
    if !effect_ops.is_empty() {
        eprintln!(
            "  {} effect conformance harness(es) (generated assertions — ties Lean↔Kani)",
            effect_ops.len()
        );
    }

    Ok(())
}
