use anyhow::Result;
use std::path::Path;

use crate::check::{self, ParsedOperation, ParsedProperty};
use crate::codegen::map_type;

/// Translate a qedspec guard expression to Rust syntax.
/// Handles: s.field → s.field (kept as-is for transition fns),
///          ≤ → <=, ≥ → >=, ∧/and → &&, ∨/or → ||, ≠ → !=
fn translate_guard_to_rust(guard: &str) -> String {
    guard
        .replace("state.", "s.")
        .replace("s.", "s.")
        .replace('≤', "<=")
        .replace('≥', ">=")
        .replace('∧', "&&")
        .replace('∨', "||")
        .replace('≠', "!=")
        .replace(" and ", " && ")
        .replace(" or ", " || ")
}

/// Translate a qedspec property expression to Rust.
fn translate_property_to_rust(expr: &str) -> String {
    expr.replace("state.", "s.")
        .replace("s.", "s.")
        .replace('≤', "<=")
        .replace('≥', ">=")
        .replace('∧', "&&")
        .replace('∨', "||")
        .replace('≠', "!=")
        .replace(" and ", " && ")
        .replace(" or ", " || ")
}

/// For a field with an "add" effect, find what bounds it in property expressions.
/// Property expressions are in Lean form (e.g. `s.approval_count ≤ s.member_count`).
/// Returns the bounding field name if a `field ≤ bound` pattern is found.
fn find_upper_bound_field(field: &str, properties: &[ParsedProperty]) -> Option<String> {
    for prop in properties {
        if let Some(ref expr) = prop.expression {
            // Normalize Unicode operators to ASCII for matching
            let norm = expr.replace('\u{2264}', "<=").replace('\u{2265}', ">=");
            // Look for `s.field <=` or `field <=`
            let field_pat = format!("s.{}", field);
            if !norm.contains(&field_pat) && !norm.contains(field) {
                continue;
            }
            // Split on <= and find the one where our field is on the LHS
            for segment in norm.split("&&").chain(norm.split('\u{2227}')) {
                let segment = segment.trim();
                if let Some((lhs, rhs)) = segment.split_once("<=") {
                    let lhs = lhs.trim();
                    let rhs = rhs.trim();
                    if lhs.ends_with(field) || lhs == &format!("s.{}", field) {
                        // Extract the bound field from rhs
                        let bound = rhs
                            .strip_prefix("s.")
                            .or_else(|| rhs.strip_prefix("state."))
                            .unwrap_or(rhs)
                            .trim();
                        // Only return if it looks like a field name (not a literal)
                        if bound.chars().all(|c| c.is_alphanumeric() || c == '_')
                            && !bound.is_empty()
                            && !bound.chars().next().unwrap().is_ascii_digit()
                        {
                            return Some(bound.to_string());
                        }
                    }
                }
            }
        }
    }
    None
}

/// Emit `kani::assume(s.field < s.bound)` for operations with "add" effects,
/// to prevent arithmetic overflow and ensure bounded properties are preserved.
fn emit_add_strict_bounds(
    out: &mut String,
    op: &ParsedOperation,
    properties: &[ParsedProperty],
) {
    for (field, eff_op, _) in &op.effects {
        if eff_op == "add" {
            if let Some(bound) = find_upper_bound_field(field, properties) {
                out.push_str(&format!(
                    "    kani::assume(s.{} < s.{}); // strict bound: {} increments\n",
                    field, bound, field
                ));
            }
        }
    }
}

/// Generate Kani proof harnesses from a spec file (.lean or .qedspec).
///
/// Produces self-contained proofs that model state transitions from the spec
/// and verify properties using Kani bounded model checking — no framework deps.
pub fn generate(spec_path: &Path, output_path: &Path) -> Result<()> {
    let spec = check::parse_spec_file(spec_path)?;

    if spec.operations.is_empty() {
        anyhow::bail!(
            "No operations found in {}. Is this a valid qedspec file?",
            spec_path.display()
        );
    }

    // Ensure parent directory exists
    if let Some(parent) = output_path.parent() {
        std::fs::create_dir_all(parent)?;
    }

    let fp = crate::fingerprint::compute_fingerprint(&spec);
    let hash = fp
        .file_hashes
        .get("tests/kani.rs")
        .cloned()
        .unwrap_or_default();

    let mut out = String::new();

    // ── File header ──────────────────────────────────────────────────────
    out.push_str(&format!(
        "// ---- GENERATED BY QEDGEN ---- spec-hash:{}\n",
        hash
    ));
    out.push_str("//\n");
    out.push_str("// Self-contained Kani proof harnesses for the spec.\n");
    out.push_str("//\n");
    out.push_str("// These proofs verify the spec's transition design using Kani bounded model\n");
    out.push_str("// checking. They operate on a pure model of the state machine (derived from\n");
    out.push_str("// the qedspec), independent of framework (Quasar/Anchor) types.\n");
    out.push_str("//\n");
    out.push_str("//   Lean proves:  transition functions preserve invariants (∀ states)\n");
    out.push_str("//   Kani checks:  same properties via bounded model checking + overflow detection\n");
    out.push_str("//   Together:     high assurance that the spec design is correct\n");
    out.push_str("//\n");
    out.push_str("// To run:  cargo kani --harness <name>   (requires cargo-kani)\n");
    out.push_str("// ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----\n");
    out.push_str("#![cfg(kani)]\n\n");

    // ── State model ──────────────────────────────────────────────────────
    out.push_str(
        "// ============================================================================\n",
    );
    out.push_str("// State model (derived from qedspec — no framework dependencies)\n");
    out.push_str(
        "// ============================================================================\n\n",
    );

    // Emit constants
    for (name, value) in &spec.constants {
        let upper = name.to_uppercase();
        out.push_str(&format!(
            "const {}: u8 = {};\n",
            upper, value
        ));
    }
    if !spec.constants.is_empty() {
        out.push('\n');
    }

    // Collect mutable state fields (skip Pubkey — those are identity, not mutable state)
    let is_multi = spec.account_types.len() > 1;
    let state_fields: &[(String, String)] = if is_multi {
        &spec.account_types[0].fields
    } else {
        &spec.state_fields
    };

    let mutable_fields: Vec<&(String, String)> = state_fields
        .iter()
        .filter(|(_, t)| t != "Pubkey")
        .collect();

    out.push_str("#[derive(Clone, Copy)]\n");
    out.push_str("struct State {\n");
    for (fname, ftype) in &mutable_fields {
        out.push_str(&format!("    {}: {},\n", fname, map_type(ftype)));
    }
    out.push_str("}\n\n");

    // ── Property predicates ──────────────────────────────────────────────
    if !spec.properties.is_empty() {
        out.push_str(
            "// ============================================================================\n",
        );
        out.push_str("// Property predicates (from qedspec `property` declarations)\n");
        out.push_str(
            "// ============================================================================\n\n",
        );

        for prop in &spec.properties {
            if let Some(ref expr) = prop.expression {
                let rust_expr = translate_property_to_rust(expr);
                out.push_str(&format!("/// {}: {}\n", prop.name, expr));
                out.push_str(&format!("fn {}(s: &State) -> bool {{\n", prop.name));
                out.push_str(&format!("    {}\n", rust_expr));
                out.push_str("}\n\n");
            }
        }
    }

    // ── Transition functions ─────────────────────────────────────────────
    out.push_str(
        "// ============================================================================\n",
    );
    out.push_str("// Transition functions (from qedspec operations — effects + guards)\n");
    out.push_str("//\n");
    out.push_str("// Each returns true if the guard passes and the transition fires,\n");
    out.push_str("// false if the guard rejects the operation.\n");
    out.push_str(
        "// ============================================================================\n\n",
    );

    for op in &spec.operations {
        // Doc comment
        if let Some(ref doc) = op.doc {
            out.push_str(&format!("/// {}\n", doc.trim()));
        }

        // Function signature with params
        let params: String = op
            .takes_params
            .iter()
            .map(|(n, t)| format!(", {}: {}", n, map_type(t)))
            .collect();
        out.push_str(&format!(
            "fn {}(s: &mut State{}) -> bool {{\n",
            op.name, params
        ));

        // Guard check
        if op.has_guard {
            if let Some(ref guard) = op.guard_str {
                let rust_guard = translate_guard_to_rust(guard);
                out.push_str(&format!("    // guard: {}\n", guard));
                out.push_str(&format!("    if !({}) {{\n", rust_guard));
                out.push_str("        return false;\n");
                out.push_str("    }\n");
            }
        }

        // Apply effects
        for (field, op_kind, value) in &op.effects {
            // Resolve value: could be a param name or a literal
            let rust_value = if op.takes_params.iter().any(|(n, _)| n == value) {
                value.clone()
            } else {
                // Check if it's a constant name
                if let Some((_, const_val)) = spec.constants.iter().find(|(n, _)| n == value) {
                    const_val.clone()
                } else {
                    value.clone()
                }
            };

            match op_kind.as_str() {
                "set" => {
                    out.push_str(&format!("    s.{} = {};\n", field, rust_value));
                }
                "add" => {
                    out.push_str(&format!("    s.{} += {};\n", field, rust_value));
                }
                "sub" => {
                    out.push_str(&format!("    s.{} -= {};\n", field, rust_value));
                }
                _ => {
                    out.push_str(&format!(
                        "    // unknown effect: {} {} {}\n",
                        field, op_kind, value
                    ));
                }
            }
        }

        out.push_str("    true\n");
        out.push_str("}\n\n");
    }

    // ── Guard enforcement proofs ─────────────────────────────────────────
    let guard_ops: Vec<&ParsedOperation> =
        spec.operations.iter().filter(|op| op.has_guard).collect();
    if !guard_ops.is_empty() {
        out.push_str(
            "// ============================================================================\n",
        );
        out.push_str("// Guard enforcement — transitions reject invalid inputs\n");
        out.push_str(
            "// ============================================================================\n\n",
        );

        for op in &guard_ops {
            let guard = op.guard_str.as_deref().unwrap_or("true");
            let rust_guard = translate_guard_to_rust(guard);

            out.push_str("#[kani::proof]\n");
            out.push_str("#[kani::unwind(2)]\n");
            out.push_str("#[kani::solver(cadical)]\n");
            out.push_str(&format!("fn verify_{}_rejects_invalid() {{\n", op.name));

            // Symbolic state
            out.push_str("    let mut s = State {\n");
            for (fname, _) in &mutable_fields {
                out.push_str(&format!("        {}: kani::any(),\n", fname));
            }
            out.push_str("    };\n");

            // Symbolic params
            for (pname, ptype) in &op.takes_params {
                out.push_str(&format!(
                    "    let {}: {} = kani::any();\n",
                    pname,
                    map_type(ptype)
                ));
            }

            // Assume guard violation
            out.push_str(&format!("    kani::assume(!({rust_guard}));\n"));

            // Assert rejection
            let args: String = op
                .takes_params
                .iter()
                .map(|(n, _)| format!(", {}", n))
                .collect();
            out.push_str(&format!(
                "    assert!(!{}(&mut s{}),\n",
                op.name, args
            ));
            out.push_str(&format!(
                "        \"{} must reject when guard is violated\");\n",
                op.name
            ));
            out.push_str("}\n\n");
        }
    }

    // ── Property preservation proofs ─────────────────────────────────────
    if !spec.properties.is_empty() {
        out.push_str(
            "// ============================================================================\n",
        );
        out.push_str("// Property preservation — invariants hold through all transitions\n");
        out.push_str(
            "// ============================================================================\n\n",
        );

        for prop in &spec.properties {
            if prop.expression.is_none() {
                continue;
            }

            for op_name in &prop.preserved_by {
                let op = spec.operations.iter().find(|o| &o.name == op_name);

                out.push_str("#[kani::proof]\n");
                out.push_str("#[kani::unwind(2)]\n");
                out.push_str("#[kani::solver(cadical)]\n");
                out.push_str(&format!(
                    "fn verify_{}_preserves_{}() {{\n",
                    op_name, prop.name
                ));

                // Determine if this is an initializing operation
                let is_init = op
                    .map(|o| o.pre_status.as_deref() == Some("Uninitialized"))
                    .unwrap_or(false);

                if is_init {
                    // For init operations, start with zeroed state
                    out.push_str("    let mut s = State {\n");
                    for (fname, _) in &mutable_fields {
                        out.push_str(&format!("        {}: 0,\n", fname));
                    }
                    out.push_str("    };\n");
                } else {
                    // Symbolic state with invariant assumptions
                    out.push_str("    let mut s = State {\n");
                    for (fname, _) in &mutable_fields {
                        out.push_str(&format!("        {}: kani::any(),\n", fname));
                    }
                    out.push_str("    };\n");

                    // Assume all declared properties hold before transition
                    for pre_prop in &spec.properties {
                        if pre_prop.expression.is_some() {
                            out.push_str(&format!("    kani::assume({}(&s));\n", pre_prop.name));
                        }
                    }

                    // Assume MAX_MEMBERS bound (derived from create_vault guard)
                    if !spec.constants.is_empty() {
                        // Find a "members" or "max" constant
                        for (cname, _cval) in &spec.constants {
                            let upper = cname.to_uppercase();
                            if upper.contains("MAX") || upper.contains("MEMBER") {
                                // Assume member_count <= MAX (from create_vault guard)
                                if mutable_fields.iter().any(|(f, _)| f == "member_count") {
                                    out.push_str(&format!(
                                        "    kani::assume(s.member_count <= {});\n",
                                        upper
                                    ));
                                }
                                break;
                            }
                        }
                    }
                }

                // Symbolic params
                if let Some(op) = op {
                    for (pname, ptype) in &op.takes_params {
                        out.push_str(&format!(
                            "    let {}: {} = kani::any();\n",
                            pname,
                            map_type(ptype)
                        ));
                    }
                }

                // For operations that increment a field (add effect), assume
                // the field is strictly less than its bound to prevent overflow
                if let Some(op) = op {
                    emit_add_strict_bounds(&mut out, op, &spec.properties);
                }

                // Call transition and assert property
                let args: String = op
                    .map(|o| {
                        o.takes_params
                            .iter()
                            .map(|(n, _)| format!(", {}", n))
                            .collect()
                    })
                    .unwrap_or_default();
                out.push_str(&format!(
                    "    if {}(&mut s{}) {{\n",
                    op_name, args
                ));
                out.push_str(&format!(
                    "        assert!({}(&s),\n",
                    prop.name
                ));
                out.push_str(&format!(
                    "            \"{} must hold after {}\");\n",
                    prop.name, op_name
                ));
                out.push_str("    }\n");
                out.push_str("}\n\n");
            }
        }
    }

    // ── Effect conformance proofs ─────────────────────────────────────────
    let effect_ops: Vec<&ParsedOperation> =
        spec.operations.iter().filter(|op| op.has_effect).collect();
    if !effect_ops.is_empty() {
        out.push_str(
            "// ============================================================================\n",
        );
        out.push_str("// Effect conformance — verify transition effects match spec\n");
        out.push_str("//\n");
        out.push_str("// Each proof applies a transition to symbolic state and checks that every\n");
        out.push_str("// field changed/unchanged matches the spec's effect: declarations.\n");
        out.push_str(
            "// ============================================================================\n\n",
        );

        for op in &effect_ops {
            out.push_str("#[kani::proof]\n");
            out.push_str("#[kani::unwind(2)]\n");
            out.push_str("#[kani::solver(cadical)]\n");
            out.push_str(&format!("fn verify_{}_effects() {{\n", op.name));

            let is_init = op.pre_status.as_deref() == Some("Uninitialized");

            // Symbolic state
            if is_init {
                out.push_str("    let mut s = State {\n");
                for (fname, _) in &mutable_fields {
                    out.push_str(&format!("        {}: 0,\n", fname));
                }
                out.push_str("    };\n");
            } else {
                out.push_str("    let mut s = State {\n");
                for (fname, _) in &mutable_fields {
                    out.push_str(&format!("        {}: kani::any(),\n", fname));
                }
                out.push_str("    };\n");
            }

            // Symbolic params
            for (pname, ptype) in &op.takes_params {
                out.push_str(&format!(
                    "    let {}: {} = kani::any();\n",
                    pname,
                    map_type(ptype)
                ));
            }

            // Bounds assumptions for arithmetic safety
            if !is_init {
                if !spec.constants.is_empty() {
                    for (cname, _) in &spec.constants {
                        let upper = cname.to_uppercase();
                        if upper.contains("MAX") || upper.contains("MEMBER") {
                            if mutable_fields.iter().any(|(f, _)| f == "member_count") {
                                out.push_str(&format!(
                                    "    kani::assume(s.member_count <= {});\n",
                                    upper
                                ));
                            }
                            break;
                        }
                    }
                }
                emit_add_strict_bounds(&mut out, op, &spec.properties);
            }

            // Snapshot pre-state — only for fields that need it
            // (add/sub effects reference pre_*, unchanged fields reference pre_*)
            let affected_fields: Vec<&str> =
                op.effects.iter().map(|(f, _, _)| f.as_str()).collect();
            let needs_pre: Vec<&&(String, String)> = mutable_fields
                .iter()
                .filter(|(fname, _)| {
                    // Fields with "set" effects don't need pre (assertion uses literal/param)
                    let has_set = op
                        .effects
                        .iter()
                        .any(|(f, k, _)| f.as_str() == fname.as_str() && k == "set");
                    !has_set
                })
                .collect();
            for (fname, _) in &needs_pre {
                out.push_str(&format!("    let pre_{} = s.{};\n", fname, fname));
            }

            // Call transition
            let args: String = op
                .takes_params
                .iter()
                .map(|(n, _)| format!(", {}", n))
                .collect();
            out.push_str(&format!(
                "    if {}(&mut s{}) {{\n",
                op.name, args
            ));

            // Assert effects
            for (field, op_kind, value) in &op.effects {
                match op_kind.as_str() {
                    "set" => {
                        out.push_str(&format!(
                            "        assert!(s.{} == {}, \"{} must equal {}\");\n",
                            field, value, field, value
                        ));
                    }
                    "add" => {
                        out.push_str(&format!(
                            "        assert!(s.{} == pre_{} + {}, \"{} must increment by {}\");\n",
                            field, field, value, field, value
                        ));
                    }
                    "sub" => {
                        out.push_str(&format!(
                            "        assert!(s.{} == pre_{} - {}, \"{} must decrement by {}\");\n",
                            field, field, value, field, value
                        ));
                    }
                    _ => {}
                }
            }

            // Assert unchanged fields
            for (fname, _) in &mutable_fields {
                if !affected_fields.contains(&fname.as_str()) {
                    out.push_str(&format!(
                        "        assert!(s.{} == pre_{}, \"{} must not change\");\n",
                        fname, fname, fname
                    ));
                }
            }

            out.push_str("    }\n");
            out.push_str("}\n\n");
        }
    }

    out.push_str("// ---- GENERATED BY QEDGEN — DO NOT EDIT BELOW THIS LINE ----\n");

    std::fs::write(output_path, &out)?;

    // ── Summary ──────────────────────────────────────────────────────────
    let guard_count = guard_ops.len();
    let prop_count: usize = spec
        .properties
        .iter()
        .filter(|p| p.expression.is_some())
        .map(|p| p.preserved_by.len())
        .sum();
    let effect_count = effect_ops.len();
    let total = guard_count + prop_count + effect_count;

    eprintln!(
        "Generated {} Kani harnesses in {}",
        total,
        output_path.display()
    );
    if guard_count > 0 {
        eprintln!("  {} guard enforcement proof(s)", guard_count);
    }
    if prop_count > 0 {
        eprintln!("  {} property preservation proof(s)", prop_count);
    }
    if effect_count > 0 {
        eprintln!("  {} effect conformance proof(s)", effect_count);
    }

    Ok(())
}
