-- Generated by qedgen lean-gen from slippage.qedspec
-- Source of truth: the .qedspec file. Regenerate with:
--   qedgen lean-gen --spec <spec>.qedspec --output <this-file>

import QEDGen
import SlippageProg

open QEDGen.Solana.SBPF
open QEDGen.Solana.SBPF.Memory

namespace Entrypoint

-- Error constants
abbrev E_SLIPPAGE_EXCEEDED : Nat := 1

-- Offset constants
abbrev TOKEN_BALANCE : Int := 160
abbrev MINIMUM_BALANCE : Int := 10520

-- Effective address lemmas
@[simp] theorem ea_TOKEN_BALANCE (b : Nat) : effectiveAddr b TOKEN_BALANCE = b + 160 := by
  unfold effectiveAddr TOKEN_BALANCE; omega

@[simp] theorem ea_MINIMUM_BALANCE (b : Nat) : effectiveAddr b MINIMUM_BALANCE = b + 10520 := by
  unfold effectiveAddr MINIMUM_BALANCE; omega

-- Guard theorem stubs
-- Hypotheses derived from checks + layout. Fill proofs with wp_exec.

/-- Rejects when minimum balance >= token balance -/
theorem rejects_insufficient_balance
    (inputAddr : Nat) (mem : Mem)
    (minimumBalance : Nat)
    (h_minimumBalance_val : readU64 mem (inputAddr + 10520) = minimumBalance)
    (tokenBalance : Nat)
    (h_tokenBalance_val : readU64 mem (inputAddr + 160) = tokenBalance)
    (h_minimumBalance_lt : minimumBalance < tokenBalance)
    :
    (executeFn SlippageProg.progAt (initState inputAddr mem) 10).exitCode
      = some E_SLIPPAGE_EXCEEDED := sorry

-- Completeness structure: fill all fields to prove every guard is covered
structure Spec (progAt : Nat → Option Insn) where
  rejects_insufficient_balance :
    ∀ (inputAddr : Nat) (mem : Mem) (minimumBalance : Nat) (_h_minimumBalance_val : readU64 mem (inputAddr + 10520) = minimumBalance) (tokenBalance : Nat) (_h_tokenBalance_val : readU64 mem (inputAddr + 160) = tokenBalance) (_h_minimumBalance_lt : minimumBalance < tokenBalance),
    (executeFn progAt (initState inputAddr mem) 10).exitCode = some E_SLIPPAGE_EXCEEDED

-- Property theorem stubs

/-- Accepts when minimum balance < token balance -/
theorem accepts_sufficient_balance : True := trivial

end Entrypoint
