// ---- GENERATED BY QEDGEN — DO NOT EDIT ---- spec-hash:37b09521b52fe136
use quasar_lang::prelude::*;

#[error_code]
pub enum LendingError {
    InsufficientLiquidity = 0,
    InsufficientCollateral = 1,
    Unauthorized = 2,
    AlreadyActive = 3,
    InvalidAmount = 4,
}
// ---- END GENERATED ----
