// ---- GENERATED BY QEDGEN — DO NOT EDIT — regenerated from .qedspec ----
//! Per-handler guard checks derived from the `.qedspec`.
//! Called from user-owned `instructions/<name>::handler` before
//! business logic; keep guard logic here, policy-free logic there.

#![allow(unused_variables, unused_imports, dead_code, clippy::too_many_arguments)]

use quasar_lang::prelude::*;
use crate::errors::*;
use crate::state::*;
use crate::instructions::*;

/// Guards for `init_pool`.  
/// Generated from the `requires` clauses of the spec handler block.
pub fn init_pool<'info>(ctx: &mut InitPool<'info>, rate: u64) -> Result<(), ProgramError> {
    // requires: rate > 0
    if !(rate > 0) { return Err(ProgramError::from(LendingError::InvalidAmount)); }
    // lifecycle: status := Active
    ctx.pool.status = PoolStatus::Active as u8;
    Ok(())
}

/// Guards for `deposit`.  
/// Generated from the `requires` clauses of the spec handler block.
pub fn deposit<'info>(ctx: &mut Deposit<'info>, amount: u64) -> Result<(), ProgramError> {
    // lifecycle: require status == Active
    if ctx.pool.status != PoolStatus::Active as u8 { return Err(ProgramError::from(LendingError::InvalidLifecycle)); }
    // authority: ctx.pool_vault.owner() == ctx.pool.address()
    if *ctx.pool_vault.owner() != *ctx.pool.to_account_view().address() { return Err(ProgramError::from(LendingError::Unauthorized)); }
    // requires: amount > 0
    if !(amount > 0) { return Err(ProgramError::from(LendingError::InvalidAmount)); }
    Ok(())
}

/// Guards for `borrow`.  
/// Generated from the `requires` clauses of the spec handler block.
pub fn borrow<'info>(ctx: &mut Borrow<'info>, amount: u64, collateral: u64) -> Result<(), ProgramError> {
    // authority: ctx.pool_vault.owner() == ctx.pool.address()
    if *ctx.pool_vault.owner() != *ctx.pool.to_account_view().address() { return Err(ProgramError::from(LendingError::Unauthorized)); }
    // requires: amount > 0 ∧ collateral > 0
    if !((amount > 0) && (collateral > 0)) { return Err(ProgramError::from(LendingError::InvalidAmount)); }
    Ok(())
}

/// Guards for `repay`.  
/// Generated from the `requires` clauses of the spec handler block.
pub fn repay<'info>(ctx: &mut Repay<'info>) -> Result<(), ProgramError> {
    // authority: ctx.pool_vault.owner() == ctx.pool.address()
    if *ctx.pool_vault.owner() != *ctx.pool.to_account_view().address() { return Err(ProgramError::from(LendingError::Unauthorized)); }
    // No guards declared in spec — nothing to check.
    Ok(())
}

/// Guards for `liquidate`.  
/// Generated from the `requires` clauses of the spec handler block.
pub fn liquidate<'info>(ctx: &mut Liquidate<'info>) -> Result<(), ProgramError> {
    // authority: ctx.pool_vault.owner() == ctx.pool.address()
    if *ctx.pool_vault.owner() != *ctx.pool.to_account_view().address() { return Err(ProgramError::from(LendingError::Unauthorized)); }
    // No guards declared in spec — nothing to check.
    Ok(())
}

// ---- END GENERATED ----
