// ---- GENERATED BY QEDGEN — DO NOT EDIT — regenerated from .qedspec ----
//! Per-handler guard checks derived from the `.qedspec`.
//! Called from user-owned `instructions/<name>::handler` before
//! business logic; keep guard logic here, policy-free logic there.

#![allow(unused_variables, unused_imports, dead_code, clippy::too_many_arguments)]

use quasar_lang::prelude::*;
use crate::errors::*;
use crate::instructions::*;

/// Guards for `init_pool`.  
/// Generated from the `requires` clauses of the spec handler block.
pub fn init_pool(ctx: &mut InitPool, rate: u64) -> Result<(), ProgramError> {
    // requires: rate > 0
    if !(rate > 0) { return Err(ProgramError::from(LendingError::InvalidAmount)); }
    Ok(())
}

/// Guards for `deposit`.  
/// Generated from the `requires` clauses of the spec handler block.
pub fn deposit(ctx: &mut Deposit, amount: u64) -> Result<(), ProgramError> {
    // requires: amount > 0
    if !(amount > 0) { return Err(ProgramError::from(LendingError::InvalidAmount)); }
    Ok(())
}

/// Guards for `borrow`.  
/// Generated from the `requires` clauses of the spec handler block.
pub fn borrow(ctx: &mut Borrow, amount: u64, collateral: u64) -> Result<(), ProgramError> {
    // requires: amount > 0 ∧ collateral > 0
    if !((amount > 0) && (collateral > 0)) { return Err(ProgramError::from(LendingError::InvalidAmount)); }
    Ok(())
}

/// Guards for `repay`.  
/// Generated from the `requires` clauses of the spec handler block.
pub fn repay(ctx: &mut Repay) -> Result<(), ProgramError> {
    // No guards declared in spec — nothing to check.
    Ok(())
}

/// Guards for `liquidate`.  
/// Generated from the `requires` clauses of the spec handler block.
pub fn liquidate(ctx: &mut Liquidate) -> Result<(), ProgramError> {
    // No guards declared in spec — nothing to check.
    Ok(())
}

// ---- END GENERATED ----
