// ---- GENERATED BY QEDGEN — DO NOT EDIT ---- spec-hash:37c283550e5924ac
use quasar_lang::prelude::*;

#[account(discriminator = 1, set_inner)]
#[seeds(b"vault", creator: Address)]
pub struct MultisigAccount {
    pub creator: Address,
    pub threshold: u8,
    pub member_count: u8,
    pub approval_count: u8,
    pub bump: u8,
}

/// Program lifecycle states.
#[derive(Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
pub enum Status {
    Uninitialized = 0,
    Active = 1,
    HasProposal = 2,
}
// ---- END GENERATED ----
