// ---- GENERATED BY QEDGEN ---- spec-hash:219d38217f12d375
//
// Self-contained Kani proof harnesses for the spec.
//
// These proofs verify the spec's transition design using Kani bounded model
// checking. They operate on a pure model of the state machine (derived from
// the qedspec), independent of framework (Quasar/Anchor) types.
//
//   Lean proves:  transition functions preserve invariants (∀ states)
//   Kani checks:  same properties via bounded model checking + overflow detection
//   Together:     high assurance that the spec design is correct
//
// To run:  cargo kani --harness <name>   (requires cargo-kani)
// ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----
#![cfg(kani)]

// ============================================================================
// State model (derived from qedspec — no framework dependencies)
// ============================================================================

#[derive(Clone, Copy, PartialEq, Eq, kani::Arbitrary)]
enum Status {
    Uninitialized,
    Active,
}

#[derive(Clone, Copy)]
struct State {
    total_deposits: u64,
    status: Status,
}

/// ADT canonical form (#326): fields the active variant does not carry
/// hold their type defaults, matching the Lean field-accessor semantics.
fn state_repr_valid(s: &State) -> bool {
    match s.status {
        Status::Uninitialized => s.total_deposits == 0,
        Status::Active => true,
    }
}

#[derive(Clone, Copy)]
struct KaniAccount {
    pubkey: [u8; 32],
}

#[derive(Clone, Copy)]
struct EmergencyCloseAccounts {
    admin: KaniAccount,
    vault: KaniAccount,
    vault_ta: KaniAccount,
    sink_ta: KaniAccount,
    token_program: KaniAccount,
    admin_config: KaniAccount,
    admin_config_admin: [u8; 32],
}

// ============================================================================
// Transition functions (from qedspec operations — effects + guards)
//
// Each returns true if the guard passes and the transition fires,
// false if the guard rejects the operation.
// ============================================================================

fn initialize(s: &mut State) -> bool {
    if s.status != Status::Uninitialized {
        return false;
    }
    s.total_deposits = 0;
    s.status = Status::Active;
    true
}

fn deposit(s: &mut State, amount: u64) -> bool {
    if !(amount > 0) {
        return false;
    }
    if s.status != Status::Active {
        return false;
    }
    match s.total_deposits.checked_add(amount) {
        Some(__v) => s.total_deposits = __v,
        None => return false,
    }
    s.status = Status::Active;
    true
}

fn emergency_close(s: &mut State, accounts: &EmergencyCloseAccounts) -> bool {
    if !(accounts.admin_config_admin == accounts.admin.pubkey) {
        return false;
    }
    if s.status != Status::Active {
        return false;
    }
    s.total_deposits = 0;
    s.status = Status::Active;
    true
}

// ============================================================================
// Guard enforcement — transitions reject invalid inputs
// ============================================================================

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_deposit_rejects_invalid() {
    let mut s = State {
        total_deposits: kani::any(),
        status: kani::any(),
    };
    kani::assume(state_repr_valid(&s));
    kani::assume(s.status == Status::Active);
    let amount: u64 = kani::any();
    kani::assume(!(amount > 0));
    kani::cover!(true, "guard-violation domain is satisfiable");
    assert!(
        !deposit(&mut s, amount),
        "deposit must reject when guard is violated"
    );
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_emergency_close_rejects_invalid() {
    let mut s = State {
        total_deposits: kani::any(),
        status: kani::any(),
    };
    kani::assume(state_repr_valid(&s));
    kani::assume(s.status == Status::Active);
    let accounts = EmergencyCloseAccounts {
        admin: KaniAccount {
            pubkey: kani::any(),
        },
        vault: KaniAccount {
            pubkey: kani::any(),
        },
        vault_ta: KaniAccount {
            pubkey: kani::any(),
        },
        sink_ta: KaniAccount {
            pubkey: kani::any(),
        },
        token_program: KaniAccount {
            pubkey: kani::any(),
        },
        admin_config: KaniAccount {
            pubkey: kani::any(),
        },
        admin_config_admin: kani::any(),
    };
    kani::assume(!(accounts.admin_config_admin == accounts.admin.pubkey));
    kani::cover!(true, "guard-violation domain is satisfiable");
    assert!(
        !emergency_close(&mut s, &accounts),
        "emergency_close must reject when guard is violated"
    );
}

// ============================================================================
// Effect conformance — verify transition effects match spec
//
// Each proof applies a transition to symbolic state and checks that every
// field changed/unchanged matches the spec's effect: declarations.
// ============================================================================

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_deposit_effect_total_deposits() {
    let mut s = State {
        total_deposits: kani::any(),
        status: kani::any(),
    };
    kani::assume(state_repr_valid(&s));
    kani::assume(s.status == Status::Active);
    let amount: u64 = kani::any();
    let pre_total_deposits = s.total_deposits;
    if deposit(&mut s, amount) {
        assert!(
            s.total_deposits == pre_total_deposits.wrapping_add(amount),
            "total_deposits must increment by amount"
        );
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_emergency_close_effect_total_deposits() {
    let mut s = State {
        total_deposits: kani::any(),
        status: kani::any(),
    };
    kani::assume(state_repr_valid(&s));
    kani::assume(s.status == Status::Active);
    let accounts = EmergencyCloseAccounts {
        admin: KaniAccount {
            pubkey: kani::any(),
        },
        vault: KaniAccount {
            pubkey: kani::any(),
        },
        vault_ta: KaniAccount {
            pubkey: kani::any(),
        },
        sink_ta: KaniAccount {
            pubkey: kani::any(),
        },
        token_program: KaniAccount {
            pubkey: kani::any(),
        },
        admin_config: KaniAccount {
            pubkey: kani::any(),
        },
        admin_config_admin: kani::any(),
    };
    if emergency_close(&mut s, &accounts) {
        assert!(s.total_deposits == 0, "total_deposits must equal 0");
    }
}

// ============================================================================
// Overflow detection — Kani catches arithmetic overflow on add effects
// ============================================================================

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_deposit_no_overflow() {
    let mut s = State {
        total_deposits: kani::any(),
        status: kani::any(),
    };
    kani::assume(state_repr_valid(&s));
    kani::assume(s.status == Status::Active);
    let amount: u64 = kani::any();
    deposit(&mut s, amount); // Kani detects overflow on += internally
}

// ---- GENERATED BY QEDGEN — DO NOT EDIT BELOW THIS LINE ----
