// ---- GENERATED BY QEDGEN ---- spec-hash:47600ad092b5663c
//
// Self-contained Kani proof harnesses for the spec.
//
// These proofs verify the spec's transition design using Kani bounded model
// checking. They operate on a pure model of the state machine (derived from
// the qedspec), independent of framework (Quasar/Anchor) types.
//
//   Lean proves:  transition functions preserve invariants (∀ states)
//   Kani checks:  same properties via bounded model checking + overflow detection
//   Together:     high assurance that the spec design is correct
//
// To run:  cargo kani --harness <name>   (requires cargo-kani)
// ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----
#![cfg(kani)]

// ============================================================================
// State model (derived from qedspec — no framework dependencies)
// ============================================================================

#[derive(Clone, Copy, PartialEq, Eq, kani::Arbitrary)]
enum Status {
    Uninitialized,
    Active,
}

#[derive(Clone, Copy)]
struct State {
    total: u64,
    rate: u64,
    status: Status,
}

// ============================================================================
// Property predicates (from qedspec `property` declarations)
// ============================================================================

/// rate_floor: s.rate > 0 ∨ s.total = 0
fn rate_floor(s: &State) -> bool {
    s.rate > 0 || s.total == 0
}

// ============================================================================
// Transition functions (from qedspec operations — effects + guards)
//
// Each returns true if the guard passes and the transition fires,
// false if the guard rejects the operation.
// ============================================================================

fn init_pool(s: &mut State, rate_in: u64) -> bool {
    if !(rate_in > 0) {
        return false;
    }
    if s.status != Status::Uninitialized {
        return false;
    }
    s.rate = rate_in;
    s.total = 0;
    s.status = Status::Active;
    true
}

fn deposit(s: &mut State, amount: u64) -> bool {
    if !(amount > 0) {
        return false;
    }
    if s.status != Status::Active {
        return false;
    }
    match s.total.checked_add(amount) {
        Some(__v) => s.total = __v,
        None => return false,
    }
    s.status = Status::Active;
    true
}

// ============================================================================
// Guard enforcement — transitions reject invalid inputs
// ============================================================================

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_init_pool_rejects_invalid() {
    let mut s = State {
        total: kani::any(),
        rate: kani::any(),
        status: kani::any(),
    };
    kani::assume(s.status == Status::Uninitialized);
    let rate_in: u64 = kani::any();
    kani::assume(!(rate_in > 0));
    kani::cover!(true, "guard-violation domain is satisfiable");
    assert!(
        !init_pool(&mut s, rate_in),
        "init_pool must reject when guard is violated"
    );
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_deposit_rejects_invalid() {
    let mut s = State {
        total: kani::any(),
        rate: kani::any(),
        status: kani::any(),
    };
    kani::assume(s.status == Status::Active);
    let amount: u64 = kani::any();
    kani::assume(!(amount > 0));
    kani::cover!(true, "guard-violation domain is satisfiable");
    assert!(
        !deposit(&mut s, amount),
        "deposit must reject when guard is violated"
    );
}

// ============================================================================
// Property preservation — invariants hold through all transitions
// ============================================================================

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_init_pool_preserves_rate_floor() {
    let pre = State {
        total: 0,
        rate: 0,
        status: Status::Uninitialized,
    };
    let mut post = pre;
    let rate_in: u64 = kani::any();
    if init_pool(&mut post, rate_in) {
        assert!(rate_floor(&post), "rate_floor must hold after init_pool");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_deposit_preserves_rate_floor() {
    let pre = State {
        total: kani::any(),
        rate: kani::any(),
        status: kani::any(),
    };
    kani::assume(pre.status == Status::Active);
    kani::assume(rate_floor(&pre));
    let mut post = pre;
    let amount: u64 = kani::any();
    if deposit(&mut post, amount) {
        assert!(rate_floor(&post), "rate_floor must hold after deposit");
    }
}

// ============================================================================
// Effect conformance — verify transition effects match spec
//
// Each proof applies a transition to symbolic state and checks that every
// field changed/unchanged matches the spec's effect: declarations.
// ============================================================================

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_init_pool_effect_rate() {
    let mut s = State {
        total: 0,
        rate: 0,
        status: Status::Uninitialized,
    };
    let rate_in: u64 = kani::any();
    let pre_total = s.total;
    if init_pool(&mut s, rate_in) {
        assert!(s.rate == rate_in, "rate must equal rate_in");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_init_pool_effect_total() {
    let mut s = State {
        total: 0,
        rate: 0,
        status: Status::Uninitialized,
    };
    let rate_in: u64 = kani::any();
    let pre_rate = s.rate;
    if init_pool(&mut s, rate_in) {
        assert!(s.total == 0, "total must equal 0");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_deposit_effect_total() {
    let mut s = State {
        total: kani::any(),
        rate: kani::any(),
        status: kani::any(),
    };
    kani::assume(s.status == Status::Active);
    let amount: u64 = kani::any();
    let pre_total = s.total;
    let pre_rate = s.rate;
    if deposit(&mut s, amount) {
        assert!(
            s.total == pre_total.wrapping_add(amount),
            "total must increment by amount"
        );
        assert!(s.rate == pre_rate, "rate must not change");
    }
}

// ============================================================================
// Overflow detection — Kani catches arithmetic overflow on add effects
// ============================================================================

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_deposit_no_overflow() {
    let mut s = State {
        total: kani::any(),
        rate: kani::any(),
        status: kani::any(),
    };
    kani::assume(s.status == Status::Active);
    let amount: u64 = kani::any();
    deposit(&mut s, amount); // Kani detects overflow on += internally
}

// ============================================================================
// Environment — properties hold under external state changes
// ============================================================================

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_rate_floor_under_rate_change() {
    let mut s = State {
        total: kani::any(),
        rate: kani::any(),
        status: kani::any(),
    };
    kani::assume(rate_floor(&s));
    s.rate = kani::any();
    kani::assume(s.rate > 0);
    assert!(rate_floor(&s), "rate_floor must hold after rate_change");
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_rate_floor_under_oracle_step() {
    let mut s = State {
        total: kani::any(),
        rate: kani::any(),
        status: kani::any(),
    };
    kani::assume(rate_floor(&s));
    let pre_oracle_price: u64 = kani::any();
    let post_oracle_price: u64 = kani::any();
    s.rate = kani::any();
    let post = &s;
    kani::assume(post.rate == post_oracle_price);
    kani::assume(post_oracle_price >= pre_oracle_price);
    assert!(rate_floor(&s), "rate_floor must hold after oracle_step");
}

// ---- GENERATED BY QEDGEN — DO NOT EDIT BELOW THIS LINE ----
