// ---- GENERATED BY QEDGEN — DO NOT EDIT ---- spec-hash:a91cd9e35327131f
use quasar_lang::prelude::*;

#[error_code]
pub enum PercolatorError {
    InsufficientFunds = 0,
    SlotInactive = 1,
    SlotAlreadyActive = 2,
    AccountUnderwater = 3,
    AccountHealthy = 4,
    BankruptPosition = 5,
    VaultOverflow = 6,
}
// ---- END GENERATED ----
