// ---- GENERATED BY QEDGEN — DO NOT EDIT — regenerated from .qedspec ----
//! Per-handler guard checks derived from the `.qedspec`.
//! Called from user-owned `instructions/<name>::handler` before
//! business logic; keep guard logic here, policy-free logic there.

#![allow(unused_variables, unused_imports, dead_code, clippy::too_many_arguments)]

use quasar_lang::prelude::*;
use crate::errors::*;
use crate::instructions::*;

/// Guards for `add_user`.  
/// Generated from the `requires` clauses of the spec handler block.
pub fn add_user<'info>(ctx: &mut AddUser<'info>, i: usize) -> Result<(), ProgramError> {
    // requires: s.accounts[i].active = 0
    if !(ctx.vault.accounts[i].active == 0) { return Err(ProgramError::from(PercolatorError::SlotAlreadyActive)); }
    // requires: (((s.accounts[i].capital) : Int)) + s.accounts[i].pnl ≥ (((0) : Int))
    if !(ctx.vault.accounts[i].capital + ctx.vault.accounts[i].pnl >= 0) { return Err(ProgramError::from(PercolatorError::AccountUnderwater)); }
    Ok(())
}

/// Guards for `add_lp`.  
/// Generated from the `requires` clauses of the spec handler block.
pub fn add_lp<'info>(ctx: &mut AddLp<'info>, i: usize) -> Result<(), ProgramError> {
    // requires: s.accounts[i].active = 0
    if !(ctx.vault.accounts[i].active == 0) { return Err(ProgramError::from(PercolatorError::SlotAlreadyActive)); }
    // requires: (((s.accounts[i].capital) : Int)) + s.accounts[i].pnl ≥ (((0) : Int))
    if !(ctx.vault.accounts[i].capital + ctx.vault.accounts[i].pnl >= 0) { return Err(ProgramError::from(PercolatorError::AccountUnderwater)); }
    Ok(())
}

/// Guards for `reclaim_empty_account`.  
/// Generated from the `requires` clauses of the spec handler block.
pub fn reclaim_empty_account<'info>(ctx: &mut ReclaimEmptyAccount<'info>, i: usize) -> Result<(), ProgramError> {
    // requires: s.accounts[i].active = 1
    if !(ctx.vault.accounts[i].active == 1) { return Err(ProgramError::from(PercolatorError::SlotInactive)); }
    // requires: s.accounts[i].capital = 0
    debug_assert!(ctx.vault.accounts[i].capital == 0);
    // requires: s.accounts[i].reserved_pnl = 0
    debug_assert!(ctx.vault.accounts[i].reserved_pnl == 0);
    // requires: s.accounts[i].fee_credits = 0
    debug_assert!(ctx.vault.accounts[i].fee_credits == 0);
    Ok(())
}

/// Guards for `close_account`.  
/// Generated from the `requires` clauses of the spec handler block.
pub fn close_account<'info>(ctx: &mut CloseAccount<'info>, i: usize) -> Result<(), ProgramError> {
    // requires: s.accounts[i].active = 1
    if !(ctx.vault.accounts[i].active == 1) { return Err(ProgramError::from(PercolatorError::SlotInactive)); }
    // requires: s.V ≥ s.accounts[i].capital
    if !(ctx.vault.V >= ctx.vault.accounts[i].capital) { return Err(ProgramError::from(PercolatorError::InsufficientFunds)); }
    Ok(())
}

/// Guards for `deposit`.  
/// Generated from the `requires` clauses of the spec handler block.
pub fn deposit<'info>(ctx: &mut Deposit<'info>, i: usize, amount: u128) -> Result<(), ProgramError> {
    // requires: s.accounts[i].active = 1
    if !(ctx.vault.accounts[i].active == 1) { return Err(ProgramError::from(PercolatorError::SlotInactive)); }
    // requires: s.V + amount ≤ 10000000000000000
    if !(ctx.vault.V + amount <= 10000000000000000) { return Err(ProgramError::from(PercolatorError::VaultOverflow)); }
    Ok(())
}

/// Guards for `withdraw`.  
/// Generated from the `requires` clauses of the spec handler block.
pub fn withdraw<'info>(ctx: &mut Withdraw<'info>, i: usize, amount: u128) -> Result<(), ProgramError> {
    // requires: s.accounts[i].active = 1
    if !(ctx.vault.accounts[i].active == 1) { return Err(ProgramError::from(PercolatorError::SlotInactive)); }
    // requires: s.accounts[i].capital ≥ amount
    if !(ctx.vault.accounts[i].capital >= amount) { return Err(ProgramError::from(PercolatorError::InsufficientFunds)); }
    // requires: (((s.accounts[i].capital) : Int)) + s.accounts[i].pnl ≥ (((amount) : Int))
    if !(ctx.vault.accounts[i].capital + ctx.vault.accounts[i].pnl >= amount) { return Err(ProgramError::from(PercolatorError::InsufficientFunds)); }
    Ok(())
}

/// Guards for `top_up_insurance`.  
/// Generated from the `requires` clauses of the spec handler block.
pub fn top_up_insurance<'info>(ctx: &mut TopUpInsurance<'info>, amount: u128) -> Result<(), ProgramError> {
    // requires: s.V + amount ≤ 10000000000000000
    if !(ctx.vault.V + amount <= 10000000000000000) { return Err(ProgramError::from(PercolatorError::VaultOverflow)); }
    Ok(())
}

/// Guards for `deposit_fee_credits`.  
/// Generated from the `requires` clauses of the spec handler block.
pub fn deposit_fee_credits<'info>(ctx: &mut DepositFeeCredits<'info>, i: usize, amount: u128) -> Result<(), ProgramError> {
    // requires: s.accounts[i].active = 1
    if !(ctx.vault.accounts[i].active == 1) { return Err(ProgramError::from(PercolatorError::SlotInactive)); }
    // requires: s.V + amount ≤ 10000000000000000
    if !(ctx.vault.V + amount <= 10000000000000000) { return Err(ProgramError::from(PercolatorError::VaultOverflow)); }
    Ok(())
}

/// Guards for `convert_released_pnl`.  
/// Generated from the `requires` clauses of the spec handler block.
pub fn convert_released_pnl<'info>(ctx: &mut ConvertReleasedPnl<'info>, i: usize, x: u128) -> Result<(), ProgramError> {
    // requires: s.accounts[i].active = 1
    if !(ctx.vault.accounts[i].active == 1) { return Err(ProgramError::from(PercolatorError::SlotInactive)); }
    // requires: s.accounts[i].reserved_pnl ≥ x
    if !(ctx.vault.accounts[i].reserved_pnl >= x) { return Err(ProgramError::from(PercolatorError::InsufficientFunds)); }
    // requires: s.V ≥ x
    if !(ctx.vault.V >= x) { return Err(ProgramError::from(PercolatorError::InsufficientFunds)); }
    Ok(())
}

/// Guards for `execute_trade`.  
/// Generated from the `requires` clauses of the spec handler block.
pub fn execute_trade<'info>(ctx: &mut ExecuteTrade<'info>, a: usize, b: usize, size_q: i128, exec_price: u64) -> Result<(), ProgramError> {
    // requires: s.accounts[a].active = 1
    if !(ctx.vault.accounts[a].active == 1) { return Err(ProgramError::from(PercolatorError::SlotInactive)); }
    // requires: s.accounts[b].active = 1
    if !(ctx.vault.accounts[b].active == 1) { return Err(ProgramError::from(PercolatorError::SlotInactive)); }
    // requires: a ≠ b
    debug_assert!(a != b);
    // requires: (((size_q) * ((((exec_price) : Int)))) / (1000000)) ≤ (((100000000000000000000) : Int))
    debug_assert!(mul_div_floor_u128(size_q, exec_price, 1000000) <= 100000000000000000000);
    Ok(())
}

/// Guards for `liquidate_case_0`.  
/// Generated from the `requires` clauses of the spec handler block.
pub fn liquidate_case_0<'info>(ctx: &mut LiquidateCase0<'info>, i: usize) -> Result<(), ProgramError> {
    // requires: s.accounts[i].active = 1
    if !(ctx.vault.accounts[i].active == 1) { return Err(ProgramError::from(PercolatorError::SlotInactive)); }
    // requires: (((s.accounts[i].capital) : Int)) + s.accounts[i].pnl ≥ (((0) : Int))
    debug_assert!(ctx.vault.accounts[i].capital + ctx.vault.accounts[i].pnl >= 0);
    // requires: 0 = 1
    if !(false) { return Err(ProgramError::from(PercolatorError::AccountHealthy)); }
    Ok(())
}

/// Guards for `liquidate_case_1`.  
/// Generated from the `requires` clauses of the spec handler block.
pub fn liquidate_case_1<'info>(ctx: &mut LiquidateCase1<'info>, i: usize) -> Result<(), ProgramError> {
    // requires: s.accounts[i].active = 1
    if !(ctx.vault.accounts[i].active == 1) { return Err(ProgramError::from(PercolatorError::SlotInactive)); }
    // requires: ¬((((s.accounts[i].capital) : Int)) + s.accounts[i].pnl ≥ (((0) : Int)))
    debug_assert!(!(ctx.vault.accounts[i].capital + ctx.vault.accounts[i].pnl >= 0));
    // requires: (((s.accounts[i].capital) : Int)) + s.accounts[i].pnl + (((s.I) : Int)) ≥ (((0) : Int))
    debug_assert!(ctx.vault.accounts[i].capital + ctx.vault.accounts[i].pnl + ctx.vault.I >= 0);
    Ok(())
}

/// Guards for `liquidate_otherwise`.  
/// Generated from the `requires` clauses of the spec handler block.
pub fn liquidate_otherwise<'info>(ctx: &mut LiquidateOtherwise<'info>, i: usize) -> Result<(), ProgramError> {
    // requires: s.accounts[i].active = 1
    if !(ctx.vault.accounts[i].active == 1) { return Err(ProgramError::from(PercolatorError::SlotInactive)); }
    // requires: ¬((((s.accounts[i].capital) : Int)) + s.accounts[i].pnl ≥ (((0) : Int)))
    debug_assert!(!(ctx.vault.accounts[i].capital + ctx.vault.accounts[i].pnl >= 0));
    // requires: ¬((((s.accounts[i].capital) : Int)) + s.accounts[i].pnl + (((s.I) : Int)) ≥ (((0) : Int)))
    debug_assert!(!(ctx.vault.accounts[i].capital + ctx.vault.accounts[i].pnl + ctx.vault.I >= 0));
    // requires: 0 = 1
    if !(false) { return Err(ProgramError::from(PercolatorError::BankruptPosition)); }
    Ok(())
}

/// Guards for `settle_account`.  
/// Generated from the `requires` clauses of the spec handler block.
pub fn settle_account<'info>(ctx: &mut SettleAccount<'info>, i: usize) -> Result<(), ProgramError> {
    // requires: s.accounts[i].active = 1
    if !(ctx.vault.accounts[i].active == 1) { return Err(ProgramError::from(PercolatorError::SlotInactive)); }
    Ok(())
}

/// Guards for `trigger_adl`.  
/// Generated from the `requires` clauses of the spec handler block.
pub fn trigger_adl<'info>(ctx: &mut TriggerAdl<'info>) -> Result<(), ProgramError> {
    // No guards declared in spec — nothing to check.
    Ok(())
}

/// Guards for `complete_drain`.  
/// Generated from the `requires` clauses of the spec handler block.
pub fn complete_drain<'info>(ctx: &mut CompleteDrain<'info>) -> Result<(), ProgramError> {
    // No guards declared in spec — nothing to check.
    Ok(())
}

/// Guards for `reset`.  
/// Generated from the `requires` clauses of the spec handler block.
pub fn reset<'info>(ctx: &mut Reset<'info>) -> Result<(), ProgramError> {
    // No guards declared in spec — nothing to check.
    Ok(())
}

// ---- END GENERATED ----
