// ---- GENERATED BY QEDGEN — DO NOT EDIT ---- spec-hash:05ab8da85801148c
use quasar_lang::prelude::*;

#[account(discriminator = 1)]
pub struct PercolatorAccount {
    pub authority: Address,
    pub V: u128,
    pub I: u128,
    pub F: u128,
    pub accounts: [Account; 1024],
}

/// Program lifecycle states.
#[derive(Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
pub enum Status {
    Active = 0,
    Draining = 1,
    Resetting = 2,
}
// ---- END GENERATED ----
