-- Generated by qedgen lean-gen from transfer.qedspec
-- Source of truth: the .qedspec file. Regenerate with:
--   qedgen lean-gen --spec <spec>.qedspec --output <this-file>

import QEDGen
import TransferProg

open QEDGen.Solana.SBPF
open QEDGen.Solana.SBPF.Memory

namespace TransferSOL

-- Global constants (from prog module, not re-declared):
--   DATA_LENGTH_ZERO = 0
--   INSTRUCTION_DATA_LENGTH_EXPECTED = 8
--   NON_DUP_MARKER = 255
--   N_ACCOUNTS_EXPECTED = 3

-- Error constants
abbrev E_INVALID_ACCOUNT_COUNT : Nat := 1
abbrev E_DATA_LENGTH_NONZERO_SENDER : Nat := 2
abbrev E_DUPLICATE_ACCOUNT_RECIPIENT : Nat := 3
abbrev E_DATA_LENGTH_NONZERO_RECIPIENT : Nat := 4
abbrev E_DUPLICATE_ACCOUNT_SYSTEM_PROGRAM : Nat := 5
abbrev E_INVALID_INSTRUCTION_DATA_LENGTH : Nat := 6
abbrev E_INSUFFICIENT_LAMPORTS : Nat := 7

-- Offset constants
abbrev N_ACCOUNTS : Int := 0
abbrev SENDER_LAMPORTS : Int := 80
abbrev SENDER_DATA_LENGTH : Int := 88
abbrev RECIPIENT_DUP_MARKER : Int := 10344
abbrev RECIPIENT_DATA_LENGTH : Int := 10424
abbrev SYSTEM_PROGRAM_DUP_MARKER : Int := 20680
abbrev INSTRUCTION_DATA_LENGTH : Int := 31032
abbrev TRANSFER_AMOUNT : Int := 31040

-- Effective address lemmas
@[simp] theorem ea_N_ACCOUNTS (b : Nat) : effectiveAddr b N_ACCOUNTS = b := by
  unfold effectiveAddr N_ACCOUNTS; omega

@[simp] theorem ea_SENDER_LAMPORTS (b : Nat) : effectiveAddr b SENDER_LAMPORTS = b + 80 := by
  unfold effectiveAddr SENDER_LAMPORTS; omega

@[simp] theorem ea_SENDER_DATA_LENGTH (b : Nat) : effectiveAddr b SENDER_DATA_LENGTH = b + 88 := by
  unfold effectiveAddr SENDER_DATA_LENGTH; omega

@[simp] theorem ea_RECIPIENT_DUP_MARKER (b : Nat) : effectiveAddr b RECIPIENT_DUP_MARKER = b + 10344 := by
  unfold effectiveAddr RECIPIENT_DUP_MARKER; omega

@[simp] theorem ea_RECIPIENT_DATA_LENGTH (b : Nat) : effectiveAddr b RECIPIENT_DATA_LENGTH = b + 10424 := by
  unfold effectiveAddr RECIPIENT_DATA_LENGTH; omega

@[simp] theorem ea_SYSTEM_PROGRAM_DUP_MARKER (b : Nat) : effectiveAddr b SYSTEM_PROGRAM_DUP_MARKER = b + 20680 := by
  unfold effectiveAddr SYSTEM_PROGRAM_DUP_MARKER; omega

@[simp] theorem ea_INSTRUCTION_DATA_LENGTH (b : Nat) : effectiveAddr b INSTRUCTION_DATA_LENGTH = b + 31032 := by
  unfold effectiveAddr INSTRUCTION_DATA_LENGTH; omega

@[simp] theorem ea_TRANSFER_AMOUNT (b : Nat) : effectiveAddr b TRANSFER_AMOUNT = b + 31040 := by
  unfold effectiveAddr TRANSFER_AMOUNT; omega

-- Guard theorem stubs
-- Hypotheses derived from checks + layout. Fill proofs with wp_exec.

/-- Must have exactly 3 accounts -/
theorem rejects_wrong_account_count
    (inputAddr : Nat) (mem : Mem)
    (nAccounts : Nat)
    (h_nAccounts_val : readU64 mem inputAddr = nAccounts)
    (h_nAccounts_ne : nAccounts ≠ N_ACCOUNTS_EXPECTED)
    :
    (executeFn TransferProg.progAt (initState inputAddr mem) 6).exitCode
      = some E_INVALID_ACCOUNT_COUNT := sorry

/-- Sender data length must be zero -/
theorem rejects_sender_data_nonzero
    (inputAddr : Nat) (mem : Mem)
    (h_nAccounts : readU64 mem inputAddr = N_ACCOUNTS_EXPECTED)
    (senderDataLength : Nat)
    (h_senderDataLength_val : readU64 mem (inputAddr + 88) = senderDataLength)
    (h_senderDataLength_ne : senderDataLength ≠ DATA_LENGTH_ZERO)
    :
    (executeFn TransferProg.progAt (initState inputAddr mem) 8).exitCode
      = some E_DATA_LENGTH_NONZERO_SENDER := sorry

/-- Recipient must not be a duplicate account -/
theorem rejects_recipient_duplicate
    (inputAddr : Nat) (mem : Mem)
    (h_nAccounts : readU64 mem inputAddr = N_ACCOUNTS_EXPECTED)
    (h_senderDataLength : readU64 mem (inputAddr + 88) = DATA_LENGTH_ZERO)
    (recipientDupMarker : Nat)
    (h_recipientDupMarker_val : readU8 mem (inputAddr + 10344) = recipientDupMarker)
    (h_recipientDupMarker_ne : recipientDupMarker ≠ NON_DUP_MARKER)
    :
    (executeFn TransferProg.progAt (initState inputAddr mem) 10).exitCode
      = some E_DUPLICATE_ACCOUNT_RECIPIENT := sorry

/-- Recipient data length must be zero -/
theorem rejects_recipient_data_nonzero
    (inputAddr : Nat) (mem : Mem)
    (h_nAccounts : readU64 mem inputAddr = N_ACCOUNTS_EXPECTED)
    (h_senderDataLength : readU64 mem (inputAddr + 88) = DATA_LENGTH_ZERO)
    (h_recipientDupMarker : readU8 mem (inputAddr + 10344) = NON_DUP_MARKER)
    (recipientDataLength : Nat)
    (h_recipientDataLength_val : readU64 mem (inputAddr + 10424) = recipientDataLength)
    (h_recipientDataLength_ne : recipientDataLength ≠ DATA_LENGTH_ZERO)
    :
    (executeFn TransferProg.progAt (initState inputAddr mem) 12).exitCode
      = some E_DATA_LENGTH_NONZERO_RECIPIENT := sorry

/-- System program must not be a duplicate account -/
theorem rejects_system_program_duplicate
    (inputAddr : Nat) (mem : Mem)
    (h_nAccounts : readU64 mem inputAddr = N_ACCOUNTS_EXPECTED)
    (h_senderDataLength : readU64 mem (inputAddr + 88) = DATA_LENGTH_ZERO)
    (h_recipientDupMarker : readU8 mem (inputAddr + 10344) = NON_DUP_MARKER)
    (h_recipientDataLength : readU64 mem (inputAddr + 10424) = DATA_LENGTH_ZERO)
    (systemProgramDupMarker : Nat)
    (h_systemProgramDupMarker_val : readU8 mem (inputAddr + 20680) = systemProgramDupMarker)
    (h_systemProgramDupMarker_ne : systemProgramDupMarker ≠ NON_DUP_MARKER)
    :
    (executeFn TransferProg.progAt (initState inputAddr mem) 14).exitCode
      = some E_DUPLICATE_ACCOUNT_SYSTEM_PROGRAM := sorry

/-- Instruction data must be exactly 8 bytes -/
theorem rejects_invalid_instruction_data_length
    (inputAddr : Nat) (mem : Mem)
    (h_nAccounts : readU64 mem inputAddr = N_ACCOUNTS_EXPECTED)
    (h_senderDataLength : readU64 mem (inputAddr + 88) = DATA_LENGTH_ZERO)
    (h_recipientDupMarker : readU8 mem (inputAddr + 10344) = NON_DUP_MARKER)
    (h_recipientDataLength : readU64 mem (inputAddr + 10424) = DATA_LENGTH_ZERO)
    (h_systemProgramDupMarker : readU8 mem (inputAddr + 20680) = NON_DUP_MARKER)
    (instructionDataLength : Nat)
    (h_instructionDataLength_val : readU64 mem (inputAddr + 31032) = instructionDataLength)
    (h_instructionDataLength_ne : instructionDataLength ≠ INSTRUCTION_DATA_LENGTH_EXPECTED)
    :
    (executeFn TransferProg.progAt (initState inputAddr mem) 16).exitCode
      = some E_INVALID_INSTRUCTION_DATA_LENGTH := sorry

/-- Sender must have enough lamports for the transfer -/
theorem rejects_insufficient_lamports
    (inputAddr : Nat) (mem : Mem)
    (h_nAccounts : readU64 mem inputAddr = N_ACCOUNTS_EXPECTED)
    (h_senderDataLength : readU64 mem (inputAddr + 88) = DATA_LENGTH_ZERO)
    (h_recipientDupMarker : readU8 mem (inputAddr + 10344) = NON_DUP_MARKER)
    (h_recipientDataLength : readU64 mem (inputAddr + 10424) = DATA_LENGTH_ZERO)
    (h_systemProgramDupMarker : readU8 mem (inputAddr + 20680) = NON_DUP_MARKER)
    (h_instructionDataLength : readU64 mem (inputAddr + 31032) = INSTRUCTION_DATA_LENGTH_EXPECTED)
    (senderLamports : Nat)
    (h_senderLamports_val : readU64 mem (inputAddr + 80) = senderLamports)
    (transferAmount : Nat)
    (h_transferAmount_val : readU64 mem (inputAddr + 31040) = transferAmount)
    (h_senderLamports_lt : senderLamports < transferAmount)
    :
    (executeFn TransferProg.progAt (initState inputAddr mem) 20).exitCode
      = some E_INSUFFICIENT_LAMPORTS := sorry

-- Completeness structure: fill all fields to prove every guard is covered
structure Spec (progAt : Nat → Option Insn) where
  rejects_wrong_account_count :
    ∀ (inputAddr : Nat) (mem : Mem) (nAccounts : Nat) (_h_nAccounts_val : readU64 mem inputAddr = nAccounts) (_h_nAccounts_ne : nAccounts ≠ N_ACCOUNTS_EXPECTED),
    (executeFn progAt (initState inputAddr mem) 6).exitCode = some E_INVALID_ACCOUNT_COUNT
  rejects_sender_data_nonzero :
    ∀ (inputAddr : Nat) (mem : Mem) (_h_nAccounts : readU64 mem inputAddr = N_ACCOUNTS_EXPECTED) (senderDataLength : Nat) (_h_senderDataLength_val : readU64 mem (inputAddr + 88) = senderDataLength) (_h_senderDataLength_ne : senderDataLength ≠ DATA_LENGTH_ZERO),
    (executeFn progAt (initState inputAddr mem) 8).exitCode = some E_DATA_LENGTH_NONZERO_SENDER
  rejects_recipient_duplicate :
    ∀ (inputAddr : Nat) (mem : Mem) (_h_nAccounts : readU64 mem inputAddr = N_ACCOUNTS_EXPECTED) (_h_senderDataLength : readU64 mem (inputAddr + 88) = DATA_LENGTH_ZERO) (recipientDupMarker : Nat) (_h_recipientDupMarker_val : readU8 mem (inputAddr + 10344) = recipientDupMarker) (_h_recipientDupMarker_ne : recipientDupMarker ≠ NON_DUP_MARKER),
    (executeFn progAt (initState inputAddr mem) 10).exitCode = some E_DUPLICATE_ACCOUNT_RECIPIENT
  rejects_recipient_data_nonzero :
    ∀ (inputAddr : Nat) (mem : Mem) (_h_nAccounts : readU64 mem inputAddr = N_ACCOUNTS_EXPECTED) (_h_senderDataLength : readU64 mem (inputAddr + 88) = DATA_LENGTH_ZERO) (_h_recipientDupMarker : readU8 mem (inputAddr + 10344) = NON_DUP_MARKER) (recipientDataLength : Nat) (_h_recipientDataLength_val : readU64 mem (inputAddr + 10424) = recipientDataLength) (_h_recipientDataLength_ne : recipientDataLength ≠ DATA_LENGTH_ZERO),
    (executeFn progAt (initState inputAddr mem) 12).exitCode = some E_DATA_LENGTH_NONZERO_RECIPIENT
  rejects_system_program_duplicate :
    ∀ (inputAddr : Nat) (mem : Mem) (_h_nAccounts : readU64 mem inputAddr = N_ACCOUNTS_EXPECTED) (_h_senderDataLength : readU64 mem (inputAddr + 88) = DATA_LENGTH_ZERO) (_h_recipientDupMarker : readU8 mem (inputAddr + 10344) = NON_DUP_MARKER) (_h_recipientDataLength : readU64 mem (inputAddr + 10424) = DATA_LENGTH_ZERO) (systemProgramDupMarker : Nat) (_h_systemProgramDupMarker_val : readU8 mem (inputAddr + 20680) = systemProgramDupMarker) (_h_systemProgramDupMarker_ne : systemProgramDupMarker ≠ NON_DUP_MARKER),
    (executeFn progAt (initState inputAddr mem) 14).exitCode = some E_DUPLICATE_ACCOUNT_SYSTEM_PROGRAM
  rejects_invalid_instruction_data_length :
    ∀ (inputAddr : Nat) (mem : Mem) (_h_nAccounts : readU64 mem inputAddr = N_ACCOUNTS_EXPECTED) (_h_senderDataLength : readU64 mem (inputAddr + 88) = DATA_LENGTH_ZERO) (_h_recipientDupMarker : readU8 mem (inputAddr + 10344) = NON_DUP_MARKER) (_h_recipientDataLength : readU64 mem (inputAddr + 10424) = DATA_LENGTH_ZERO) (_h_systemProgramDupMarker : readU8 mem (inputAddr + 20680) = NON_DUP_MARKER) (instructionDataLength : Nat) (_h_instructionDataLength_val : readU64 mem (inputAddr + 31032) = instructionDataLength) (_h_instructionDataLength_ne : instructionDataLength ≠ INSTRUCTION_DATA_LENGTH_EXPECTED),
    (executeFn progAt (initState inputAddr mem) 16).exitCode = some E_INVALID_INSTRUCTION_DATA_LENGTH
  rejects_insufficient_lamports :
    ∀ (inputAddr : Nat) (mem : Mem) (_h_nAccounts : readU64 mem inputAddr = N_ACCOUNTS_EXPECTED) (_h_senderDataLength : readU64 mem (inputAddr + 88) = DATA_LENGTH_ZERO) (_h_recipientDupMarker : readU8 mem (inputAddr + 10344) = NON_DUP_MARKER) (_h_recipientDataLength : readU64 mem (inputAddr + 10424) = DATA_LENGTH_ZERO) (_h_systemProgramDupMarker : readU8 mem (inputAddr + 20680) = NON_DUP_MARKER) (_h_instructionDataLength : readU64 mem (inputAddr + 31032) = INSTRUCTION_DATA_LENGTH_EXPECTED) (senderLamports : Nat) (_h_senderLamports_val : readU64 mem (inputAddr + 80) = senderLamports) (transferAmount : Nat) (_h_transferAmount_val : readU64 mem (inputAddr + 31040) = transferAmount) (_h_senderLamports_lt : senderLamports < transferAmount),
    (executeFn progAt (initState inputAddr mem) 20).exitCode = some E_INSUFFICIENT_LAMPORTS

-- Property theorem stubs

/-- All guards pass → CPI + exit 0 -/
theorem accepts_valid_transfer : True := trivial

end TransferSOL
