// ---- GENERATED BY QEDGEN — DO NOT EDIT ---- spec-hash:484198670e308000
use quasar_lang::prelude::*;

#[event(discriminator = 1)]
pub struct PoolInitialized {
    pub authority: Address,
    pub rate: U64 ,
}

#[event(discriminator = 2)]
pub struct Deposited {
    pub depositor: Address,
    pub amount: U64 ,
}

#[event(discriminator = 3)]
pub struct Borrowed {
    pub borrower: Address,
    pub amount: U64 ,
}

#[event(discriminator = 4)]
pub struct Repaid {
    pub borrower: Address,
    pub amount: U64 ,
}

#[event(discriminator = 5)]
pub struct LoanLiquidated {
    pub borrower: Address,
    pub amount: U64 ,
}

// ---- END GENERATED ----
