// ---- GENERATED BY QEDGEN — DO NOT EDIT — regenerated from .qedspec ----
//! Per-handler guard checks derived from the `.qedspec`.
//! Called from user-owned `instructions/<name>::handler` before
//! business logic; keep guard logic here, policy-free logic there.

#![allow(unused_variables, unused_imports, dead_code, clippy::too_many_arguments)]

use quasar_lang::prelude::*;
use crate::errors::*;
use crate::instructions::*;

/// Guards for `initialize`.  
/// Generated from the `requires` clauses of the spec handler block.
pub fn initialize(ctx: &mut Initialize, deposit_amount: u64, receive_amount: u64) -> Result<(), ProgramError> {
    // requires: deposit_amount > 0 ∧ receive_amount > 0
    if !(deposit_amount > 0 && receive_amount > 0) { return Err(ProgramError::from(EscrowError::InvalidAmount)); }
    Ok(())
}

/// Guards for `exchange`.  
/// Generated from the `requires` clauses of the spec handler block.
pub fn exchange(ctx: &mut Exchange) -> Result<(), ProgramError> {
    // No guards declared in spec — nothing to check.
    Ok(())
}

/// Guards for `cancel`.  
/// Generated from the `requires` clauses of the spec handler block.
pub fn cancel(ctx: &mut Cancel) -> Result<(), ProgramError> {
    // No guards declared in spec — nothing to check.
    Ok(())
}

// ---- END GENERATED ----
