// ---- GENERATED BY QEDGEN — DO NOT EDIT ---- spec-hash:b5ac4c66e954c2ea
use quasar_lang::prelude::*;

#[account(discriminator = 1)]
pub struct EscrowAccount {
    pub initializer: Address,
    pub initializer_token_account: Address,
    pub taker: Address,
    pub initializer_amount: u64,
    pub taker_amount: u64,
    pub escrow_token_account: Address,
    pub bump: u8,
    pub status: u8,
}

/// Program lifecycle states.
#[derive(Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
pub enum Status {
    Uninitialized = 0,
    Open = 1,
    Closed = 2,
}
// ---- END GENERATED ----
