// ---- GENERATED BY QEDGEN — DO NOT EDIT ABOVE THIS LINE ---- spec-hash:7cac4b8c6c0d4598
use quasar_lang::prelude::*;
use crate::state::*;
use crate::events::*;
use crate::errors::*;

#[derive(Accounts)]
pub struct Deposit {
    #[account(mut)]
    pub depositor: Signer,
    #[account(mut, seeds = PoolAccount::seeds(pool), bump)]
    pub pool: Account<Pool>,
    #[account(mut, token::authority = pool)]
    pub pool_vault: Account<Token>,
    #[account(mut)]
    pub depositor_ta: Account<Token>,
    pub token_program: Program<Token>,
}

impl Deposit {
    /// Deposit tokens into the pool
    #[inline(always)]
    #[qed(verified, hash = "5af369bb254368d3")]
    pub fn handler(&mut self, amount: u64, bumps: &DepositBumps) -> Result<(), ProgramError> {
        // AGENT: implement business logic here
        // Spec guard: "amount > 0"
        // Spec effect: total_deposits add amount
        // Spec: emit!(Deposited)
        todo!()
    }
}
// ---- GENERATED BY QEDGEN — DO NOT EDIT BELOW THIS LINE ----
