// ---- GENERATED BY QEDGEN — DO NOT EDIT ABOVE THIS LINE ---- spec-hash:ae5acfeb508892f0
use quasar_lang::prelude::*;
use crate::state::*;
use crate::events::*;
use crate::errors::*;

#[derive(Accounts)]
pub struct Deposit {
    #[account(mut)]
    pub depositor: Signer,
    #[account(mut, seeds = LendingAccount::seeds(pool), bump)]
    pub pool: Account<()>,
    #[account(mut, token::authority = pool)]
    pub pool_vault: Account<Token>,
    #[account(mut)]
    pub depositor_ta: Account<Token>,
    pub token_program: Program<()>,
}

impl Deposit {
    /// Deposit tokens into the pool
    #[inline(always)]
    pub fn handler(&mut self, amount: u64, bumps: &DepositBumps) -> Result<(), ProgramError> {
        // AGENT: implement business logic here
        // Spec guard: "amount > 0"
        // Spec effect: total_deposits add amount
        // Spec: emit!(Deposited)
        todo!()
    }
}
// ---- GENERATED BY QEDGEN — DO NOT EDIT BELOW THIS LINE ----
