// ---- GENERATED BY QEDGEN — DO NOT EDIT ABOVE THIS LINE ---- spec-hash:9f6d1b2b50a85326
use quasar_lang::prelude::*;
use crate::state::*;
use crate::events::*;
use crate::errors::*;

#[derive(Accounts)]
pub struct InitPool {
    #[account(mut)]
    pub authority: Signer,
    #[account(init, payer = authority, seeds = PoolAccount::seeds(pool), bump)]
    pub pool: Account<Pool>,
    pub system_program: Program<System>,
}

impl InitPool {
    /// Initialize the lending pool with an interest rate
    #[inline(always)]
    #[qed(verified, hash = "b3a8119e013aa8fb")]
    pub fn handler(&mut self, rate: u64, bumps: &InitPoolBumps) -> Result<(), ProgramError> {
        // AGENT: implement business logic here
        // Spec guard: "rate > 0"
        // Spec effect: interest_rate set rate
        // Spec effect: total_deposits set 0
        // Spec effect: total_borrows set 0
        // Spec: emit!(PoolInitialized)
        todo!()
    }
}
// ---- GENERATED BY QEDGEN — DO NOT EDIT BELOW THIS LINE ----
