// ---- GENERATED BY QEDGEN — DO NOT EDIT ABOVE THIS LINE ---- spec-hash:c5d24342ddd052f7
use quasar_lang::prelude::*;
use crate::state::*;
use crate::events::*;
use crate::errors::*;

#[derive(Accounts)]
pub struct Liquidate {
    #[account(mut)]
    pub liquidator: Signer,
    #[account(mut, seeds = LoanAccount::seeds(loan), bump)]
    pub loan: Account<()>,
    #[account(mut, seeds = PoolAccount::seeds(pool), bump)]
    pub pool: Account<()>,
    #[account(mut, token::authority = pool)]
    pub pool_vault: Account<Token>,
    pub token_program: Program<()>,
}

impl Liquidate {
    /// Liquidate an undercollateralized loan
    #[inline(always)]
    pub fn handler(&mut self, bumps: &LiquidateBumps) -> Result<(), ProgramError> {
        // AGENT: implement business logic here
        // Spec effect: amount set 0
        // Spec: emit!(LoanLiquidated)
        todo!()
    }
}
// ---- GENERATED BY QEDGEN — DO NOT EDIT BELOW THIS LINE ----
