// ---- GENERATED BY QEDGEN — DO NOT EDIT ABOVE THIS LINE ---- spec-hash:19d85e7e02bbb207
use quasar_lang::prelude::*;
use crate::state::*;
use crate::events::*;
use crate::errors::*;

#[derive(Accounts)]
pub struct Repay {
    #[account(mut)]
    pub borrower: Signer,
    #[account(mut, seeds = LoanAccount::seeds(loan), bump, close = borrower)]
    pub loan: Account<Loan>,
    #[account(mut, seeds = PoolAccount::seeds(pool), bump)]
    pub pool: Account<Pool>,
    #[account(mut, token::authority = pool)]
    pub pool_vault: Account<Token>,
    #[account(mut)]
    pub borrower_ta: Account<Token>,
    pub token_program: Program<Token>,
}

impl Repay {
    /// Repay a loan in full
    #[inline(always)]
    pub fn handler(&mut self, bumps: &RepayBumps) -> Result<(), ProgramError> {
        // AGENT: implement business logic here
        // Spec effect: amount set 0
        // Spec effect: collateral set 0
        // Spec: emit!(Repaid)
        todo!()
    }
}
// ---- GENERATED BY QEDGEN — DO NOT EDIT BELOW THIS LINE ----
