// ---- GENERATED BY QEDGEN — DO NOT EDIT ABOVE THIS LINE ---- spec-hash:f5d3e9795920e389
use quasar_lang::prelude::*;
use crate::state::*;
use crate::events::*;
use crate::errors::*;

#[derive(Accounts)]
pub struct Borrow {
    #[account(mut)]
    pub borrower: Signer,
    #[account(mut, init, payer = borrower, seeds = LoanAccount::seeds(loan), bump)]
    pub loan: Account<()>,
    #[account(mut, init, payer = borrower, seeds = PoolAccount::seeds(pool), bump)]
    pub pool: Account<()>,
    #[account(mut, token::authority = pool)]
    pub pool_vault: Account<Token>,
    #[account(mut)]
    pub borrower_ta: Account<Token>,
    pub token_program: Program<()>,
    pub system_program: Program<()>,
}

impl Borrow {
    /// Borrow tokens from the pool against collateral
    #[inline(always)]
    pub fn handler(&mut self, amount: u64, collateral: u64, bumps: &BorrowBumps) -> Result<(), ProgramError> {
        // AGENT: implement business logic here
        // Spec effect: amount set amount
        // Spec effect: collateral set collateral
        // Spec: emit!(Borrowed)
        todo!()
    }
}
// ---- GENERATED BY QEDGEN — DO NOT EDIT BELOW THIS LINE ----
