// ---- GENERATED BY QEDGEN — DO NOT EDIT ---- spec-hash:1857eaed3d5aba1b
// Parallax integration test scaffold.
// Tests run against the compiled .so binary via parallax-svm/LiteSVM.
//
// AGENT: fill instruction builder data and assertions marked with todo!().
//
// Prerequisites:
//   1. Build your program: cargo build-sbf (or cargo build --target bpfel-unknown-none)
//   2. Run tests: cargo test --features client
//
// Dev-dependencies (add to Cargo.toml):
//   [dev-dependencies]
//   parallax-svm = { git = "https://github.com/blueshift-gg/parallax", rev = "804c5662832c65330e7299901cc5195a78d87256" }
//   solana-sdk-ids = "3.1"
//   # Parallax 0.1 compatibility pins; dependency Cargo.lock files are not inherited.
//   solana-address = "=2.6.1"
//   solana-hash = "=4.5.0"
//   solana-nonce = "=3.2.0"
//   solana-short-vec = "=3.2.2"
//   solana-last-restart-slot = "=3.1.0"
//   solana-slot-history = "=3.1.0"
//   solana-epoch-rewards = "=3.1.0"
//   solana-slot-hashes = "=3.1.0"
//   spl-token = { version = "=9.0.0", default-features = false, features = ["no-entrypoint"] }
//   wincode = { version = "0.5", features = ["derive"] }

extern crate std;
use {
    multisig as program, parallax_svm::prelude::*, program::client::*, program::state::*, std::vec,
};

// ── Setup ────────────────────────────────────────────────────────

fn setup() -> Ctx {
    Ctx::builder(program::ID)
        .crate_name(env!("CARGO_PKG_NAME"))
        .build()
        .expect("load compiled program into Parallax")
}

// ── Account helpers ──────────────────────────────────────────────

#[allow(dead_code)]
fn signer_account(address: Pubkey) -> Account {
    Account::new(address, system_program::ID, DEFAULT_WALLET_LAMPORTS, vec![])
}

#[allow(dead_code)]
fn empty_account(address: Pubkey) -> Account {
    Account::new(address, system_program::ID, 0, vec![])
}
/// Create a pre-populated MultisigAccount account (program-owned).
#[allow(dead_code)]
fn state_account(
    address: Pubkey,
    creator: Pubkey,
    threshold: u8,
    member_count: u8,
    members: [Pubkey; 32],
    voted: [u8; 32],
    approval_count: u8,
    rejection_count: u8,
    bump: u8,
) -> Account {
    let state = MultisigAccount {
        creator,
        threshold,
        member_count,
        members,
        voted,
        approval_count,
        rejection_count,
        bump,
    };
    Account {
        address,
        lamports: 2_000_000,
        data: wincode::serialize(&state).unwrap(),
        owner: program::ID,
        executable: false,
    }
}

// ── create_vault ──

#[test]
fn test_create_vault() {
    let mut ctx = setup();

    // Account addresses
    let system_program = system_program::ID;
    let creator = Pubkey::new_unique();
    let (vault, _vault_bump) =
        Pubkey::find_program_address(&[b"vault", creator.as_ref()], &program::ID);

    // Instruction parameters
    let threshold: u8 = 1; // AGENT: set appropriate value
    let member_count: u8 = 1; // AGENT: set appropriate value

    let instruction: Instruction = CreateVaultInstruction {
        creator,
        vault,
        system_program,
        threshold,
        member_count,
    }
    .into();

    let outcome = ctx.execute_with(
        instruction,
        vec![signer_account(creator), empty_account(vault)],
    );

    outcome.check(Outcome::success()); // create_vault

    // AGENT: verify account state after instruction
    // let vault_data = &outcome.account(vault).unwrap().data;
    // Spec effect: threshold set threshold
    // Spec effect: member_count set member_count
    // Spec effect: approval_count set 0
    // Spec effect: rejection_count set 0

    // AGENT: pin a compute budget once measured, e.g.
    //   outcome.check(Cu::spent(|cu| cu <= 20_000));
}

// ── propose ──

#[test]
fn test_propose() {
    let mut ctx = setup();

    // Account addresses
    let creator = Pubkey::new_unique();
    let (vault, _vault_bump) =
        Pubkey::find_program_address(&[b"vault", creator.as_ref()], &program::ID);

    let instruction: Instruction = ProposeInstruction { creator, vault }.into();

    let outcome = ctx.execute_with(
        instruction,
        vec![
            signer_account(creator),
            empty_account(vault), /* AGENT: use state_account() with appropriate fields */
        ],
    );

    outcome.check(Outcome::success()); // propose

    // AGENT: verify account state after instruction
    // let vault_data = &outcome.account(vault).unwrap().data;
    // Spec effect: approval_count set 0
    // Spec effect: rejection_count set 0

    // AGENT: pin a compute budget once measured, e.g.
    //   outcome.check(Cu::spent(|cu| cu <= 20_000));
}

// ── approve ──

#[test]
fn test_approve() {
    let mut ctx = setup();

    // Account addresses
    let creator = Pubkey::new_unique(); // AGENT: replace with the creator from pre-state
    let approver = Pubkey::new_unique();
    let (vault, _vault_bump) =
        Pubkey::find_program_address(&[b"vault", creator.as_ref()], &program::ID);

    // Instruction parameters
    let member_index: u8 = 1; // AGENT: set appropriate value

    let instruction: Instruction = ApproveInstruction {
        approver,
        vault,
        member_index,
    }
    .into();

    let outcome = ctx.execute_with(
        instruction,
        vec![
            signer_account(approver),
            empty_account(vault), /* AGENT: use state_account() with appropriate fields */
        ],
    );

    outcome.check(Outcome::success()); // approve

    // AGENT: verify account state after instruction
    // let vault_data = &outcome.account(vault).unwrap().data;
    // Spec effect: approval_count add 1
    // Spec effect: voted[member_index] set 1

    // AGENT: pin a compute budget once measured, e.g.
    //   outcome.check(Cu::spent(|cu| cu <= 20_000));
}

// ── reject ──

#[test]
fn test_reject() {
    let mut ctx = setup();

    // Account addresses
    let creator = Pubkey::new_unique(); // AGENT: replace with the creator from pre-state
    let rejecter = Pubkey::new_unique();
    let (vault, _vault_bump) =
        Pubkey::find_program_address(&[b"vault", creator.as_ref()], &program::ID);

    // Instruction parameters
    let member_index: u8 = 1; // AGENT: set appropriate value

    let instruction: Instruction = RejectInstruction {
        rejecter,
        vault,
        member_index,
    }
    .into();

    let outcome = ctx.execute_with(
        instruction,
        vec![
            signer_account(rejecter),
            empty_account(vault), /* AGENT: use state_account() with appropriate fields */
        ],
    );

    outcome.check(Outcome::success()); // reject

    // AGENT: verify account state after instruction
    // let vault_data = &outcome.account(vault).unwrap().data;
    // Spec effect: rejection_count add 1
    // Spec effect: voted[member_index] set 1

    // AGENT: pin a compute budget once measured, e.g.
    //   outcome.check(Cu::spent(|cu| cu <= 20_000));
}

// ── execute ──

#[test]
fn test_execute() {
    let mut ctx = setup();

    // Account addresses
    let creator = Pubkey::new_unique(); // AGENT: replace with the creator from pre-state
    let executor = Pubkey::new_unique();
    let (vault, _vault_bump) =
        Pubkey::find_program_address(&[b"vault", creator.as_ref()], &program::ID);

    // Instruction parameters
    let member_index: u8 = 1; // AGENT: set appropriate value

    let instruction: Instruction = ExecuteInstruction {
        executor,
        vault,
        member_index,
    }
    .into();

    let outcome = ctx.execute_with(
        instruction,
        vec![
            signer_account(executor),
            empty_account(vault), /* AGENT: use state_account() with appropriate fields */
        ],
    );

    outcome.check(Outcome::success()); // execute

    // AGENT: verify account state after instruction
    // let vault_data = &outcome.account(vault).unwrap().data;
    // Spec effect: approval_count set 0
    // Spec effect: rejection_count set 0

    // AGENT: pin a compute budget once measured, e.g.
    //   outcome.check(Cu::spent(|cu| cu <= 20_000));
}

// ── cancel_proposal ──

#[test]
fn test_cancel_proposal() {
    let mut ctx = setup();

    // Account addresses
    let creator = Pubkey::new_unique(); // AGENT: replace with the creator from pre-state
    let canceller = Pubkey::new_unique();
    let (vault, _vault_bump) =
        Pubkey::find_program_address(&[b"vault", creator.as_ref()], &program::ID);

    let instruction: Instruction = CancelProposalInstruction { canceller, vault }.into();

    let outcome = ctx.execute_with(
        instruction,
        vec![
            signer_account(canceller),
            empty_account(vault), /* AGENT: use state_account() with appropriate fields */
        ],
    );

    outcome.check(Outcome::success()); // cancel_proposal

    // AGENT: verify account state after instruction
    // let vault_data = &outcome.account(vault).unwrap().data;
    // Spec effect: approval_count set 0
    // Spec effect: rejection_count set 0

    // AGENT: pin a compute budget once measured, e.g.
    //   outcome.check(Cu::spent(|cu| cu <= 20_000));
}

// ── add_member ──

#[test]
fn test_add_member() {
    let mut ctx = setup();

    // Account addresses
    let creator = Pubkey::new_unique();
    let (vault, _vault_bump) =
        Pubkey::find_program_address(&[b"vault", creator.as_ref()], &program::ID);

    // Instruction parameters
    let member_index: u8 = 1; // AGENT: set appropriate value
    let member_pubkey: [u8; 32] = todo!(); // AGENT: set appropriate value

    let instruction: Instruction = AddMemberInstruction {
        creator,
        vault,
        member_index,
        member_pubkey,
    }
    .into();

    let outcome = ctx.execute_with(
        instruction,
        vec![
            signer_account(creator),
            empty_account(vault), /* AGENT: use state_account() with appropriate fields */
        ],
    );

    outcome.check(Outcome::success()); // add_member

    // AGENT: verify account state after instruction
    // let vault_data = &outcome.account(vault).unwrap().data;
    // Spec effect: members[member_index] set member_pubkey

    // AGENT: pin a compute budget once measured, e.g.
    //   outcome.check(Cu::spent(|cu| cu <= 20_000));
}

// ── remove_member ──

#[test]
fn test_remove_member() {
    let mut ctx = setup();

    // Account addresses
    let creator = Pubkey::new_unique();
    let (vault, _vault_bump) =
        Pubkey::find_program_address(&[b"vault", creator.as_ref()], &program::ID);

    let instruction: Instruction = RemoveMemberInstruction { creator, vault }.into();

    let outcome = ctx.execute_with(
        instruction,
        vec![
            signer_account(creator),
            empty_account(vault), /* AGENT: use state_account() with appropriate fields */
        ],
    );

    outcome.check(Outcome::success()); // remove_member

    // AGENT: verify account state after instruction
    // let vault_data = &outcome.account(vault).unwrap().data;
    // Spec effect: member_count sub 1

    // AGENT: pin a compute budget once measured, e.g.
    //   outcome.check(Cu::spent(|cu| cu <= 20_000));
}

/// create_vault must reject unauthorized callers (wrong creator).
#[test]
fn test_create_vault_unauthorized() {
    let mut ctx = setup();

    let system_program = system_program::ID;
    let wrong_creator = Pubkey::new_unique();
    let vault = Pubkey::new_unique();

    let instruction: Instruction = CreateVaultInstruction {
        creator: wrong_creator,
        vault,
        system_program,
        threshold: 1,
        member_count: 1,
    }
    .into();

    let outcome = ctx.execute_with(
        instruction,
        vec![signer_account(wrong_creator), empty_account(vault)],
    );

    // AGENT: the spec declares no authorization error, so this only
    // asserts that SOME error fired — it also passes on a deserialization
    // or missing-account failure. Declare the error in the spec, then
    // assert it with `outcome.check(Outcome::error(..))`.
    assert!(outcome.is_err(), "create_vault should reject wrong creator");
}

/// propose must reject unauthorized callers (wrong creator).
#[test]
fn test_propose_unauthorized() {
    let mut ctx = setup();

    let wrong_creator = Pubkey::new_unique();
    let vault = Pubkey::new_unique();

    let instruction: Instruction = ProposeInstruction {
        creator: wrong_creator,
        vault,
    }
    .into();

    let outcome = ctx.execute_with(
        instruction,
        vec![
            signer_account(wrong_creator),
            empty_account(vault), /* AGENT: use state_account() with appropriate fields */
        ],
    );

    // AGENT: the spec declares no authorization error, so this only
    // asserts that SOME error fired — it also passes on a deserialization
    // or missing-account failure. Declare the error in the spec, then
    // assert it with `outcome.check(Outcome::error(..))`.
    assert!(outcome.is_err(), "propose should reject wrong creator");
}

/// approve must reject unauthorized callers (wrong approver).
#[test]
fn test_approve_unauthorized() {
    let mut ctx = setup();

    let wrong_approver = Pubkey::new_unique();
    let vault = Pubkey::new_unique();

    let instruction: Instruction = ApproveInstruction {
        approver: wrong_approver,
        vault,
        member_index: 1,
    }
    .into();

    let outcome = ctx.execute_with(
        instruction,
        vec![
            signer_account(wrong_approver),
            empty_account(vault), /* AGENT: use state_account() with appropriate fields */
        ],
    );

    // AGENT: the spec declares no authorization error, so this only
    // asserts that SOME error fired — it also passes on a deserialization
    // or missing-account failure. Declare the error in the spec, then
    // assert it with `outcome.check(Outcome::error(..))`.
    assert!(outcome.is_err(), "approve should reject wrong approver");
}

/// reject must reject unauthorized callers (wrong rejecter).
#[test]
fn test_reject_unauthorized() {
    let mut ctx = setup();

    let wrong_rejecter = Pubkey::new_unique();
    let vault = Pubkey::new_unique();

    let instruction: Instruction = RejectInstruction {
        rejecter: wrong_rejecter,
        vault,
        member_index: 1,
    }
    .into();

    let outcome = ctx.execute_with(
        instruction,
        vec![
            signer_account(wrong_rejecter),
            empty_account(vault), /* AGENT: use state_account() with appropriate fields */
        ],
    );

    // AGENT: the spec declares no authorization error, so this only
    // asserts that SOME error fired — it also passes on a deserialization
    // or missing-account failure. Declare the error in the spec, then
    // assert it with `outcome.check(Outcome::error(..))`.
    assert!(outcome.is_err(), "reject should reject wrong rejecter");
}

/// execute must reject unauthorized callers (wrong executor).
#[test]
fn test_execute_unauthorized() {
    let mut ctx = setup();

    let wrong_executor = Pubkey::new_unique();
    let vault = Pubkey::new_unique();

    let instruction: Instruction = ExecuteInstruction {
        executor: wrong_executor,
        vault,
        member_index: 1,
    }
    .into();

    let outcome = ctx.execute_with(
        instruction,
        vec![
            signer_account(wrong_executor),
            empty_account(vault), /* AGENT: use state_account() with appropriate fields */
        ],
    );

    // AGENT: the spec declares no authorization error, so this only
    // asserts that SOME error fired — it also passes on a deserialization
    // or missing-account failure. Declare the error in the spec, then
    // assert it with `outcome.check(Outcome::error(..))`.
    assert!(outcome.is_err(), "execute should reject wrong executor");
}

/// add_member must reject unauthorized callers (wrong creator).
#[test]
fn test_add_member_unauthorized() {
    let mut ctx = setup();

    let wrong_creator = Pubkey::new_unique();
    let vault = Pubkey::new_unique();

    let instruction: Instruction = AddMemberInstruction {
        creator: wrong_creator,
        vault,
        member_index: 1,
        member_pubkey: todo!(),
    }
    .into();

    let outcome = ctx.execute_with(
        instruction,
        vec![
            signer_account(wrong_creator),
            empty_account(vault), /* AGENT: use state_account() with appropriate fields */
        ],
    );

    // AGENT: the spec declares no authorization error, so this only
    // asserts that SOME error fired — it also passes on a deserialization
    // or missing-account failure. Declare the error in the spec, then
    // assert it with `outcome.check(Outcome::error(..))`.
    assert!(outcome.is_err(), "add_member should reject wrong creator");
}

/// remove_member must reject unauthorized callers (wrong creator).
#[test]
fn test_remove_member_unauthorized() {
    let mut ctx = setup();

    let wrong_creator = Pubkey::new_unique();
    let vault = Pubkey::new_unique();

    let instruction: Instruction = RemoveMemberInstruction {
        creator: wrong_creator,
        vault,
    }
    .into();

    let outcome = ctx.execute_with(
        instruction,
        vec![
            signer_account(wrong_creator),
            empty_account(vault), /* AGENT: use state_account() with appropriate fields */
        ],
    );

    // AGENT: the spec declares no authorization error, so this only
    // asserts that SOME error fired — it also passes on a deserialization
    // or missing-account failure. Declare the error in the spec, then
    // assert it with `outcome.check(Outcome::error(..))`.
    assert!(
        outcome.is_err(),
        "remove_member should reject wrong creator"
    );
}

// ── Lifecycle sequence ────────────────────────────────────────────

/// End-to-end lifecycle: execute operations in spec order.
/// AGENT: fill in instruction parameters and account setup for each step.
#[test]
#[allow(unused_mut, unused_variables)] // until the sequence is filled in
fn test_lifecycle_sequence() {
    let mut ctx = setup();

    // Lifecycle transitions:
    //   create_vault : Uninitialized → Active
    //   propose : Active → HasProposal
    //   approve : HasProposal → HasProposal
    //   reject : HasProposal → HasProposal
    //   execute : HasProposal → Active
    //   cancel_proposal : HasProposal → Active
    //   add_member : Active → Active
    //   remove_member : Active → Active

    // Step 1: create_vault (Uninitialized → Active)
    // AGENT: build and execute create_vault instruction
    todo!("build instruction sequence");
}
