// ---- GENERATED BY QEDGEN ---- spec-hash:7cef849f69775ace
//
// Self-contained Kani proof harnesses for the Multisig spec.
//
// These proofs verify the spec's transition design using Kani bounded model
// checking. They operate on a pure model of the state machine (derived from
// the qedspec), independent of framework (Quasar/Anchor) types.
//
//   Lean proves:  transition functions preserve invariants (∀ states)
//   Kani checks:  same properties via bounded model checking + overflow detection
//   Together:     high assurance that the spec design is correct
//
// To run:  cargo kani --harness <name>   (requires cargo-kani)
// ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----
#![cfg(kani)]

// ============================================================================
// State model (derived from multisig.qedspec — no framework dependencies)
// ============================================================================

const MAX_MEMBERS: u8 = 32;

#[derive(Clone, Copy)]
struct State {
    threshold: u8,
    member_count: u8,
    approval_count: u8,
}

// ============================================================================
// Property predicates (from qedspec `property` declarations)
// ============================================================================

/// threshold_bounded: 0 < threshold ≤ member_count
fn threshold_bounded(s: &State) -> bool {
    s.threshold > 0 && s.threshold <= s.member_count
}

/// approvals_bounded: approval_count ≤ member_count
fn approvals_bounded(s: &State) -> bool {
    s.approval_count <= s.member_count
}

// ============================================================================
// Transition functions (from qedspec operations — effects + guards)
//
// Each returns true if the guard passes and the transition fires,
// false if the guard rejects the operation.
// ============================================================================

/// create_vault: Uninitialized → Active
/// guard: threshold > 0 ∧ threshold ≤ member_count ∧ member_count ≤ MAX_MEMBERS
/// effect: threshold ← threshold, member_count ← member_count, approval_count ← 0
fn create_vault(s: &mut State, threshold: u8, member_count: u8) -> bool {
    if !(threshold > 0 && threshold <= member_count && member_count <= MAX_MEMBERS) {
        return false;
    }
    s.threshold = threshold;
    s.member_count = member_count;
    s.approval_count = 0;
    true
}

/// propose: Active → HasProposal
/// guard: (none)
/// effect: approval_count ← 0
fn propose(s: &mut State) -> bool {
    s.approval_count = 0;
    true
}

/// approve: HasProposal → HasProposal
/// guard: member_index < member_count
/// effect: approval_count += 1
fn approve(s: &mut State, member_index: u8) -> bool {
    if member_index >= s.member_count {
        return false;
    }
    s.approval_count += 1; // overflow caught by Kani if invariants are wrong
    true
}

/// execute: HasProposal → Active
/// guard: approval_count ≥ threshold
/// effect: approval_count ← 0
fn execute(s: &mut State) -> bool {
    if s.approval_count < s.threshold {
        return false;
    }
    s.approval_count = 0;
    true
}

/// cancel_proposal: HasProposal → Active
/// guard: (none)
/// effect: approval_count ← 0
fn cancel_proposal(s: &mut State) -> bool {
    s.approval_count = 0;
    true
}

/// remove_member: Active → Active
/// guard: member_count > threshold
/// effect: member_count -= 1
fn remove_member(s: &mut State) -> bool {
    if s.member_count <= s.threshold {
        return false;
    }
    s.member_count -= 1; // safe: guard ensures member_count > threshold ≥ 1
    true
}

// ============================================================================
// Guard enforcement — transitions reject invalid inputs
// ============================================================================

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_create_vault_rejects_invalid() {
    let threshold: u8 = kani::any();
    let member_count: u8 = kani::any();
    kani::assume(!(threshold > 0 && threshold <= member_count && member_count <= MAX_MEMBERS));
    let mut s = State { threshold: 0, member_count: 0, approval_count: 0 };
    assert!(!create_vault(&mut s, threshold, member_count),
        "create_vault must reject when guard is violated");
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_approve_rejects_invalid() {
    let mut s = State {
        threshold: kani::any(),
        member_count: kani::any(),
        approval_count: kani::any(),
    };
    let member_index: u8 = kani::any();
    kani::assume(member_index >= s.member_count);
    assert!(!approve(&mut s, member_index),
        "approve must reject when member_index >= member_count");
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_execute_rejects_invalid() {
    let mut s = State {
        threshold: kani::any(),
        member_count: kani::any(),
        approval_count: kani::any(),
    };
    kani::assume(s.approval_count < s.threshold);
    assert!(!execute(&mut s),
        "execute must reject when approval_count < threshold");
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_remove_member_rejects_invalid() {
    let mut s = State {
        threshold: kani::any(),
        member_count: kani::any(),
        approval_count: kani::any(),
    };
    kani::assume(s.member_count <= s.threshold);
    assert!(!remove_member(&mut s),
        "remove_member must reject when member_count <= threshold");
}

// ============================================================================
// Property preservation — threshold_bounded
//   "0 < threshold ≤ member_count" preserved by all operations
// ============================================================================

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_create_vault_preserves_threshold_bounded() {
    let threshold: u8 = kani::any();
    let member_count: u8 = kani::any();
    // create_vault initialises state — no pre-invariant needed
    let mut s = State { threshold: 0, member_count: 0, approval_count: 0 };
    if create_vault(&mut s, threshold, member_count) {
        assert!(threshold_bounded(&s),
            "threshold_bounded must hold after create_vault");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_propose_preserves_threshold_bounded() {
    let mut s = State {
        threshold: kani::any(),
        member_count: kani::any(),
        approval_count: kani::any(),
    };
    kani::assume(threshold_bounded(&s));
    if propose(&mut s) {
        assert!(threshold_bounded(&s),
            "threshold_bounded must hold after propose");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_approve_preserves_threshold_bounded() {
    let mut s = State {
        threshold: kani::any(),
        member_count: kani::any(),
        approval_count: kani::any(),
    };
    kani::assume(threshold_bounded(&s));
    kani::assume(approvals_bounded(&s));
    kani::assume(s.member_count <= MAX_MEMBERS);
    let member_index: u8 = kani::any();
    if approve(&mut s, member_index) {
        assert!(threshold_bounded(&s),
            "threshold_bounded must hold after approve");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_execute_preserves_threshold_bounded() {
    let mut s = State {
        threshold: kani::any(),
        member_count: kani::any(),
        approval_count: kani::any(),
    };
    kani::assume(threshold_bounded(&s));
    if execute(&mut s) {
        assert!(threshold_bounded(&s),
            "threshold_bounded must hold after execute");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_cancel_proposal_preserves_threshold_bounded() {
    let mut s = State {
        threshold: kani::any(),
        member_count: kani::any(),
        approval_count: kani::any(),
    };
    kani::assume(threshold_bounded(&s));
    if cancel_proposal(&mut s) {
        assert!(threshold_bounded(&s),
            "threshold_bounded must hold after cancel_proposal");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_remove_member_preserves_threshold_bounded() {
    let mut s = State {
        threshold: kani::any(),
        member_count: kani::any(),
        approval_count: kani::any(),
    };
    kani::assume(threshold_bounded(&s));
    if remove_member(&mut s) {
        assert!(threshold_bounded(&s),
            "threshold_bounded must hold after remove_member");
    }
}

// ============================================================================
// Property preservation — approvals_bounded
//   "approval_count ≤ member_count" preserved by
//   [create_vault, propose, approve, execute, cancel_proposal]
// ============================================================================

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_create_vault_preserves_approvals_bounded() {
    let threshold: u8 = kani::any();
    let member_count: u8 = kani::any();
    let mut s = State { threshold: 0, member_count: 0, approval_count: 0 };
    if create_vault(&mut s, threshold, member_count) {
        assert!(approvals_bounded(&s),
            "approvals_bounded must hold after create_vault");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_propose_preserves_approvals_bounded() {
    let mut s = State {
        threshold: kani::any(),
        member_count: kani::any(),
        approval_count: kani::any(),
    };
    kani::assume(approvals_bounded(&s));
    if propose(&mut s) {
        assert!(approvals_bounded(&s),
            "approvals_bounded must hold after propose");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_approve_preserves_approvals_bounded() {
    let mut s = State {
        threshold: kani::any(),
        member_count: kani::any(),
        approval_count: kani::any(),
    };
    // Need: approval_count < member_count (strictly less, since we add 1).
    // This is guaranteed because each member approves at most once,
    // so approval_count < member_count always holds when approve is called.
    // The weaker approvals_bounded (<=) plus member_count <= MAX_MEMBERS
    // prevents u8 overflow; the strict bound ensures the property is preserved.
    kani::assume(approvals_bounded(&s));
    kani::assume(s.approval_count < s.member_count); // each member approves once
    kani::assume(s.member_count <= MAX_MEMBERS);
    let member_index: u8 = kani::any();
    if approve(&mut s, member_index) {
        assert!(approvals_bounded(&s),
            "approvals_bounded must hold after approve");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_execute_preserves_approvals_bounded() {
    let mut s = State {
        threshold: kani::any(),
        member_count: kani::any(),
        approval_count: kani::any(),
    };
    kani::assume(approvals_bounded(&s));
    if execute(&mut s) {
        assert!(approvals_bounded(&s),
            "approvals_bounded must hold after execute");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_cancel_proposal_preserves_approvals_bounded() {
    let mut s = State {
        threshold: kani::any(),
        member_count: kani::any(),
        approval_count: kani::any(),
    };
    kani::assume(approvals_bounded(&s));
    if cancel_proposal(&mut s) {
        assert!(approvals_bounded(&s),
            "approvals_bounded must hold after cancel_proposal");
    }
}

// ============================================================================
// Effect conformance — verify transition effects match spec
//
// Each proof applies a transition to symbolic state and checks that every
// field changed/unchanged matches the spec's effect: declarations.
// ============================================================================

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_create_vault_effects() {
    let threshold: u8 = kani::any();
    let member_count: u8 = kani::any();
    let mut s = State { threshold: 0, member_count: 0, approval_count: 0 };
    if create_vault(&mut s, threshold, member_count) {
        assert!(s.threshold == threshold, "threshold must equal input threshold");
        assert!(s.member_count == member_count, "member_count must equal input member_count");
        assert!(s.approval_count == 0, "approval_count must be 0");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_propose_effects() {
    let mut s = State {
        threshold: kani::any(),
        member_count: kani::any(),
        approval_count: kani::any(),
    };
    let pre_threshold = s.threshold;
    let pre_member_count = s.member_count;
    if propose(&mut s) {
        assert!(s.approval_count == 0, "approval_count must be reset to 0");
        assert!(s.threshold == pre_threshold, "threshold must not change");
        assert!(s.member_count == pre_member_count, "member_count must not change");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_approve_effects() {
    let mut s = State {
        threshold: kani::any(),
        member_count: kani::any(),
        approval_count: kani::any(),
    };
    kani::assume(s.member_count <= MAX_MEMBERS);
    kani::assume(s.approval_count < s.member_count);
    let pre_threshold = s.threshold;
    let pre_member_count = s.member_count;
    let pre_approval_count = s.approval_count;
    let member_index: u8 = kani::any();
    if approve(&mut s, member_index) {
        assert!(s.approval_count == pre_approval_count + 1, "approval_count must increment by 1");
        assert!(s.threshold == pre_threshold, "threshold must not change");
        assert!(s.member_count == pre_member_count, "member_count must not change");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_execute_effects() {
    let mut s = State {
        threshold: kani::any(),
        member_count: kani::any(),
        approval_count: kani::any(),
    };
    let pre_threshold = s.threshold;
    let pre_member_count = s.member_count;
    if execute(&mut s) {
        assert!(s.approval_count == 0, "approval_count must be reset to 0");
        assert!(s.threshold == pre_threshold, "threshold must not change");
        assert!(s.member_count == pre_member_count, "member_count must not change");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_cancel_proposal_effects() {
    let mut s = State {
        threshold: kani::any(),
        member_count: kani::any(),
        approval_count: kani::any(),
    };
    let pre_threshold = s.threshold;
    let pre_member_count = s.member_count;
    if cancel_proposal(&mut s) {
        assert!(s.approval_count == 0, "approval_count must be reset to 0");
        assert!(s.threshold == pre_threshold, "threshold must not change");
        assert!(s.member_count == pre_member_count, "member_count must not change");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_remove_member_effects() {
    let mut s = State {
        threshold: kani::any(),
        member_count: kani::any(),
        approval_count: kani::any(),
    };
    let pre_threshold = s.threshold;
    let pre_member_count = s.member_count;
    let pre_approval_count = s.approval_count;
    if remove_member(&mut s) {
        assert!(s.member_count == pre_member_count - 1, "member_count must decrement by 1");
        assert!(s.threshold == pre_threshold, "threshold must not change");
        assert!(s.approval_count == pre_approval_count, "approval_count must not change");
    }
}
// ---- GENERATED BY QEDGEN — DO NOT EDIT BELOW THIS LINE ----
