// ---- GENERATED BY QEDGEN ---- spec-hash:af9201efab780d3c
//
// Self-contained Kani proof harnesses for the spec.
//
// These proofs verify the spec's transition design using Kani bounded model
// checking. They operate on a pure model of the state machine (derived from
// the qedspec), independent of framework (Quasar/Anchor) types.
//
//   Lean proves:  transition functions preserve invariants (∀ states)
//   Kani checks:  same properties via bounded model checking + overflow detection
//   Together:     high assurance that the spec design is correct
//
// To run:  cargo kani --harness <name>   (requires cargo-kani)
// ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----
#![cfg(kani)]

// ============================================================================
// State model (derived from qedspec — no framework dependencies)
// ============================================================================

const MAX_MEMBERS: u8 = 32;

#[derive(Clone, Copy)]
struct State {
    threshold: u8,
    member_count: u8,
    approval_count: u8,
}

// ============================================================================
// Property predicates (from qedspec `property` declarations)
// ============================================================================

/// threshold_bounded: s.threshold ≤ s.member_count ∧ s.threshold > 0
fn threshold_bounded(s: &State) -> bool {
    s.threshold <= s.member_count && s.threshold > 0
}

/// approvals_bounded: s.approval_count ≤ s.member_count
fn approvals_bounded(s: &State) -> bool {
    s.approval_count <= s.member_count
}

// ============================================================================
// Transition functions (from qedspec operations — effects + guards)
//
// Each returns true if the guard passes and the transition fires,
// false if the guard rejects the operation.
// ============================================================================

/// Create a new multisig vault with members and approval threshold
fn create_vault(s: &mut State, threshold: u8, member_count: u8) -> bool {
    if !(threshold > 0 && threshold <= member_count && member_count <= 32) {
        return false;
    }
    s.threshold = threshold;
    s.member_count = member_count;
    s.approval_count = 0;
    true
}

/// Submit a new transaction proposal — any vault member can propose
fn propose(s: &mut State) -> bool {
    s.approval_count = 0;
    true
}

/// Approve the current proposal — each member may approve once
fn approve(s: &mut State, member_index: u8) -> bool {
    if !(member_index < s.member_count && s.approval_count < s.member_count) {
        return false;
    }
    s.approval_count += 1;
    true
}

/// Execute the proposal once the approval threshold is met
fn execute(s: &mut State) -> bool {
    if !(s.approval_count >= s.threshold) {
        return false;
    }
    s.approval_count = 0;
    true
}

/// Cancel the current proposal and return to accepting new proposals
fn cancel_proposal(s: &mut State) -> bool {
    s.approval_count = 0;
    true
}

/// Remove a member from the vault — creator only
fn remove_member(s: &mut State) -> bool {
    if !(s.member_count > s.threshold && s.approval_count == 0) {
        return false;
    }
    s.member_count -= 1;
    true
}

// ============================================================================
// Guard enforcement — transitions reject invalid inputs
// ============================================================================

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_create_vault_rejects_invalid() {
    let mut s = State {
        threshold: kani::any(),
        member_count: kani::any(),
        approval_count: kani::any(),
    };
    let threshold: u8 = kani::any();
    let member_count: u8 = kani::any();
    kani::assume(!(true));
    assert!(!create_vault(&mut s, threshold, member_count),
        "create_vault must reject when guard is violated");
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_approve_rejects_invalid() {
    let mut s = State {
        threshold: kani::any(),
        member_count: kani::any(),
        approval_count: kani::any(),
    };
    let member_index: u8 = kani::any();
    kani::assume(!(true));
    assert!(!approve(&mut s, member_index),
        "approve must reject when guard is violated");
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_execute_rejects_invalid() {
    let mut s = State {
        threshold: kani::any(),
        member_count: kani::any(),
        approval_count: kani::any(),
    };
    kani::assume(!(true));
    assert!(!execute(&mut s),
        "execute must reject when guard is violated");
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_remove_member_rejects_invalid() {
    let mut s = State {
        threshold: kani::any(),
        member_count: kani::any(),
        approval_count: kani::any(),
    };
    kani::assume(!(true));
    assert!(!remove_member(&mut s),
        "remove_member must reject when guard is violated");
}

// ============================================================================
// Property preservation — invariants hold through all transitions
// ============================================================================

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_create_vault_preserves_threshold_bounded() {
    let mut s = State {
        threshold: 0,
        member_count: 0,
        approval_count: 0,
    };
    let threshold: u8 = kani::any();
    let member_count: u8 = kani::any();
    if create_vault(&mut s, threshold, member_count) {
        assert!(threshold_bounded(&s),
            "threshold_bounded must hold after create_vault");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_propose_preserves_threshold_bounded() {
    let mut s = State {
        threshold: kani::any(),
        member_count: kani::any(),
        approval_count: kani::any(),
    };
    kani::assume(threshold_bounded(&s));
    kani::assume(approvals_bounded(&s));
    kani::assume(s.member_count <= MAX_MEMBERS);
    if propose(&mut s) {
        assert!(threshold_bounded(&s),
            "threshold_bounded must hold after propose");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_approve_preserves_threshold_bounded() {
    let mut s = State {
        threshold: kani::any(),
        member_count: kani::any(),
        approval_count: kani::any(),
    };
    kani::assume(threshold_bounded(&s));
    kani::assume(approvals_bounded(&s));
    kani::assume(s.member_count <= MAX_MEMBERS);
    let member_index: u8 = kani::any();
    kani::assume(s.approval_count < s.member_count); // strict bound: approval_count increments
    if approve(&mut s, member_index) {
        assert!(threshold_bounded(&s),
            "threshold_bounded must hold after approve");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_execute_preserves_threshold_bounded() {
    let mut s = State {
        threshold: kani::any(),
        member_count: kani::any(),
        approval_count: kani::any(),
    };
    kani::assume(threshold_bounded(&s));
    kani::assume(approvals_bounded(&s));
    kani::assume(s.member_count <= MAX_MEMBERS);
    if execute(&mut s) {
        assert!(threshold_bounded(&s),
            "threshold_bounded must hold after execute");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_cancel_proposal_preserves_threshold_bounded() {
    let mut s = State {
        threshold: kani::any(),
        member_count: kani::any(),
        approval_count: kani::any(),
    };
    kani::assume(threshold_bounded(&s));
    kani::assume(approvals_bounded(&s));
    kani::assume(s.member_count <= MAX_MEMBERS);
    if cancel_proposal(&mut s) {
        assert!(threshold_bounded(&s),
            "threshold_bounded must hold after cancel_proposal");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_remove_member_preserves_threshold_bounded() {
    let mut s = State {
        threshold: kani::any(),
        member_count: kani::any(),
        approval_count: kani::any(),
    };
    kani::assume(threshold_bounded(&s));
    kani::assume(approvals_bounded(&s));
    kani::assume(s.member_count <= MAX_MEMBERS);
    if remove_member(&mut s) {
        assert!(threshold_bounded(&s),
            "threshold_bounded must hold after remove_member");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_create_vault_preserves_approvals_bounded() {
    let mut s = State {
        threshold: 0,
        member_count: 0,
        approval_count: 0,
    };
    let threshold: u8 = kani::any();
    let member_count: u8 = kani::any();
    if create_vault(&mut s, threshold, member_count) {
        assert!(approvals_bounded(&s),
            "approvals_bounded must hold after create_vault");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_propose_preserves_approvals_bounded() {
    let mut s = State {
        threshold: kani::any(),
        member_count: kani::any(),
        approval_count: kani::any(),
    };
    kani::assume(threshold_bounded(&s));
    kani::assume(approvals_bounded(&s));
    kani::assume(s.member_count <= MAX_MEMBERS);
    if propose(&mut s) {
        assert!(approvals_bounded(&s),
            "approvals_bounded must hold after propose");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_approve_preserves_approvals_bounded() {
    let mut s = State {
        threshold: kani::any(),
        member_count: kani::any(),
        approval_count: kani::any(),
    };
    kani::assume(threshold_bounded(&s));
    kani::assume(approvals_bounded(&s));
    kani::assume(s.member_count <= MAX_MEMBERS);
    let member_index: u8 = kani::any();
    kani::assume(s.approval_count < s.member_count); // strict bound: approval_count increments
    if approve(&mut s, member_index) {
        assert!(approvals_bounded(&s),
            "approvals_bounded must hold after approve");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_execute_preserves_approvals_bounded() {
    let mut s = State {
        threshold: kani::any(),
        member_count: kani::any(),
        approval_count: kani::any(),
    };
    kani::assume(threshold_bounded(&s));
    kani::assume(approvals_bounded(&s));
    kani::assume(s.member_count <= MAX_MEMBERS);
    if execute(&mut s) {
        assert!(approvals_bounded(&s),
            "approvals_bounded must hold after execute");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_cancel_proposal_preserves_approvals_bounded() {
    let mut s = State {
        threshold: kani::any(),
        member_count: kani::any(),
        approval_count: kani::any(),
    };
    kani::assume(threshold_bounded(&s));
    kani::assume(approvals_bounded(&s));
    kani::assume(s.member_count <= MAX_MEMBERS);
    if cancel_proposal(&mut s) {
        assert!(approvals_bounded(&s),
            "approvals_bounded must hold after cancel_proposal");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_remove_member_preserves_approvals_bounded() {
    let mut s = State {
        threshold: kani::any(),
        member_count: kani::any(),
        approval_count: kani::any(),
    };
    kani::assume(threshold_bounded(&s));
    kani::assume(approvals_bounded(&s));
    kani::assume(s.member_count <= MAX_MEMBERS);
    if remove_member(&mut s) {
        assert!(approvals_bounded(&s),
            "approvals_bounded must hold after remove_member");
    }
}

// ============================================================================
// Effect conformance — verify transition effects match spec
//
// Each proof applies a transition to symbolic state and checks that every
// field changed/unchanged matches the spec's effect: declarations.
// ============================================================================

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_create_vault_effects() {
    let mut s = State {
        threshold: 0,
        member_count: 0,
        approval_count: 0,
    };
    let threshold: u8 = kani::any();
    let member_count: u8 = kani::any();
    if create_vault(&mut s, threshold, member_count) {
        assert!(s.threshold == threshold, "threshold must equal threshold");
        assert!(s.member_count == member_count, "member_count must equal member_count");
        assert!(s.approval_count == 0, "approval_count must equal 0");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_propose_effects() {
    let mut s = State {
        threshold: kani::any(),
        member_count: kani::any(),
        approval_count: kani::any(),
    };
    kani::assume(s.member_count <= MAX_MEMBERS);
    let pre_threshold = s.threshold;
    let pre_member_count = s.member_count;
    if propose(&mut s) {
        assert!(s.approval_count == 0, "approval_count must equal 0");
        assert!(s.threshold == pre_threshold, "threshold must not change");
        assert!(s.member_count == pre_member_count, "member_count must not change");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_approve_effects() {
    let mut s = State {
        threshold: kani::any(),
        member_count: kani::any(),
        approval_count: kani::any(),
    };
    let member_index: u8 = kani::any();
    kani::assume(s.member_count <= MAX_MEMBERS);
    kani::assume(s.approval_count < s.member_count); // strict bound: approval_count increments
    let pre_threshold = s.threshold;
    let pre_member_count = s.member_count;
    let pre_approval_count = s.approval_count;
    if approve(&mut s, member_index) {
        assert!(s.approval_count == pre_approval_count + 1, "approval_count must increment by 1");
        assert!(s.threshold == pre_threshold, "threshold must not change");
        assert!(s.member_count == pre_member_count, "member_count must not change");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_execute_effects() {
    let mut s = State {
        threshold: kani::any(),
        member_count: kani::any(),
        approval_count: kani::any(),
    };
    kani::assume(s.member_count <= MAX_MEMBERS);
    let pre_threshold = s.threshold;
    let pre_member_count = s.member_count;
    if execute(&mut s) {
        assert!(s.approval_count == 0, "approval_count must equal 0");
        assert!(s.threshold == pre_threshold, "threshold must not change");
        assert!(s.member_count == pre_member_count, "member_count must not change");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_cancel_proposal_effects() {
    let mut s = State {
        threshold: kani::any(),
        member_count: kani::any(),
        approval_count: kani::any(),
    };
    kani::assume(s.member_count <= MAX_MEMBERS);
    let pre_threshold = s.threshold;
    let pre_member_count = s.member_count;
    if cancel_proposal(&mut s) {
        assert!(s.approval_count == 0, "approval_count must equal 0");
        assert!(s.threshold == pre_threshold, "threshold must not change");
        assert!(s.member_count == pre_member_count, "member_count must not change");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_remove_member_effects() {
    let mut s = State {
        threshold: kani::any(),
        member_count: kani::any(),
        approval_count: kani::any(),
    };
    kani::assume(s.member_count <= MAX_MEMBERS);
    let pre_threshold = s.threshold;
    let pre_member_count = s.member_count;
    let pre_approval_count = s.approval_count;
    if remove_member(&mut s) {
        assert!(s.member_count == pre_member_count - 1, "member_count must decrement by 1");
        assert!(s.threshold == pre_threshold, "threshold must not change");
        assert!(s.approval_count == pre_approval_count, "approval_count must not change");
    }
}

// ============================================================================
// Cover properties — reachability via kani::cover!
// ============================================================================

#[kani::proof]
#[kani::unwind(5)]
#[kani::solver(cadical)]
fn cover_proposal_lifecycle() {
    let mut s = State {
        threshold: kani::any(),
        member_count: kani::any(),
        approval_count: kani::any(),
    };
    let threshold_0: u8 = kani::any();
    let member_count_0: u8 = kani::any();
    if create_vault(&mut s, threshold_0, member_count_0) {
        if propose(&mut s) {
            let member_index_2: u8 = kani::any();
            if approve(&mut s, member_index_2) {
                kani::cover!(execute(&mut s), "proposal_lifecycle trace is reachable");
            }
        }
    }
}

#[kani::proof]
#[kani::unwind(4)]
#[kani::solver(cadical)]
fn cover_cancel_flow() {
    let mut s = State {
        threshold: kani::any(),
        member_count: kani::any(),
        approval_count: kani::any(),
    };
    let threshold_0: u8 = kani::any();
    let member_count_0: u8 = kani::any();
    if create_vault(&mut s, threshold_0, member_count_0) {
        if propose(&mut s) {
            kani::cover!(cancel_proposal(&mut s), "cancel_flow trace is reachable");
        }
    }
}

// ============================================================================
// Liveness properties — bounded reachability via non-deterministic ops
// ============================================================================

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_liveness_proposal_resolves() {
    let mut s = State {
        threshold: kani::any(),
        member_count: kani::any(),
        approval_count: kani::any(),
    };
    for _ in 0..1 {
        let op: u8 = kani::any();
        match op {
            0 => {
                execute(&mut s);
            }
            1 => {
                cancel_proposal(&mut s);
            }
            _ => {}
        }
    }
    // Target: from HasProposal to Active within 1 steps
}

// ============================================================================
// Overflow detection — Kani catches arithmetic overflow on add effects
// ============================================================================

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_approve_no_overflow() {
    let mut s = State {
        threshold: kani::any(),
        member_count: kani::any(),
        approval_count: kani::any(),
    };
    let member_index: u8 = kani::any();
    approve(&mut s, member_index);  // Kani detects overflow on += internally
}

// ---- GENERATED BY QEDGEN — DO NOT EDIT BELOW THIS LINE ----
