// ---- GENERATED BY QEDGEN — DO NOT EDIT ABOVE THIS LINE ---- spec-hash:eae38f7c4bb765bb
use quasar_lang::prelude::*;
use crate::state::*;
use crate::errors::*;

#[derive(Accounts)]
pub struct Deposit {
    #[account(mut)]
    pub authority: Signer,
    #[account(mut)]
    pub vault: Account<()>,
}

impl Deposit {
    /// User adds capital — V and C_tot increase by same amount
    #[inline(always)]
    pub fn handler(&mut self, amount: u128) -> Result<(), ProgramError> {
        // AGENT: implement business logic here
        // Spec effect: V add amount
        // Spec effect: C_tot add amount
        todo!()
    }
}
// ---- GENERATED BY QEDGEN — DO NOT EDIT BELOW THIS LINE ----
