// ---- GENERATED BY QEDGEN — DO NOT EDIT ABOVE THIS LINE ---- spec-hash:dc22e85f543d6b11
use quasar_lang::prelude::*;
use crate::state::*;
use crate::errors::*;

#[derive(Accounts)]
pub struct TopUpInsurance {
    #[account(mut)]
    pub authority: Signer,
    #[account(mut)]
    pub vault: Account<()>,
}

impl TopUpInsurance {
    /// External deposit into insurance fund
    #[inline(always)]
    pub fn handler(&mut self, amount: u128) -> Result<(), ProgramError> {
        // AGENT: implement business logic here
        // Spec effect: V add amount
        // Spec effect: I add amount
        todo!()
    }
}
// ---- GENERATED BY QEDGEN — DO NOT EDIT BELOW THIS LINE ----
