// ---- GENERATED BY QEDGEN — DO NOT EDIT ABOVE THIS LINE ---- spec-hash:50b9a602fca09863
use quasar_lang::prelude::*;
use crate::state::*;
use crate::errors::*;

#[derive(Accounts)]
pub struct Withdraw {
    #[account(mut)]
    pub authority: Signer,
    #[account(mut)]
    pub vault: Account<()>,
}

impl Withdraw {
    /// User removes capital — V and C_tot decrease by same amount
    #[inline(always)]
    pub fn handler(&mut self, amount: u128) -> Result<(), ProgramError> {
        // AGENT: implement business logic here
        // Spec effect: V sub amount
        // Spec effect: C_tot sub amount
        todo!()
    }
}
// ---- GENERATED BY QEDGEN — DO NOT EDIT BELOW THIS LINE ----
